.rubocop.yml, Gemfile, Gemfile.lock, spec/decorators/base_decorator_spec.rb, spec/helpers/application_helper_spec.rb, spec/helpers/form_builder_helper_spec.rb, spec/lib/feature_flags_spec.rb, spec/lib/host_env_spec.rb, spec/presenters/base_presenter_spec.rb, spec/rails_helper.rb, spec/requests/healthcheck_spec.rb
- apply rubocop and rubocop-rspec to the spec directory
- fix all issues raised
=> Tp robocop rspec

.rubocop.yml, Gemfile, Gemfile.lock, spec/decorators/base_decorator_spec.rb, spec/helpers/application_helper_spec.rb, spec/helpers/form_builder_helper_spec.rb, spec/lib/feature_flags_spec.rb, spec/lib/host_env_spec.rb, spec/presenters/base_presenter_spec.rb, spec/rails_helper.rb, spec/requests/healthcheck_spec.rb
=> Use rubocop on specs

config/kubernetes/staging/config_map.yml
=> Add AzureAd config for staging

config/initializers/omniauth.rb
=> Add azure ad staging config

config/kubernetes/staging/ingress.yml
=> Remove basic auth as we have formal login

app/lib/api_client.rb
=> Ignore ssl on dev api.

config/kubernetes/staging/config_map.yml
=> Use public url for dev api.

Dockerfile
See:
https://github.com/sgerrand/alpine-pkg-glibc/issues/185#issuecomment-1261935191
=> Attempt to fix build issue

config/kubernetes/staging/config_map.yml
=> Update staging dev api url

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/crime_applications_controller.rb, app/events/assigning.rb, app/lib/application_struct.rb, app/models/assignment.rb, app/models/crime_application.rb, app/models/user.rb, app/views/crime_applications/_assignment.html.erb, app/views/crime_applications/show.html.erb, app/views/shared/_flash_banner.html.erb, config/initializers/rails_event_store.rb, config/locales/en.yml, config/routes.rb, db/migrate/20221114114421_create_event_store_events.rb, db/schema.rb, spec/system/assign_an_application_to_myself_spec.rb
An authenticated user can assign an application to themselves.
[CRIMRE-49](https://dsdmoj.atlassian.net/browse/CRIMRE-49)
Sources assigned user from event store.
=> CRIMRE-49 Assign to myself

Gemfile, Gemfile.lock, app/controllers/assigned_applications_controller.rb, app/models/crime_application.rb, app/models/current_assignment.rb, app/models/user.rb, app/views/application/_crime_application.html.erb, app/views/assigned_applications/index.html.erb, app/views/crime_applications/_current_assignment.html.erb, app/views/crime_applications/show.html.erb, config/environments/development.rb, config/environments/test.rb, config/locales/en.yml, config/routes.rb, spec/fixtures/files/crime_apply_data/applications.json, spec/fixtures/files/crime_apply_data/applications/1aa4c689-6fb5-47ff-9567-5eee7f8ac2cc.json, spec/init/api_data.rb, spec/init/event_store.rb, spec/rails_helper.rb, spec/requests/azure_ad_logout_spec.rb, spec/shared_contexts/logged_in_user.rb, spec/system/applications_dashboard_spec.rb, spec/system/assign_an_application_to_myself_spec.rb, spec/system/viewing_your_assigned_applications_spec.rb
Adds your list page (current user's assigned applications)
[CRIMRE-66](https://dsdmoj.atlassian.net/browse/CRIMRE-66)
Determining a users assigned applications is done in ruby for now based on the list from the data api. How this will work in the future may be determined by the final datastore design.
=> CRIMRE-66 view assigned applications

app/lib/api_resource.rb, spec/init/api_data.rb
Stop memoizing crime applications collection.
=> Don't memoize all

app/commands/assigning.rb, app/controllers/assigned_applications_controller.rb, app/controllers/crime_applications_controller.rb, app/events/assigning.rb, app/lib/application_struct.rb, app/models/crime_application.rb, app/models/current_assignment.rb, app/models/user.rb, app/views/application/_crime_application.html.erb, app/views/crime_applications/_current_assignment.html.erb, app/views/crime_applications/index.html.erb, app/views/crime_applications/show.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, config/routes.rb, spec/system/applications_dashboard_spec.rb, spec/system/assign_an_application_to_myself_spec.rb, spec/system/primary_nav_spec.rb, spec/system/sub_nav_spec.rb, spec/system/unassign_an_application_from_myself_spec.rb, spec/system/viewing_an_application_spec.rb, spec/system/viewing_your_assigned_applications_spec.rb
User can unassign an application.
[CRIMRE-53](https://dsdmoj.atlassian.net/browse/CRIMRE-53)
=> CRIMRE 53 User can unassign an application.

app/commands/assigning.rb, app/controllers/crime_applications_controller.rb, app/models/application_history.rb, app/models/application_history_event.rb, app/models/crime_application.rb, app/views/crime_applications/history.html.erb, app/views/shared/_subnavigation.html.erb, config/locales/en.yml, config/routes.rb, spec/system/sub_nav_spec.rb, spec/system/viewing_application_history_spec.rb
Shows application history
[CRIMRE-69](https://dsdmoj.atlassian.net/browse/CRIMRE-69)
=> CRIMRE-69 view application history

app/views/layouts/application.html.erb
Adds a back link to the application
(CRIMRE-74)[https://dsdmoj.atlassian.net/browse/CRIMRE-74]
- Navigate through the app
- click the link
- Does it take you back to the page you were last on?
=> Add back link to app

app/commands/assigning.rb, app/controllers/application_controller.rb, app/controllers/assigned_applications_controller.rb, app/controllers/reassigns_controller.rb, app/lib/api_resource.rb, app/models/application_history.rb, app/models/application_history_event.rb, app/models/crime_application.rb, app/models/current_assignment.rb, app/views/crime_applications/_current_assignment.html.erb, app/views/reassigns/new.html.erb, app/views/shared/_flash_banner.html.erb, config/locales/en.yml, config/routes.rb, spec/system/assign_an_application_to_myself_spec.rb, spec/system/reassign_an_application_to_myself_spec.rb, spec/system/viewing_application_history_spec.rb
Can reassign an assigned application to themselves.
[CRIMRE-68](https://dsdmoj.atlassian.net/browse/CRIMRE-68)
Basic error for not found added. Need to bring correct pages over from apply.
app/commands in need of a tidy/refactor
Confirm Page:
Success notification
Reasignment in history
When reassigned to another whilst on confirm page:
=> CRIMRE-68 reassign an application

app/models/application_search.rb, app/models/application_search_filter.rb, app/models/crime_application.rb, spec/system/search_applications/filter_by_date_range_spec.rb
Filter by submission date.
[CRIMRE-81](https://dsdmoj.atlassian.net/browse/CRIMRE-81)
Building on https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/48
Adds filtering by submission date.
=> CRIMRE-81 search by date range

app/controllers/assigned_applications_controller.rb, app/views/assigned_applications/index.html.erb, config/routes.rb, spec/system/get_next_application_spec.rb
Adds get_next functionality
[CRIMRE-76](https://dsdmoj.atlassian.net/browse/CRIMRE-76)
Your list --> click "Get next application"
Have you been assigned the correct application?
=> Add get next functionality + spec

app/views/application/_application_search_filter.html.erb, app/views/application_searches/show.html.erb, config/locales/en.yml, spec/system/applications_dashboard_spec.rb, spec/system/search_applications/search_filters_and_results_spec.rb
Added subtitles in search fields, updated assigned to to caseworker, added status column, added generic spec for search fields and results.
https://dsdmoj.atlassian.net/browse/CRIMRE-115
=> CRIMRE-115 Update search

app/views/application/_application_search_filter.html.erb, app/views/application_searches/show.html.erb, config/locales/en.yml
=> Remove unused date values, move status to locale

config/initializers/datastore_client.rb, spec/init/api_data.rb
Point to the v2 datastore api.
=> Use V2 datastore

app/controllers/assigned_applications_controller.rb, app/views/assigned_applications/_application_table.html.erb, app/views/assigned_applications/index.html.erb, app/views/crime_applications/_current_assignment.html.erb, app/views/crime_applications/show.html.erb, config/locales/en.yml, config/routes.rb, spec/system/assign_an_application_to_myself_spec.rb, spec/system/get_next_application_spec.rb, spec/system/reassign_an_application_to_myself_spec.rb, spec/system/sub_nav_spec.rb
=> Removed success flash on get next, fixed style and layout on your list

app/views/application_searches/_no_search_results.html.erb, app/views/application_searches/_search_results_table.html.erb, app/views/application_searches/_search_results_table_body.html.erb, app/views/application_searches/show.html.erb, app/views/assigned_applications/_application_table.html.erb, app/views/crime_applications/_crime_applications_table.html.erb, app/views/crime_applications/_crime_applications_table_body.html.erb, app/views/crime_applications/_history_item.html.erb, app/views/crime_applications/history.html.erb, app/views/crime_applications/index.html.erb, config/locales/en.yml
Removed some of the looping, and use collection partials instead for things like table bodies etc.
For the changed files corresponding pages, check they render correctly
=> Some view refactoring

app/views/assigned_applications/index.html.erb
=> Adjust spacing to match designs

app/views/layouts/_primary_navigation.html.erb
Fix for aria naming to get nav highlighting working again
=> Fix aria current page name for open applications

app/views/application_searches/_no_search_results.html.erb, config/locales/en.yml
=> Update no results copy

Gemfile.lock, app/views/crime_applications/_application_ctas.erb, app/views/crime_applications/_offences.html.erb, app/views/crime_applications/show.html.erb, config/locales/en.yml, spec/fixtures/files/crime_apply_data/applications.json, spec/fixtures/files/crime_apply_data/applications/1aa4c689-6fb5-47ff-9567-5eee7f8ac2cc.json, spec/fixtures/files/crime_apply_data/applications/5aa4c689-6fb5-47ff-9567-5efe7f8ac211.json, spec/fixtures/files/crime_apply_data/applications/696dd4fd-b619-4637-ab42-a5f4565bcf4a.json, spec/fixtures/files/crime_apply_data/closed_applications.json, spec/fixtures/files/crime_apply_data/open_applications.json, spec/system/unassign_an_application_from_myself_spec.rb, spec/system/viewing_application_history_spec.rb
Adds status badge at top of view application page
Adds buttons to view application page for Completing, Sending back and Unassigning - all three conditionally shown to the assigned user when the case is currently open. 
Adds links as per designs regardless of user/appln status
https://dsdmoj.atlassian.net/browse/CRIMRE-51
=> CRIME-51 Mark as complete part 1 - UI

.rubocop.yml, app/views/crime_applications/_current_assignment.html.erb, spec/system/viewing_an_application_spec.rb
Added tests to ensure CTAs show on correct states, and status banners are correct per status. Also improving to ensure buttons have correct copy when assigned/unassigned/assigned to another 
Designs for status badge/assignement/dates https://www.figma.com/file/TELZW9jdNqFcrI4yZoH7BV/Crime-Review?node-id=4491%3A16813&t=hAjiuqIqCfLVzKtP-1
=> Add tests for CTA work, revert lost view application format

app/controllers/returns_controller.rb, app/models/return_details.rb, app/views/crime_applications/_case_details.html.erb, app/views/crime_applications/_client_details.html.erb, app/views/crime_applications/_codefendants.html.erb, app/views/crime_applications/_current_assignment.html.erb, app/views/crime_applications/_interests_of_justice.html.erb, app/views/crime_applications/_offences.html.erb, app/views/crime_applications/_overview.html.erb, app/views/crime_applications/_provider_details.html.erb, app/views/crime_applications/show.html.erb, app/views/returns/new.html.erb, config/locales/en.yml, config/locales/en/errors.yml, spec/fixtures/files/crime_apply_data/applications/5aa4c689-6fb5-47ff-9567-5efe7f8ac211.json, spec/system/reviewing/send_back_to_provider_spec.rb, spec/system/viewing_an_application_spec.rb
I have ended up using this branch to resolve quite a few bits, apologies that it's not wide-reaching and not focussed
Main point of contention may be around how we consider an application's assignment after it has been returned - I have left all as is and been hacky with regard to 'Reviewed by' and conditionality of buttons etc. But I am aware of the issues leaving a closed application assigned will have on Your list application count among other issues.
=> Tidy front end

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/application_searches_controller.rb, app/controllers/assigned_applications_controller.rb, app/controllers/crime_applications_controller.rb, app/models/application_search.rb, app/models/application_search_filter.rb, app/models/get_next.rb, app/models/pagination.rb, app/views/application/_application_search_filter.html.erb, app/views/application_searches/_search_results_table_body.html.erb, app/views/application_searches/show.html.erb, app/views/assigned_applications/index.html.erb, app/views/crime_applications/index.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/layouts/_primary_navigation.html.erb, config/locales/en.yml, config/routes.rb, spec/models/application_search_filter_spec.rb, spec/shared_contexts/with_stubbed_search.rb, spec/system/assigning/viewing_your_assigned_applications_spec.rb, spec/system/closed_applications_dashboard_spec.rb
Co-authored-by: willmcb <william.mcbrien@digital.justice.gov.uk>
Adds pagination to search, open and closed applications, and your list.
[CRIMRE-87](https://dsdmoj.atlassian.net/browse/CRIMRE-87)
[CRIMRE-87]: https://dsdmoj.atlassian.net/browse/CRIMRE-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMRE-87 Basic implementation of pagination

app/aggregates/reviewing/commands/load_review.rb, app/aggregates/reviewing/review.rb, app/models/application_search_filter.rb, app/models/application_search_result.rb, app/models/concerns/assignable.rb, app/models/concerns/reviewable.rb, app/models/crime_application.rb, app/read_models/current_assignments/configuration.rb, app/views/application_searches/_search_results_table_body.html.erb, app/views/crime_applications/_assignment.html.erb, app/views/crime_applications/_client_details.html.erb, app/views/crime_applications/_closed_crime_applications_table_body.html.erb, app/views/crime_applications/_open_crime_applications_table_body.html.erb, app/views/crime_applications/_review_overview.html.erb, app/views/crime_applications/history.html.erb, app/views/crime_applications/show.html.erb, config/locales/en.yml, spec/aggregates/reviewing/complete_spec.rb, spec/aggregates/reviewing/receive_application_spec.rb, spec/aggregates/reviewing/review_spec.rb, spec/aggregates/reviewing/send_back_spec.rb, spec/init/api_data.rb, spec/system/closed_applications_dashboard_spec.rb, spec/system/reviewing/send_back_to_provider_spec.rb, spec/system/viewing_an_application_spec.rb, spec/system/viewing_application_history_spec.rb
CRIMRE-147 show reviewer and refactor
Event source review and assignment information in lists and show pages.
Extract assignment and review code.
[CRIMRE-147](https://dsdmoj.atlassian.net/browse/CRIMRE-147)
Still not decided how create the received_event. I expect this will be driven out with the mini-report work.
Also added an issue for creating shared contexts for specs so tests can easily access applications in the common states: 
https://github.com/ministryofjustice/laa-review-criminal-legal-aid/issues/112
[CRIMRE-147]: https://dsdmoj.atlassian.net/browse/CRIMRE-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Crimre 147 show review

app/read_models/current_assignments/configuration.rb, config/locales/en.yml, spec/system/reviewing/mark_application_as_complete_spec.rb
Unassign an application on completion.
[CRIMRE-151](https://dsdmoj.atlassian.net/browse/CRIMRE-151)
[CRIMRE-151]: https://dsdmoj.atlassian.net/browse/CRIMRE-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMRE-151 unassign on completion

app/models/application_history.rb, app/views/application_history_items/_reviewing_completed.html.erb, config/locales/en.yml, spec/system/viewing_an_application/history_spec.rb
Adds completed events to an application history
[CRIMRE-176](https://dsdmoj.atlassian.net/browse/CRIMRE-176)
[CRIMRE-176]: https://dsdmoj.atlassian.net/browse/CRIMRE-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add completed event to app history + spec

app/aggregates/assigning/command.rb, app/aggregates/reviewing/command.rb, app/models/application_history.rb, app/models/concerns/assignable.rb, app/models/concerns/reviewable.rb, spec/models/crime_application_spec.rb, spec/spec_helper.rb
Capture branch coverage
Add unit test for CrimeApplication
This is the beginning of a wider refactor of the specs now the model interfaces are more tied down.
=> Capture branch coverage

app/views/crime_applications/_case_details.html.erb, app/views/crime_applications/_client_details.html.erb, app/views/crime_applications/_offences.html.erb, app/views/crime_applications/_overview.html.erb, config/locales/en.yml, spec/system/closed_applications_dashboard_spec.rb, spec/system/open_applications_dashboard_spec.rb, spec/system/searching/search_filters_and_results_spec.rb
Fixed/tidied a few things as per designs and in discussion with Carol
Added Partner field default to no
Reverted date formats on dashboards
Reformatted offences for duplicate offences to show on their own rows one per date
Added 'Class' for offence class
=> Tidied a few presentation errors

app/controllers/api/events_controller.rb
=> Log AWS request for debugging.

app/controllers/api/events_controller.rb, spec/requests/api/events_spec.rb
SNS callback request body is json.
AWS/SNS sends the body as JSON but specifies the content type as text. This PR handles that.
=> SNS request body is json

app/controllers/api/events_controller.rb
To aid with debugging, log request body for SNS event callback. Previously we were just logging the params.
=> Log request body on event callback

app/lib/types.rb, app/models/table_header.rb
Adds time passed to sort columns - sorting by date submitted
Removes Reference from sort column
This is in line with UR/designs/in discussion with Carol
=> remove sort by ref no, map time passed to submitted at

spec/models/concerns/assignable_spec.rb, spec/models/sorting_spec.rb
Adds unit tests for Sortable and Assignment concern
=> Crimre 181 unit tests

app/views/application_history_items/_reviewing_application_received.html.erb, app/views/crime_applications/history.html.erb, spec/spec_helper.rb
Refactor out current version logic 
Small lint tidy to shorten line length and improve readability
Add comment for SimpleCov filtering
Responding to comments on https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/149
=> Refactor based on PR comments

app/controllers/application_controller.rb, app/controllers/errors_controller.rb, app/views/errors/forbidden.html.erb, config/initializers/omniauth.rb, config/initializers/warden.rb, config/locales/en/errors.yml, config/routes.rb, lib/warden/strategies/azure_ad.rb, spec/requests/authentication_spec.rb
- show not authorised page when users are not found locally
- show not authorised page when callback phase fails
[CRIMRE-194](https://dsdmoj.atlassian.net/browse/CRIMRE-194)
[CRIMRE-194]: https://dsdmoj.atlassian.net/browse/CRIMRE-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMRE-194 Handle not authorised users

app/controllers/application_controller.rb, app/controllers/errors_controller.rb, app/models/user.rb, app/views/errors/forbidden.html.erb, config/initializers/omniauth.rb, config/initializers/warden.rb, config/locales/en/errors.yml, config/routes.rb, db/migrate/20230306151554_add_deactivated_at_to_users.rb, db/schema.rb, lib/warden/strategies/azure_ad.rb, spec/models/user_spec.rb, spec/requests/authentication_spec.rb
Add deactivated_at to users.
Prevent deactivated users from authenticating.
[CRIMRE-196](https://dsdmoj.atlassian.net/browse/CRIMRE-196)
[CRIMRE-196]: https://dsdmoj.atlassian.net/browse/CRIMRE-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMRE 196 deactivate a user

.rubocop.yml, app/controllers/admin/manage_users_controller.rb, app/controllers/application_controller.rb, app/views/admin/manage_users/edit.html.erb, app/views/admin/manage_users/index.html.erb, config/locales/en.yml, config/routes.rb, spec/system/manage_users/edit_user_spec.rb, spec/system/manage_users/viewing_spec.rb
https://dsdmoj.atlassian.net/browse/CRIMRE-191
=> CRIMRE-191 Edit manage others

.codeclimate.yml
=> Add basic .codeclimage.yml config file

app/aggregates/aggregate_loader.rb, app/aggregates/assigning.rb, app/aggregates/reviewing.rb
Removes a small amount of duplication - running as a test of CodeClimate really
=> Remove duplication identified by CodeClimate

app/controllers/admin/manage_users_controller.rb, spec/system/manage_users/viewing_spec.rb
Ordered user list first name and last name
https://dsdmoj.atlassian.net/browse/CRIMRE-205
=> CRIMRE-205 Order user list first name and last name

app/views/admin/manage_users/index.html.erb, config/locales/en.yml, spec/system/manage_users/viewing_spec.rb
Shows last authentication access at
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMRE/boards/960/backlog?view=detail&selectedIssue=CRIMRE-206&issueLimit=100
=> CRIMRE-206 Show Last Auth At

config/locales/en.yml, spec/system/manage_users/add_user_spec.rb, spec/system/manage_users/deactivate_a_user_spec.rb, spec/system/manage_users/edit_user_spec.rb
=> Update copy, correct sp, remove unused I18N attributes

app/views/crime_applications/_assignment.html.erb, app/views/returns/new.html.erb, spec/shared_contexts/with_an_existing_application.rb, spec/shared_contexts/with_an_existing_user.rb, spec/system/accessibility_spec.rb, spec/system/assigning/assign_an_application_to_myself_spec.rb, spec/system/assigning/reassign_an_application_confirmation_spec.rb, spec/system/assigning/reassign_an_application_to_myself_spec.rb, spec/system/manage_users/deactivate_a_user_spec.rb, spec/system/manage_users/edit_user_spec.rb, spec/system/reviewing/mark_application_as_complete_spec.rb, spec/system/reviewing/send_back_to_provider_spec.rb, spec/system/viewing_an_application/history_spec.rb
Implements accessibility testing to the main journey routes and the default view of those pages for users. To implement this, shared context files have been created  for common application states (e.g. having an existing application). This addresses [ issue 112 ](https://github.com/ministryofjustice/laa-review-criminal-legal-aid/issues/112) in part 
[CRIMRE-241](https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMRE/boards/960?modal=detail&selectedIssue=CRIMRE-241)
Two accessibility issues were flagged and corrected as part of this ticket. 
The first error raised was where there was a dt element missing in a summary table. [Error explained here](https://dequeuniversity.com/rules/axe/4.6/definition-list?application=axeAPI)
Upon further inspection, it did not seem like an appropriate …
=> CRIMRE-241 add accessibility testing to additional routes

Dockerfile
Adds missing escape character in dockerfile which should fix the build
=> Add missing escape character in dockerfile

app/aggregates/assigning/assignment.rb, app/aggregates/assigning/errors.rb, app/controllers/reassigns_controller.rb, config/locales/en.yml, spec/system/assigning/reassign_an_application_confirmation_errors_spec.rb
Update reassign confirm error messaging.
[CRIMRE-102](https://dsdmoj.atlassian.net/browse/CRIMRE-102)
[CRIMRE-102]: https://dsdmoj.atlassian.net/browse/CRIMRE-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMRE-102 clarify reassign confirm error messages

app/views/crime_applications/_review_overview.html.erb, config/locales/en.yml, spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
Change copy link to "Copy reference number"
Move Copy to en.yml 
Increase spacing between reference number and copy link as per designs
https://dsdmoj.atlassian.net/browse/CRIMRE-263
=> Update copy reference number copy

config/locales/en.yml
Update nav links at the bottom of show application view
https://dsdmoj.atlassian.net/browse/CRIMRE-264
=> Update nav links at the bottom of show application view

config/locales/en.yml, spec/system/assigning/reassign_an_application_confirmation_errors_spec.rb, spec/system/assigning/reassign_an_application_to_myself_spec.rb, spec/system/viewing_an_application/history_spec.rb, spec/system/viewing_an_application/that_is_assigned_to_somone_else_spec.rb
Update reassign CTA from "Reassign to myself" to "Reassign to your list"
https://dsdmoj.atlassian.net/browse/CRIMRE-270
=> Update reassign CTA 

config/locales/en.yml, spec/system/assigning/assign_an_application_to_myself_spec.rb, spec/system/assigning/unassign_an_application_from_myself_spec.rb, spec/system/assigning/viewing_your_assigned_applications_spec.rb, spec/system/primary_nav_spec.rb, spec/system/viewing_an_application/history_spec.rb, spec/system/viewing_an_application/that_is_assigned_to_me_spec.rb, spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
Update assign to self CTA from "Assign to myself" to "Assign to your list"
https://dsdmoj.atlassian.net/browse/CRIMRE-266
=> Update assign to self CTA

app/views/application_history_items/_reviewing_application_received.html.erb, app/views/crime_applications/history.html.erb, config/locales/en.yml, spec/system/viewing_an_application/history_spec.rb, spec/system/viewing_an_application/history_when_a_resubmission_spec.rb
Modify links in application history
https://dsdmoj.atlassian.net/browse/CRIMRE-293
=> Modify links in application history

app/controllers/reassigns_controller.rb, app/views/crime_applications/_offences.html.erb, config/locales/en.yml, spec/system/assigning/assign_an_application_to_myself_spec.rb, spec/system/assigning/reassign_an_application_confirmation_errors_spec.rb, spec/system/assigning/reassign_an_application_to_myself_spec.rb, spec/system/assigning/unassign_an_application_from_myself_spec.rb, spec/system/manage_users/viewing_spec.rb, spec/system/reviewing/mark_application_as_complete_spec.rb, spec/system/reviewing/mark_application_as_ready_spec.rb, spec/system/reviewing/send_back_to_provider_spec.rb
Updated all banner content as requested in the Google sheet
https://dsdmoj.atlassian.net/browse/CRIMRE-284
https://docs.google.com/spreadsheets/d/1SHMV188G6Y1l_g3NR4sGai9UuTzrjoBNTQrGLGhKpC0/edit#gid=0
=> CRIMRE-284-Updated all banner content

app/views/application_history_items/_reviewing_application_received.html.erb, app/views/crime_applications/history.html.erb, config/locales/en.yml, spec/system/viewing_an_application/history_spec.rb, spec/system/viewing_an_application/history_when_a_resubmission_spec.rb
=> Revert some previous links, correct event names

app/views/crime_applications/_overview.html.erb, spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
=> Fix date stamp field to read from date stamp attribute

config/initializers/datastore_client.rb, spec/init/api_data.rb, spec/system/viewing_an_application/history_spec.rb
This needs to go together or soon after this other PR: https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/88
https://dsdmoj.atlassian.net/browse/CRIMAP-350
=> Use v1 of the datastore

Gemfile, Gemfile.lock, config/initializers/filter_parameter_logging.rb, config/initializers/lograge.rb
This is a port of[ this PR from Apply ](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/280)and the same ideas should apply to it.
@timpeat do you think there are any review specific bits of data that we should add as custom payloads?
On locally this new log stream to stdout can seen and tested by running the app in production mode.
In our k8s namespaces, logs will output to stdout and can be accessed in Kibana.
=> Configure lograge + log to Stdout

config/locales/en.yml
Updated IOJ reason translations to match Apply
https://dsdmoj.atlassian.net/browse/CRIMRE-314
Translations in Apply https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/blob/bfd7db7629cc3b7504e9b2814642a6ee3cc523f3/config/locales/en/summary.yml#L116
=> Update ioj reason translations

app/mailers/notify_mailer.rb, config/locales/en.yml, spec/mailers/notify_mailer_spec.rb
Adds prose descriptors of return reasons as per designs.
=> Add better email messages

config/kubernetes/production/config_map.yml, config/kubernetes/staging/config_map.yml, docker-compose.yml
Configure staging an production to log to stdout
=> Configure staging an production to log to stdout

config/locales/en/devise.yml, spec/system/authenticating/a_dormant_user_spec.rb, spec/system/authenticating/a_signed_out_user_spec.rb
Add missing translation for unauthorised users attepting access
https://dsdmoj.atlassian.net/browse/CRIMRE-326
Copy not confirmed by content design
Sign out
Go to /assigned_applications
=> Add missing translation for unauthorised users attepting access

.github/workflows/test-build-deploy.yml
=> Add snyk docker image scanning to pipeline

Gemfile.lock, app/controllers/admin/manage_users/deactivated_users_controller.rb, app/controllers/reports_controller.rb, app/models/user.rb, app/views/admin/manage_users/active_users/_actions.html.erb, app/views/admin/manage_users/deactivated_users/_actions.html.erb, app/views/admin/manage_users/deactivated_users/_table_cells.html.erb, app/views/admin/manage_users/deactivated_users/_table_headers.html.erb, app/views/admin/manage_users/deactivated_users/confirm_reactivate.html.erb, app/views/admin/manage_users/deactivated_users/new.html.erb, app/views/admin/manage_users/index.html.erb, app/views/admin/manage_users/invitations/_actions.html.erb, app/views/admin/manage_users/invitations/confirm_destroy.html.erb, app/views/admin/manage_users/invitations/confirm_renew.html.erb, config/locales/en.yml, config/locales/en/manage_users.yml, config/routes.rb, spec/requests/authorisation_spec.rb, spec/shared_contexts/when_not_logged_in.rb, spec/system/authenticating/a_dormant_user_spec.rb, spec/system/authenticating/a_signed_out_user_spec.rb, spec/system/authenticating/dev_auth_spec.rb, spec/system/authenticating/sign_out_spec.rb, spec/system/manage_users/reactivate_a_user_spec.rb
Deactivated users can be reactivated
Add deactivated users tab to manage users
[CRIMRE-349](https://dsdmoj.atlassian.net/browse/CRIMRE-349)
[CRIMRE-349]: https://dsdmoj.atlassian.net/browse/CRIMRE-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Deactivated users can be reactivated

Gemfile, Gemfile.lock
Bump schema from 0.2.0 to 0.2.1
=> Bump schema from 0.2.0 to 0.2.1

config/locales/en.yml
=> Add missing passport translation

config/application.rb
Set time zone to London
We were displaying times in UTC.
=> Set time_zone to London

app/aggregates/reviewing.rb, app/controllers/crime_applications_controller.rb, config/locales/en.yml
Simplify review error handling
[CRIMRE-374](https://dsdmoj.atlassian.net/browse/CRIMRE-374)
This is part of a series of changes to simplify error handling in the application.
[CRIMRE-374]: https://dsdmoj.atlassian.net/browse/CRIMRE-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Simpify Reviewing exception handling

config/kubernetes/production/service.yml, config/kubernetes/staging/service.yml
Fix incorrect namespace in service.yml
https://dsdmoj.atlassian.net/browse/CRIMRE-384
Incorrect namespaces (mixed up with app name)
=> [CRIMRE-384] Fix namespace

.github/workflows/snyk-container.yml, .github/workflows/snyk-infrastructure.yml
Change so that Snyk runs on chron rather than every branch - should make the pipline a little faster.
=> Snyk to run on chron job rather every branch / PR

Gemfile, Gemfile.lock, spec/system/viewing_an_application/address_details_spec.rb, spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
=> Bump schema to 1.0.0

Gemfile.lock
=> Bump Datastore API client to v1.0.0

config/locales/en.yml
Removes duplicate keys in translation file
N/A
Are the duplicate keys meant to have a different name?
=> CHORE Remove duplicate translation keys

config/application.rb
Based on user feedback, also lines up with timeout duration on MAAT.
Also removes some whitespace
=> Change timeout from 15 to 30 mins

config/locales/en.yml, config/locales/en/manage_users.yml
Removes whitespaces which causes problems with diffs
N/A
=> [CHORE] Clean translation files

config/settings.yml
Enable the search by age in business day feature on staging
=> CRIMAP-499 Enable Search by Age in Business Day Feature on Staging

app/controllers/performance_tracking_controller.rb, app/models/reporting/caseworker_report.rb, app/views/performance_tracking/index.html.erb, config/locales/en/reporting.yml, db/schema.rb, spec/models/reporting/caseworker_report_spec.rb, spec/system/performance_tracking/viewing_spec.rb
Add basic user report to performance tracking page.
[CRIMAP-541](https://dsdmoj.atlassian.net/browse/CRIMAP-541)
[CRIMAP-541]: https://dsdmoj.atlassian.net/browse/CRIMAP-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMRE-541-basic-caseworker-report

app/views/application/_application_search_filter.html.erb, config/settings.yml
Remove age in business day filter Feature Flag
[CRIMAP-537](https://dsdmoj.atlassian.net/browse/CRIMAP-537)
This feature has been released to all environments
[CRIMAP-537]: https://dsdmoj.atlassian.net/browse/CRIMAP-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAP-537 remove feature flag

.github/workflows/test-build-deploy.yml
=> Also removes : in the tag name for a hyphen which is supported in tags

app/controllers/reporting/user_reports_controller.rb, app/controllers/reporting/weekly_reports_controller.rb, app/lib/types.rb, app/models/reporting/monthly_report.rb, app/models/reporting/weekly_report.rb, app/views/reporting/user_reports/index.html.erb, app/views/reporting/weekly_reports/show.html.erb, config/brakeman.ignore, config/locales/en.yml, config/locales/en/reporting.yml, config/routes.rb, spec/requests/authorisation_spec.rb, spec/system/reporting/monthly_reports_spec.rb, spec/system/reporting/weekly_reports_spec.rb
View full weeks report.
[CRIMAP-543](https://dsdmoj.atlassian.net/browse/CRIMAP-543)
[CRIMAP-543]: https://dsdmoj.atlassian.net/browse/CRIMAP-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAP-543 view latest full week

config/kubernetes/staging/ingress.yml
=> remove ingress comments

config/kubernetes/production/ingress.yml
Remove comments from production ingress yaml.
As per recent fix to staging ingress.
=> Remove comments from production ingress config

config/kubernetes/staging/ingress.yml
Use the correct modsecurity rule id in exception to allow AWS SNS 
https://dsdmoj.atlassian.net/browse/CRIMAP-655
N/A
=> [CRIMAP-655] Add correct modsecurity rule (STAGING ONLY)

config/settings.yml
Allow user roles in production.
[CRIMAP-679](https://dsdmoj.atlassian.net/browse/CRIMAP-679)
Feature flag itself will be removed once the deploy has been confirmed.
[CRIMAP-679]: https://dsdmoj.atlassian.net/browse/CRIMAP-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAP-679 allow user roles in production

config/settings.yml
Enables evidence upload in production
https://dsdmoj.atlassian.net/browse/CRIMAPP-66
=> [CRIMAP-66] Enable evidence upload production

Dockerfile, config/clamd/clamd.docker.conf, config/clamd/clamd.local.conf, config/clamd/clamd.staging.conf, config/kubernetes/staging/config_map.yml, config/kubernetes/staging/deployment-clamav.yml
Introduces clamav deployment to verify whether the clamav server has specific configuration preventing operation in apply production
https://dsdmoj.atlassian.net/browse/CRIMAPP-66
This PR is only to verify configuration correctness and help to document the setup procedure.
=> [TEST] Add clamav statefulset deployment

Dockerfile
No need to install clam etc on Review
https://dsdmoj.atlassian.net/browse/CRIMAPP-66
For staging only, not for production
=> [TEST] Remove unnecessary clamd install

config/settings.yml
This reverts commit 5e6a7c543398261ee6933b799f3bb80a4d290fb1.
=> Revert "Temporarily disable work stream feature on staging (#475)"

Gemfile, Gemfile.lock
=> Bump schema to v1.0.18

config/settings.yml
Turns evidence upload ff to true on prod
=> Turn on evidence upload in prod

config/settings.yml
=> disable work streams on staging

app/models/application_search_result.rb, app/models/application_search_sorting.rb, app/views/casework/application_searches/_search_results_table_body.html.erb, app/views/casework/application_searches/search.html.erb, config/locales/en/casework.yml, spec/shared_contexts/with_stubbed_search.rb, spec/system/casework/closed_applications_dashboard_spec.rb, spec/system/casework/searching/search_filters_and_results_spec.rb, spec/system/casework/searching/sorting_search_results_spec.rb
Adds case type and application type to search results table. Case type is also added as a filter to sort.
This was requested in user research around reporting where it would be useful to have the case type and the application type (initial application or change in financial circumstances) in the absence of the case summary report and to allow them to carry out quality control checks
[CRIMAPP-282](https://dsdmoj.atlassian.net/browse/CRIMAPP-282)
Needs to be merged after the datastore changes are merged: https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/192
Requires building datastore from this branch: https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/192
Once you have pulled down and built datastore and review, navigate to the search …
=> [CRIMAPP-282] Add case and application type to search results

config/settings.yml
=> Enable Work Streams in all environments

app/views/casework/crime_applications/show.html.erb, config/settings.yml
Removes evidence_upload feature flag from review
[RIMAPP-294](https://dsdmoj.atlassian.net/browse/CRIMAPP-294)
=> [CRIMAPP-294] Remove evidence upload ff from review

app/controllers/concerns/work_streamable.rb, app/models/concerns/user_competence.rb, app/views/casework/assigned_applications/_crime_application.html.erb, app/views/casework/assigned_applications/index.html.erb, app/views/casework/crime_applications/index.html.erb, config/settings.yml, spec/models/concerns/user_competence_spec.rb, spec/requests/authorisation_spec.rb, spec/system/casework/assigning/viewing_your_assigned_applications_spec.rb, spec/system/casework/closed_applications_dashboard_spec.rb, spec/system/casework/no_competencies_spec.rb, spec/system/casework/open_applications_dashboard_spec.rb, spec/system/casework/primary_nav_spec.rb
Removes `work_streams` feature flag from review
=> [CRIMAPP-293] Remove work streams feature flag

Gemfile, Gemfile.lock, config/initializers/sentry.rb
Adds profilling and performance monitoring for sentry
See:
https://docs.sentry.io/product/performance
https://docs.sentry.io/product/profiling
=> Enable sentry profiling and performance monitoring

config/settings.yml
=> Remove means journey ff duplication

Gemfile.lock
=> Upgrade puma to 6.4.2

Dockerfile
=> Upgrade to alpine 3.19

app/views/casework/application_searches/_search_results_table_body.html.erb, app/views/casework/application_searches/search.html.erb, app/views/casework/assigned_applications/_crime_application.html.erb, app/views/casework/assigned_applications/index.html.erb, app/views/casework/crime_applications/_closed_crime_applications_table_body.html.erb, app/views/casework/crime_applications/_closed_crime_applications_table_headers.html.erb, app/views/casework/crime_applications/_open_crime_applications_table_body.html.erb, app/views/casework/crime_applications/_open_crime_applications_table_headers.html.erb, config/locales/en/reporting.yml, config/settings.yml, spec/system/casework/assigning/viewing_your_assigned_applications_spec.rb, spec/system/casework/closed_applications_dashboard_spec.rb, spec/system/casework/open_applications_dashboard_spec.rb, spec/system/casework/searching/search_filters_and_results_spec.rb
Adds column displaying application type to the open/closed application, search and assigned application tables 
Adds pse feature flag 
[CRIMAPP-376](https://dsdmoj.atlassian.net/browse/CRIMAPP-376)
Build review from this branch and then navigate to the following pages and check the table displayed has a column for application type, displaying the application type expected
- Assigned applications page (Your list)
- Open applications page
- Closed applications page
- Application search results page
Note: Make sure you have built datastore and crime apply from main
- Submit a standard application in apply and review the application in review (as can only submit pse for applications that are complete)
- Then go back to apply and find the application in the submitted tab. Click on the …
=> [CRIMAPP-376] Display application type across review

Gemfile, Gemfile.lock
Allows Outgoings Payments submission/rehydration
https://dsdmoj.atlassian.net/browse/CRIMAPP-217
https://dsdmoj.atlassian.net/browse/CRIMAPP-218
N/A
N/A
Create a new application in Apply with outgoings, submit the application, return the Application in review and 'update' in Apply
=> [CRIMAPP-218] Bump schema v1.0.40

Gemfile, Gemfile.lock
Bump Schema to latest 1.0.44
N/A
N/A
N/A
=> [CHORE] Bump Schema to 1.0.44

Gemfile, Gemfile.lock
Bump Schema v1.0.46 which includes outgoings updates
https://dsdmoj.atlassian.net/browse/CRIMAPP-497
N/A
N/A
=> [CRIMAPP-497] Bump Schema v1.0.46

app/controllers/manage_competencies/base_controller.rb, app/controllers/manage_competencies/caseworker_competencies_controller.rb, app/controllers/manage_competencies/history_controller.rb
Manage competencies controllers use the same user scope.
=> Move user scope to base controller

Gemfile, Gemfile.lock
Bump Schema v1.0.56 which includes changed `property` and `property owner` columns
=> Update schema version to v1.0.56

.rubocop.yml, Gemfile, app/components/card_component.rb, app/helpers/app_text_helper.rb, app/helpers/application_helper.rb, app/views/casework/crime_applications/_capital_details.html.erb, app/views/casework/crime_applications/_initial.html.erb, app/views/casework/crime_applications/sections/_investments.html.erb, app/views/casework/crime_applications/sections/_national_savings_certificates.html.erb, app/views/casework/crime_applications/sections/_premium_bonds.html.erb, app/views/casework/crime_applications/sections/_savings.html.erb, config/locales/en.yml, config/locales/en/casework.yml, spec/components/card_component_spec.rb, spec/rails_helper.rb, spec/support/matchers/summary_card.rb, spec/support/view_component.rb, spec/system/casework/viewing_an_application/application_details/investments_spec.rb, spec/system/casework/viewing_an_application/application_details/national_savings_certificates_spec.rb, spec/system/casework/viewing_an_application/application_details/premium_bonds_spec.rb, spec/system/casework/viewing_an_application/application_details/savings_spec.rb
Adds savings, investments, premium bonds and certificates to Review
[CRIMAPP-584](https://dsdmoj.atlassian.net/browse/CRIMAPP-584)
[CRIMAPP-569](https://dsdmoj.atlassian.net/browse/CRIMAPP-569)
[CRIMAPP-553](https://dsdmoj.atlassian.net/browse/CRIMAPP-553)
[CRIMAPP-558](https://dsdmoj.atlassian.net/browse/CRIMAPP-558)
[CRIMAPP-584]: https://dsdmoj.atlassian.net/browse/CRIMAPP-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-569]: https://dsdmoj.atlassian.net/browse/CRIMAPP-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-553]: https://dsdmoj.atlassian.net/browse/CRIMAPP-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> Show capital savings, investments, premium bonds and certificates

config/settings.yml
Turn pse feature flag to `true` on production
=> Enable pse on prod

Gemfile, Gemfile.lock
=> Upgrade schema to v1.0.61

Gemfile, Gemfile.lock
=> bump schema

Gemfile, Gemfile.lock, app/views/casework/crime_applications/_income_details.html.erb, app/views/casework/crime_applications/_outgoings_details.html.erb, app/views/casework/crime_applications/sections/_dependants.html.erb, app/views/casework/crime_applications/sections/_housing_payments.html.erb, app/views/casework/crime_applications/sections/_income_benefits.html.erb, app/views/casework/crime_applications/sections/_income_payments.html.erb, app/views/casework/crime_applications/sections/_national_savings_certificates.html.erb, app/views/casework/crime_applications/sections/_other_outgoings_details.html.erb, app/views/casework/crime_applications/sections/_outgoing_payments.html.erb, app/views/casework/crime_applications/sections/_premium_bonds.html.erb, spec/shared_contexts/with_stubbed_application.rb, spec/system/casework/viewing_an_application/application_details/dependants_spec.rb, spec/system/casework/viewing_an_application/application_details/national_savings_certificates_spec.rb, spec/system/casework/viewing_an_application/application_details/other_outgoings_details_spec.rb, spec/system/casework/viewing_an_application/application_details/outgoing_payments_spec.rb, spec/system/casework/viewing_an_application/application_details/premium_bonds_spec.rb
Do not show dependants question if not asked.
[CRIMAPP-757](https://dsdmoj.atlassian.net/browse/CRIMAPP-757)
[CRIMAPP-757]: https://dsdmoj.atlassian.net/browse/CRIMAPP-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Do not show dependants if not answered

config/settings.yml
Turn means journey to `true` on production
=> Enable means journey on production

app/views/casework/crime_applications/_supporting_evidence.html.erb, config/locales/en/casework.yml
=> [CRIMAPP-649] Display other income, outgoings, capital prompts in review

app/views/casework/application_searches/_search_results_table_body.html.erb, app/views/casework/application_searches/search.html.erb, app/views/casework/assigned_applications/_crime_application.html.erb, app/views/casework/assigned_applications/index.html.erb, app/views/casework/crime_applications/_closed_crime_applications_table_body.html.erb, app/views/casework/crime_applications/_closed_crime_applications_table_headers.html.erb, app/views/casework/crime_applications/_open_crime_applications_table_body.html.erb, app/views/casework/crime_applications/_open_crime_applications_table_headers.html.erb, config/settings.yml
Removes unrequired pse feature flag
[CRIMAPP-708](https://dsdmoj.atlassian.net/browse/CRIMAPP-708)
[CRIMAPP-708]: https://dsdmoj.atlassian.net/browse/CRIMAPP-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-708] Remove pse feature flag

Gemfile, Gemfile.lock
=> Increment schema to v1.1.5

Gemfile, Gemfile.lock, app/presenters/income_payments_presenter.rb, app/presenters/outgoing_payments_presenter.rb, app/views/casework/crime_applications/_income_details.html.erb, app/views/casework/crime_applications/sections/_applicant_other_work_benefits.html.erb, app/views/casework/crime_applications/sections/_applicant_self_assessment_tax_bill.html.erb, app/views/casework/crime_applications/sections/_employment_income.html.erb, app/views/casework/crime_applications/sections/_work_benefits.html.erb, config/locales/en/casework.yml
Display the following sections in Review App
- Pay from employment
- Self Assessment tax
- Other work benefits
https://dsdmoj.atlassian.net/browse/CRIMAPP-878
=> CRIMAPP-875 rehydrate employment standalone pages

Gemfile, Gemfile.lock, app/presenters/income_payments_presenter.rb, app/presenters/outgoing_payments_presenter.rb, app/views/casework/crime_applications/_income_details.html.erb, app/views/casework/crime_applications/sections/_applicant_self_assessment_tax_bill.html.erb, config/settings.yml, spec/system/casework/viewing_an_application/application_details/income_details_spec.rb
Add self assessment tax bill attributes to income 
https://dsdmoj.atlassian.net/browse/CRIMAPP-875
=> CRIMAPP-875-refactor-self-assessment-tax-bill

Gemfile, Gemfile.lock
=> Upgrade schema to v1.1.13

Gemfile, Gemfile.lock
=> Upgrade schema to v1.1.14

Gemfile, Gemfile.lock
=> Upgrade schema to v1.1.19

config/settings.yml
=> Disable employment journey for staging

Gemfile, Gemfile.lock
=> Update schema version to v1.1.22

app/views/casework/crime_applications/sections/_passporting_benefit_check_partner.html.erb
=> Call correct helper method to determine partner being shown

config/settings.yml
=> Enable partner in production

config/settings.yml
=> Enable employment on staging

config/settings.yml
Turn on employment feature flag in prod
=> Turn on employment feature flag in prod

app/lib/types.rb, app/models/reporting/workload_report.rb, app/read_models/received_on_reports/projection.rb, config/locales/en.yml, config/locales/en/casework.yml, spec/models/reporting/workload_report_spec.rb, spec/system/casework/assigning/get_next_application_spec.rb, spec/system/reporting/workload_report_spec.rb
- users can be assigned change in financial circumstances competency
- change in financial circumstance applications appear in reporting
[CRIMAPP-1182](https://dsdmoj.atlassian.net/browse/CRIMAPP-1182)
[CRIMAPP-1182]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-1182 add Change in financial circumstances competency

Gemfile, Gemfile.lock, app/lib/types.rb, app/models/work_stream.rb, config/locales/en.yml, spec/models/reporting/workload_report_spec.rb
=> Crimapp 1183 add non means tested workstream

app/views/casework/crime_applications/sections/_businesses.html.erb, spec/system/casework/viewing_an_application/application_details/businesses_spec.rb
Display conditional partnership/director stakeholder business question answers
[CRIMAPP-983](https://dsdmoj.atlassian.net/browse/CRIMAPP-983)
[CRIMAPP-984](https://dsdmoj.atlassian.net/browse/CRIMAPP-984)
[CRIMAPP-985](https://dsdmoj.atlassian.net/browse/CRIMAPP-985)
[CRIMAPP-983]: https://dsdmoj.atlassian.net/browse/CRIMAPP-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-984]: https://dsdmoj.atlassian.net/browse/CRIMAPP-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-985]: https://dsdmoj.atlassian.net/browse/CRIMAPP-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-983, 984, 985] Display remaining self employed answers

config/settings.yml
=> Turn on self employed ff on staging

config/settings.yml
Turn on self employed ff on production
=> Turn on self employed ff

app/views/casework/crime_applications/_appeal_no_changes.html.erb
Fix appeal no changes
[LAA-REVIEW-CRIMINAL-LEGAL-AID-X](https://ministryofjustice.sentry.io/issues/5621783525/)
=> FIX blocking bug - specs forthcoming

Gemfile, Gemfile.lock, app/models/crime_application.rb, app/views/casework/crime_applications/_initial.html.erb, app/views/casework/crime_applications/_overview.html.erb, app/views/casework/crime_applications/show.html.erb, config/locales/en/casework.yml, spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Fix display for CIFC application
https://dsdmoj.atlassian.net/browse/CRIMAPP-1173
=> CRIMAPP-1173: Fix CIFC display

app/views/casework/crime_applications/_case_details.html.erb
=> FIX missing court info

Gemfile, Gemfile.lock, app/views/casework/crime_applications/_case_details.html.erb, app/views/casework/crime_applications/sections/_appeal_case_details.html.erb, app/views/casework/crime_applications/sections/_savings.html.erb, spec/shared_contexts/with_stubbed_application.rb, spec/system/casework/viewing_an_application/application_details/case_details_spec.rb
Include non appeal case in case details specs.
Refactor case_details to make it easier to see where blocks start and end.
=> Spec hearing details when case is not appeal

config/locales/en/casework.yml
A case worker reported this small content issue, it won't be in the ticket but i've fixed as part of CRIMAPP-1266
https://dsdmoj.atlassian.net/browse/CRIMAPP-1266
=> [CRIMAPP-1266] Content fixes

config/locales/en/casework.yml, spec/system/casework/viewing_an_application/application_details/income_details_spec.rb
[CRIMAPP-1285](https://dsdmoj.atlassian.net/browse/CRIMAPP-1285)
[CRIMAPP-1285]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-1285 Update content for self assessment tax bill

Gemfile, Gemfile.lock
Upgrade schema to v1.2.4
https://dsdmoj.atlassian.net/browse/CRIMAPP-1119
=> Upgrade schema to v1.2.4

config/kubernetes/staging/deployment.tpl
Adjust the readiness and liveness delay for staging
[CRIMAPP-345](https://dsdmoj.atlassian.net/browse/CRIMAPP-345)
Minor adjustment to delay initial liveness probe on staging.
[CRIMAPP-345]: https://dsdmoj.atlassian.net/browse/CRIMAPP-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-345 Adjust the readiness and liveness delay for staging

Gemfile, Gemfile.lock, app/views/casework/crime_applications/_client_details.html.erb, app/views/casework/crime_applications/_partner_details.html.erb, config/locales/en/casework.yml, spec/system/casework/viewing_an_application/application_details/partner_details_spec.rb, spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Display ARC number if present 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1181
=> [CRIMAPP-1181] Display arc

config/kubernetes/staging/deployment.tpl
Add startup probe to staging
[CRIMAPP-345](https://dsdmoj.atlassian.net/browse/CRIMAPP-345)
Attempt to fix 503 on readiness probe.
[CRIMAPP-345]: https://dsdmoj.atlassian.net/browse/CRIMAPP-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-345 Experiment with startup probe

config/kubernetes/staging/deployment.tpl
=> CRIMAPP-345 Remove tabs

config/initializers/lograge.rb
=> [CRIMAPP-345] log requests to health check for debugging

config/settings.yml
Enable adding decisions on staging.
=> Enable adding decisions on staging

Gemfile, Gemfile.lock, app/views/casework/crime_applications/_initial.html.erb, app/views/casework/crime_applications/_other_charge.html.erb, config/locales/en/casework.yml, config/settings.yml, spec/system/casework/viewing_an_application/application_details/client_other_charge_spec.rb, spec/system/casework/viewing_an_application/application_details/partner_other_charge_spec.rb
Show any other charges the client or partner might have.
[CRIMAPP-825](https://dsdmoj.atlassian.net/browse/CRIMAPP-825)
[CRIMAPP-825]: https://dsdmoj.atlassian.net/browse/CRIMAPP-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-825] Other charges

config/settings.yml
Enable other_charges in production.
[CRIMAPP-825](https://dsdmoj.atlassian.net/browse/CRIMAPP-825)
[CRIMAPP-825]: https://dsdmoj.atlassian.net/browse/CRIMAPP-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Enable other_charges in prod

app/views/casework/crime_applications/_partner_details.html.erb, spec/system/casework/viewing_an_application/application_details/partner_details_spec.rb, spec/system/casework/viewing_an_application/client_contact_details_spec.rb
Handle missing partner address
https://dsdmoj.atlassian.net/browse/CRIMAPP-1386
Urgent bug fix.
=> LAA-REVIEW-CRIMINAL-LEGAL-AID-1M

app/lib/types.rb, spec/models/application_search_filter_spec.rb, spec/system/casework/searching/filter_by_age_in_business_days_spec.rb, spec/system/casework/searching/filter_by_caseworker_spec.rb, spec/system/casework/searching/filter_by_date_of_birth_spec.rb, spec/system/casework/searching/filter_by_date_range_spec.rb, spec/system/casework/searching/filter_by_status_spec.rb
Reverts ministryofjustice/laa-review-criminal-legal-aid#722
=> Revert "[CRIMAPP-1385] Update search default to all applications"

config/kubernetes/production/ingress.yml
Updated the ModSec rules in production to prevent common false positives on select endpoints.
=> Update ModSec rules in production

app/components/decision_component.rb, app/controllers/casework/decisions/interests_of_justices_controller.rb, app/controllers/casework/decisions/overall_results_controller.rb, app/controllers/casework/decisions_controller.rb, app/controllers/casework/maat_decisions_controller.rb, config/routes.rb, spec/requests/authorisation_spec.rb, spec/system/casework/deciding/adding_a_cifc_decision_spec.rb, spec/system/casework/deciding/adding_a_maat_decision_by_maat_id_spec.rb, spec/system/casework/deciding/adding_a_maat_decision_by_reference_spec.rb
https://dsdmoj.atlassian.net/browse/CRIMAPP-1486
Submit a non means application in apply. In review, assign the non means application to your list and start the funding decision. From the IoJ page, before you enter any details press `save and continue` twice
Then click back and verify that it navigates back the ioj page instead of being shown an error message
=> [CRIMAPP-1486] Refactor decision routes

app/components/decision_component.rb, app/models/crime_application.rb, app/models/flash_notice.rb, app/views/casework/crime_applications/_funding_decision.html.erb, app/views/casework/crime_applications/show.html.erb, app/views/casework/decisions/comments/edit.html.erb, app/views/casework/decisions/interests_of_justices/edit.html.erb, app/views/casework/decisions/overall_results/edit.html.erb, app/views/casework/maat_decisions/edit.html.erb, app/views/casework/maat_decisions/new.html.erb, app/views/casework/send_decisions/new.html.erb, config/locales/en/casework.yml, spec/models/flash_notice_spec.rb, spec/system/casework/deciding/updating_a_decision_from_maat_spec.rb
Made the required UI changes to the decision flow as per the latest designs.
[CRIMAPP-1488](https://dsdmoj.atlassian.net/browse/CRIMAPP-1488)
[CRIMAPP-1488]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1488] Update decision flow

app/components/client_remanded_value_component.rb, app/helpers/components_helper.rb, app/models/crime_application.rb, app/presenters/client_details_presenter.rb, app/views/casework/base/_assignment.html.erb, app/views/casework/crime_applications/_case_details.html.erb, app/views/casework/crime_applications/_overview.html.erb, config/locales/en/casework.yml, spec/components/client_remanded_value_component_spec.rb, spec/presenters/client_details_presenter_spec.rb, spec/system/casework/viewing_an_application/application_details/case_details_spec.rb, spec/system/casework/viewing_an_application/application_details/overview_spec.rb, spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Updated the overview cards and made other content and UI improvements to the application details page.
[CRIMAPP-1505](https://dsdmoj.atlassian.net/browse/CRIMAPP-1505)
[CRIMAPP-1505]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1505] Update overview cards & other improvements

app/views/casework/crime_applications/_overview.html.erb, spec/system/casework/viewing_an_application/application_details/overview_spec.rb
Changed the date format of 'Date submitted' in the overview summary card to include the time.
[CRIMAPP-1511](https://dsdmoj.atlassian.net/browse/CRIMAPP-1511)
[CRIMAPP-1511]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1511] Update date submitted format

app/views/casework/application_searches/_application_search_filter.html.erb
https://dsdmoj.atlassian.net/browse/CRIMAPP-1524
=> [CRIMAPP-1524] Replace labels with headers for accessibility

Gemfile, Gemfile.lock
Upgrade Rails 7.2.2. and related dependencies.
=> Upgrade rails to 7.2.2 and related dependencies

config/initializers/govuk_components.rb
Update GOVUK link to: https://www.gov.uk/
[CRIMAPP-1525](https://dsdmoj.atlassian.net/browse/CRIMAPP-1525)
[CRIMAPP-1525]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1525] update homepage URL

config/locales/en/casework.yml, spec/system/casework/assigning/viewing_your_assigned_applications_spec.rb, spec/system/casework/open_applications_dashboard_spec.rb, spec/system/casework/searching/filter_by_age_in_business_days_spec.rb
Changes to content in the 'Provider details' card and application table headings.
[CRIMAPP-1463](https://dsdmoj.atlassian.net/browse/CRIMAPP-1463)
[CRIMAPP-1463]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1463] Content issues

Gemfile, Gemfile.lock
Updates debug gem which needed updating as errors were being thrown when spinning up a rails console
=> Update debug gem

app/aggregates/reviewing/available_reviewer_actions.rb, app/models/concerns/type_of_application.rb, app/models/crime_application.rb, app/views/casework/send_decisions/new.html.erb, spec/system/casework/deciding/adding_another_maat_decision_spec.rb, spec/system/casework/deciding/submitting_a_non_means_decision_spec.rb
Updates submit decision form for non means applications following feedback from user research 
Changes:
- hide ‘What do you want to do next?’ and the radio buttons block
- replace ‘Save and continue’ button with a button saying ‘Send decision to provider’ 
- hide H2 ‘You have added 1 case’
https://dsdmoj.atlassian.net/browse/CRIMAPP-1600
Submit a non means application and then start adding the funding decision on review 
After adding any decision comments you should see a screen with a summary card of the decision and a button to submit the decision to the provider 
Verify the changes listed above have been made and then confirm that you can submit a non means decision
=> [CRIMAPP-1600] Update non means submit decision form

config/settings.yml
Enable decisions in production
[CRIMAPP-1642](https://dsdmoj.atlassian.net/browse/CRIMAPP-1642)
[CRIMAPP-1642]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1642] enable decisions in production

config/kubernetes/production/config_map.yml
Allow linking to older MAAT decisions in production
[CRIMAPP-1645](https://dsdmoj.atlassian.net/browse/CRIMAPP-1645)
[CRIMAPP-1645]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1645] allow linking to older MAAT decisions

app/assets/stylesheets/application.scss, app/assets/stylesheets/local/custom.scss, app/assets/stylesheets/local/govuk.scss, app/assets/stylesheets/local/moj.scss, app/views/casework/application_searches/_application_search_filter.html.erb, app/views/casework/assigned_applications/index.html.erb, config/initializers/assets.rb, package.json, yarn.lock
- Upgrade MoJ Frontend to 4.0 from 2.2.5 
- Upgrade GOVUK Frontend to 5.9 from 5.7.1
=> Use MoJ Frontend 4.0

config/kubernetes/production/config_map.yml
Update first supported MAAT ID in production to 7000000
[CRIMAPP-1685](https://dsdmoj.atlassian.net/browse/CRIMAPP-1685)
[CRIMAPP-1685]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1685] update first supported MAAT ID to 7000000

.trivyignore
Do not alert cloud platform vulnerabilities
Reduce noise from Prometheus alerts for vulnerabilities we are unable to fix as they are on Cloud platform--who are alerted separately.
Tested and confirmed vulnerabilities not present in local image.
=> Update alert ignored vulnerability

config/settings.yml
Prevent user managers having service access on staging
=> Prevent user managers having service access on staging

config/settings.yml
Reverts ministryofjustice/laa-review-criminal-legal-aid#841
=> Revert "Prevent user managers having service access on staging"

config/settings.yml
Revoke user managers having service access on staging for testing
=> Revoke user manager service access on staging

config/kubernetes/production/config_map.yml
Update first supported MAAT ID in production to 6000000
https://dsdmoj.atlassian.net/browse/CRIMAPP-1685
=> [CRIMAPP-1685] Update first supported maat id to 6000000

app/models/reporting/monthly_report.rb, app/models/reporting/weekly_report.rb, app/views/reporting/temporal_reports/_return_reasons_report.en.html.erb, config/locales/en/casework.yml, spec/models/reporting/monthly_report_spec.rb, spec/models/reporting/temporal_report_spec.rb, spec/models/reporting/weekly_report_spec.rb, spec/system/casework/assigning/viewing_your_assigned_applications_spec.rb, spec/system/casework/closed_applications_dashboard_spec.rb, spec/system/casework/open_applications_dashboard_spec.rb, spec/system/casework/searching/search_filters_and_results_spec.rb, spec/system/reporting/monthly_reports_spec.rb, spec/system/reporting/return_reasons_report_spec.rb, spec/system/reporting/weekly_reports_spec.rb
Updates listed in ticket acceptance criteria
https://dsdmoj.atlassian.net/browse/CRIMAPP-1701
=> [CRIMAPP-1701] Content updates to reports

package.json, yarn.lock
Upgrade moj frontend to 5.1.0 from 4.0.1
=> Upgrade moj frontend to 5.1.0 from 4.0.1

.trivyignore
Ignore Trivy vulns outside of our control
=> Ignore Trivy vulns outside of our control

config/locales/en/casework.yml, spec/system/casework/viewing_an_application/application_details/overview_spec.rb
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?selectedIssue=CRIMAPP-1784
Visit `applications/<case-uuid>`
=> [CRIMAPP-1784] Change passporting benefit label in review

config/kubernetes/production/ingress.yml, config/kubernetes/staging/ingress.yml
PR to disable http connections following security recommendation 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1822
=> [CRIMAPP-1822] Disable http connections

Gemfile.lock
Update thor to 1.4.0 from 1.3.2
[CRIMAPP-1861](https://dsdmoj.atlassian.net/browse/CRIMAPP-1861)
[CRIMAPP-1861]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update thor to 1.4.0 from 1.3.2
