ministryofjustice/laa-review-criminal-legal-aid

- .env.development
- .env.test
- Gemfile
- Gemfile.lock
- app/controllers/crime_applications_controller.rb
- app/controllers/home_controller.rb
- app/lib/api_client.rb
- app/lib/api_resource.rb
- app/lib/types.rb
- app/models/crime_application.rb
- app/views/crime_applications/index.html.erb
- app/views/crime_applications/show.html.erb
- config/environments/development.rb
- config/locales/en.yml
- config/routes.rb
- spec/fixtures/files/crime_apply_data/applications.json
- spec/init/webmock.rb
- spec/rails_helper.rb
- spec/requests/applications_list_spec.rb
- spec/requests/home_spec.rb
- spec/support/shared_contexts_for_crime_apply_api.rb
- spec/system/applications_dashboard_spec.rb
Applications from Crime Apply can be viewed on the applications dashboard.
additionally:
- use rack_test for system specs by default
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMRE/boards/960?modal=detail&selectedIssue=CRIMRE-23
Test coverage in this exploratory phase comes primarily from system and not unit tests. 
The rational for this being:
- the architecture is experimental and likely to change 
- user expectations are decoupled from architecture, more evolved, less likely to change
- if the architecture changes, the system specs will be useful in catching regressions
- the data store is a stubbed http request to the dev api, so system specs are fast
Install puma-dev and configure https://laa-apply-for-criminal-legal-aid.test to point to apply and …
> CRIMRE-23 view list of applications

- app/lib/types.rb
- app/models/interest_of_justice.rb
- app/views/crime_applications/_co_defendants.html.erb
- app/views/crime_applications/_interests_of_justice.html.erb
- app/views/crime_applications/show.html.erb
- config/locales/en.yml
- spec/fixtures/files/crime_apply_data/applications.json
- spec/fixtures/files/crime_apply_data/applications/696dd4fd-b619-4637-ab42-a5f4565bcf4a.json
- spec/system/applications_dashboard_spec.rb
Adds Interests of Justice and Co-defendants to review page.
[CRIMRE-31](https://dsdmoj.atlassian.net/browse/CRIMRE-31)
[CRIMRE-32](https://dsdmoj.atlassian.net/browse/CRIMRE-32)
NB: this does not include tag styling (see: https://dsdmoj.atlassian.net/browse/CRIMRE-62 )
This omits the table headings for offences and IoJ shown on the design.
> Crimre 31 co defendants

- README.md
Adds some basic documentation to the readme for the use of `puma-dev` for local development with the api
n/a
- does this make sense? happy to rewrite if not etc.
> Add some docs for puma dev

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/moj.scss
- app/views/crime_applications/_co_defendants.html.erb
- app/views/crime_applications/_overview.html.erb
- package.json
- yarn.lock
Imports badge component for MoJ design system
[CRIMRE-62](https://dsdmoj.atlassian.net/browse/CRIMRE-62)
- I have only added the badge component to the build, we can require others as needed. This stops us needing to import everything and reduces the scss namespace to avoid clashes etc. similar approach used on apply.
Overview section:
Co-defendants section:
Overview section:
Co-defendants section:
- run `yarn install`
- got to app url > click through to an application's show page > see the new badges.
> Crimre 62 add moj badge tag styles

- app/views/crime_applications/_interests_of_justice.html.erb
- config/locales/en.yml
Display offences as a table 
[CRIMRE-32](https://dsdmoj.atlassian.net/browse/CRIMRE-32)
Design requirement
> Display iojs as a table

- app/views/crime_applications/_offences.html.erb
- config/locales/en.yml
Display offences as a table 
[CRIMRE-30](https://dsdmoj.atlassian.net/browse/CRIMRE-30)
Design requirement.
> Display offences as a table

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/moj.scss
- app/controllers/application_controller.rb
- app/views/assigned_applications/index.html.erb
- app/views/crime_applications/index.html.erb
- app/views/layouts/_primary_navigation.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/govuk_template.html.erb
- config/locales/en.yml
- spec/helpers/application_helper_spec.rb
- spec/helpers/form_builder_helper_spec.rb
- spec/system/primary_nav_spec.rb
Adds primary nav to the application
[CRIMRE-72](https://dsdmoj.atlassian.net/browse/CRIMRE-72)
- I have left out 'closed applications' as they don't exist yet
- click on primary nav a link - it should have the blue highlight under it after being clicked
- the 'Your list' page should reflect the number of applications in your list
- if you go to an application show page then none of the nav links should have the blue highlight
> Crimre 72 primary nav

- app/assets/stylesheets/local/moj.scss
- app/views/crime_applications/show.html.erb
- app/views/shared/_subnavigation.html.erb
- config/locales/en.yml
- spec/system/sub_nav_spec.rb
Implements sub navigation on view application page. 2 links, one for Application details and one for Application history (which is not yet hooked up)
https://dsdmoj.atlassian.net/browse/CRIMRE-35
As Application history not yet working, this links out to heathcheck - it is possible to inspect the link for Application details to view the correct aria-current tag, but not for history until this is available to implement. 
Go to all applications, click on an applicant name to view application - see the sub navigation
> Implement sub nav

- app/views/crime_applications/_current_assignment.html.erb
Makes "Assign to self" a govuk-button--secondry
n/a
> Current assignment button styles

- app/models/application_history_event.rb
- config/locales/en.yml
- spec/system/viewing_application_history_spec.rb
Update application history event description to use the name of the person whom the application was assigned to or from rather than self.
[CRIMRE-69](https://dsdmoj.atlassian.net/browse/CRIMRE-69)
This reverts a change I'd made the wording of assigning event descriptions when the indirect object of the sentence was the subject.
> CRIMRE-69 use indirect object name and not self

- app/models/application_search.rb
- app/models/crime_application.rb
- spec/system/search_applications/filter_by_date_of_birth_spec.rb
Filter by applicants date of birth.
[CRIMRE-82](https://dsdmoj.atlassian.net/browse/CRIMRE-82)
Building on https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/49
Adds filtering applicant date of birth.
> CRIMRE-82 search by applicants dob

- app/models/application_search.rb
- app/models/application_search_filter.rb
- app/models/current_assignment.rb
- spec/system/search_applications/filter_by_caseworker_spec.rb
Adds the filter to allow users to filter by all those cases that are assigned.
[CRIMRE-104](https://dsdmoj.atlassian.net/browse/CRIMRE-104)
- On the 'app open applications' page search for 'All assigned' and check whether the results make sense.
> Adds "All assigned" filter

- config/locales/en.yml
- spec/system/applications_dashboard_spec.rb
Changes default date to be in DD/MM/YYYY format in the app to reflect the format on MAAT.
[CRIMRE-37](https://dsdmoj.atlassian.net/browse/CRIMRE-37)
> Change default date to match MAAT's format

- app/views/crime_applications/_codefendants.html.erb
Conflict tag already present - this PR just right aligns it to match the designs in the ticket.
[CRIMRE-77](https://dsdmoj.atlassian.net/browse/CRIMRE-77)
> Align text right to match design

- .rubocop.yml
- app/controllers/assigned_applications_controller.rb
- config/locales/en.yml
- spec/system/get_next_application_spec.rb
Add conditional around get next feature dependent on there being an available unassigned application for a casework to assign to themselves
I have made decisions unilaterally whilst awaiting response from product and design - redirecting user to their list, and showing flash message: `There are no unassigned applications to that need processing at this time, please try again later`
Ensure there are no unassigned applications, navigate to your list page, click get next.
> Account for situation where there is no next application to get

- app/assets/stylesheets/local/custom.scss
- app/views/application/_application_search_filter.html.erb
- config/locales/en.yml
- spec/system/search_applications/no_search_results_spec.rb
Small PR to change search copy to match designs - removes heading from the search and addes some grey help text in place
[CRIMRE-108](https://dsdmoj.atlassian.net/browse/CRIMRE-108)
- go to search page - check it against the designs
> Change copy on search to match designs

- config/routes.rb
Adds rails event store browser to app when running in development mode.
Browser is mounted at `/event_browser`
n/a
is this useful, id like your thoughts? I think it will be helpful for debugging
Load app in dev mode
Go to `/event_browser` -> click on an event to see details of it
> Add event browser for development

- app/controllers/application_searches_controller.rb
- app/models/application_search_csv.rb
- app/models/application_search_filter.rb
- app/models/application_search_result.rb
- app/views/application/_application_search_filter.html.erb
- app/views/application_searches/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/fixtures/files/application_search.csv
- spec/system/search_applications/download_search_results_spec.rb
Download search results as csv
Co-authored-by: "willmcb"<william.mcbrien@digital.justice.gov.uk>
Adds basic CSV download for application searches.
[CRIMRE-50](https://dsdmoj.atlassian.net/browse/CRIMRE-50)
Very basic for demonstration purposes.
Unlike the design, we have used a button for the download action.  We felt that downloading should probably not be a link/GET request because were likely to want to:
- restrict downloading to specific roles,
- log downloading events, and
- generally discourage what could be quite a costly requests
[CRIMRE-50]: https://dsdmoj.atlassian.net/browse/CRIMRE-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMRE-50]: https://dsdmoj.atlassian.net/browse/CRIMRE-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> Add csv download link

- app/models/application_search_csv.rb
- spec/system/search_applications/download_search_results_spec.rb
Adds ".csv" to the download filename.
[CRIMRE-50](https://dsdmoj.atlassian.net/browse/CRIMRE-50)
Add the file extension to the filename, which also sets the response content-type etc.
[CRIMRE-50]: https://dsdmoj.atlassian.net/browse/CRIMRE-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add extension to download file name

- .env.development
- app/lib/types.rb
- app/models/application_search_filter.rb
- app/models/crime_application.rb
- app/views/application/_application_search_filter.html.erb
- config/environments/development.rb
- config/locales/en.yml
- spec/models/application_search_filter_spec.rb
- spec/system/search_applications/filter_by_status_spec.rb
Co-authored-by: Arthur Ashman <arthur.ashman@digital.justice.gov.uk>
Adds filter by review status to search.
[CRIMRE-106](https://dsdmoj.atlassian.net/browse/CRIMRE-106)
Review statuses are different to apply and datastore. The mapping of review status to datastore status take place in the Types.
Also uses types from LaaCrimeSchemas (these were previously duplicated).
[Datastore PR](https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/16)
[CRIMRE-106]: https://dsdmoj.atlassian.net/browse/CRIMRE-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-106 filter by review status

- .rubocop.yml
- app/aggregates/reviewing.rb
- app/aggregates/reviewing/command.rb
- app/aggregates/reviewing/commands/complete.rb
- app/aggregates/reviewing/commands/receive_application.rb
- app/aggregates/reviewing/commands/send_back.rb
- app/aggregates/reviewing/errors.rb
- app/aggregates/reviewing/event.rb
- app/aggregates/reviewing/events/application_recieved.rb
- app/aggregates/reviewing/events/completed.rb
- app/aggregates/reviewing/events/sent_back.rb
- app/aggregates/reviewing/review.rb
- app/lib/types.rb
- config/initializers/aggregates.rb
- spec/aggregates/reviewing/complete_spec.rb
- spec/aggregates/reviewing/receive_application_spec.rb
- spec/aggregates/reviewing/review_spec.rb
- spec/aggregates/reviewing/send_back_spec.rb
- spec/shared_contexts/with_review.rb
- spec/system/reassign_an_application_confirmation_spec.rb
- spec/system/reassign_an_application_to_myself_spec.rb
- spec/system/sub_nav_spec.rb
Adds Review aggregates and reviewing commands and events.
adds the Reviewing::Review aggregate root (event sourced).
adds the following commands:
Reviewing::ReceiveApplication
Reviewing::SendBack
Reviewing::Complete
adds the following events:
Reviewing::ApplicationReceived
Reviewing::SentBack
Reviewing::Completed
adds a new type, Types::ReturnReason
[CRIMRE-84](https://dsdmoj.atlassian.net/browse/CRIMRE-84)
In order to build the time passed reports (and many other things), Review needs a temporal understanding of changes in an applications review status.
[CRIMRE-84]: https://dsdmoj.atlassian.net/browse/CRIMRE-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add reviewing aggregate, commands and events

- Gemfile.lock
- app/aggregates/reviewing.rb
Revert update to mail gem to a version that work on CP.
> Mail 2.8.0 has issues. Revert update.

- app/models/user.rb
- config/locales/en.yml
- spec/models/user_spec.rb
Return "Anonymous" for names when showing application history for users that have been forgotten.
[CRIMRE-124](https://dsdmoj.atlassian.net/browse/CRIMRE-124)
Arguably part of later GDPR forgetting features. However this was causing an issue on staging where we had applications assigned to deleted users.
[CRIMRE-124]: https://dsdmoj.atlassian.net/browse/CRIMRE-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-124 Handle anonymous caseworkers

- app/controllers/assigned_applications_controller.rb
- app/models/application_search_result.rb
- spec/init/api_data.rb
- spec/shared_contexts/when_search_results_are_returned.rb
- spec/shared_contexts/when_search_results_empty.rb
- spec/shared_contexts/with_stubbed_search.rb
- spec/system/search_applications/download_search_results_spec.rb
- spec/system/search_applications/filter_by_caseworker_spec.rb
- spec/system/search_applications/filter_by_date_range_spec.rb
- spec/system/search_applications/filter_by_status_spec.rb
- spec/system/search_applications/no_search_results_spec.rb
- spec/system/search_applications/search_filters_and_results_spec.rb
- spec/system/unassign_an_application_from_myself_spec.rb
- spec/system/viewing_your_assigned_applications_spec.rb
Your list only shows assignments if they exist in the data store.
Prior to this change, if an application was removed from the datastore whilst still assigned to a user, that user would not be able to load the "Your list" page.
[CRIMRE-127](https://dsdmoj.atlassian.net/browse/CRIMRE-127)
This is a minimal solution to unblock staging should this happen again. The wider process for handing this scenario has not been determined.
This solution can result in a mismatch between the assignment counts and the number of records shown in the table. However, we do not want to delete the Assignment from review (which would correct the mismatch) because we cannot be sure that the record not being found in the datastore is intentional or just a temporary issue as a result of a bug.
[CRIMRE-127]: …
> Crimre 127 handle applications deleted from datastore

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/sorting.scss
- app/views/application_searches/_search_results_table.html.erb
- spec/system/open_applications_dashboard_spec.rb
- spec/system/searching/search_filters_and_results_spec.rb
Applies styles to first two columns in "search" table
A small PR to start using the styles for the sortable columns on the search page.
Future PRs will incude actual functional rather than just style code.:w
[CRIMRE-141](https://dsdmoj.atlassian.net/browse/CRIMRE-141)
[CRIMRE-141]: https://dsdmoj.atlassian.net/browse/CRIMRE-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add sorting to app

- Gemfile.lock
- app/aggregates/reviewing/commands/send_back.rb
- app/lib/types.rb
- app/models/application_history.rb
- app/models/application_history_item.rb
- app/models/application_search_result.rb
- app/views/application_history_items/_assigning_assigned_to_user.html.erb
- app/views/application_history_items/_assigning_reassigned_to_user.html.erb
- app/views/application_history_items/_assigning_unassigned_from_user.html.erb
- app/views/application_history_items/_reviewing_application_received.html.erb
- app/views/application_history_items/_reviewing_sent_back.html.erb
- app/views/crime_applications/_closed_crime_applications_table_body.html.erb
- app/views/crime_applications/_history_item.html.erb
- app/views/crime_applications/history.html.erb
- config/locales/en.yml
- spec/aggregates/reviewing/send_back_spec.rb
- spec/init/api_data.rb
- spec/system/closed_applications_dashboard_spec.rb
- spec/system/reviewing/send_back_to_provider_spec.rb
- spec/system/viewing_application_history_spec.rb
Adds return events to application history.
User reviewed at date from datastore.
Completes CRIMRE-52
> CRIMRE-52 show return in application history

- app/views/application_searches/_search_results_table_body.html.erb
- config/locales/en.yml
- spec/system/open_applications_dashboard_spec.rb
- spec/system/searching/search_filters_and_results_spec.rb
also fixes search results page with returned applications.
[CRIMRE-123](https://dsdmoj.atlassian.net/browse/CRIMRE-123)
[CRIMRE-123]: https://dsdmoj.atlassian.net/browse/CRIMRE-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-123-time-past-days-past

- app/controllers/application_controller.rb
- app/controllers/application_searches_controller.rb
- app/controllers/assigned_applications_controller.rb
- app/controllers/crime_applications_controller.rb
- app/helpers/application_helper.rb
- app/lib/application_struct.rb
- app/models/pagination.rb
- app/models/table_header.rb
- app/views/application_searches/show.html.erb
- app/views/assigned_applications/index.html.erb
- app/views/crime_applications/_closed_crime_applications_table_headers.html.erb
- app/views/crime_applications/_open_crime_applications_table_headers.html.erb
- app/views/crime_applications/index.html.erb
- spec/models/application_search_filter_spec.rb
- spec/models/pagination_spec.rb
- spec/shared_contexts/with_stubbed_search.rb
Allows per_page to be set in the query string of any paginated page for testing and development purposes.
for example, visit:
```
/applications/open?per_page=1
```
> Crimre 87 set per page in views

- app/controllers/application_controller.rb
- app/controllers/crime_applications_controller.rb
- app/lib/types.rb
- app/views/crime_applications/index.html.erb
- spec/system/assigning/viewing_your_assigned_applications_spec.rb
- spec/system/open_applications_dashboard_spec.rb
- spec/system/searching/sorting_search_results_spec.rb
Open applications, your list, and search show oldest at the top initially. 
Closed applications show most recently reviewed at the top initially.
[CRIMRE-45](https://dsdmoj.atlassian.net/browse/CRIMRE-45)
> CRIMRE-45 fix default sort order

- app/lib/types.rb
- app/models/application_search.rb
- app/views/crime_applications/show.html.erb
- config/locales/en.yml
- spec/models/application_search_filter_spec.rb
- spec/shared_contexts/with_stubbed_search.rb
- spec/system/searching/filter_by_status_spec.rb
Treat "superseded" applications like "send_back".
Show no results when completed filter is selected.
https://dsdmoj.atlassian.net/browse/CRIMRE-158
When a sent back application is resubmitted by a provider the original application is marked as superseded in the datastore. 
Currently (and incorrectly) review shows these applications as “superseded” and does not return them in search results when filtering with status “Sent back to provider”.
Requirements for Review: 
Superseded applications show their status as “Sent back to provider”.
Superseded applications are included in results when searching with status filter “Sent back to the provider”.
> CRIMRE-158-superseded-as-sent-back

- app/views/crime_applications/index.html.erb
Carol mentioned that the count is at the top of the mini report and not bold in the the design
n/a
> Move count above mini reports and reduce padding

- Dockerfile
On asset:precompile, turbo attempts to create a signed_stream_verifier_key using Rails.application.key_generator. This fix creates a dummy SECRET_KEY_BASE to be used in the build process.
> FIX build error on asset precompile

- .env.development
- .env.test
- Gemfile
- Gemfile.lock
- config/initializers/datastore_client.rb
- config/initializers/simple_jwt_auth.rb
- config/kubernetes/staging/deployment.tpl
Merging this will not enable JWT or change any functionality on Review, as it is not enabled yet (to enable, change `config.auth_type = :jwt`).
Once enabled, the datastore API client will make use of a little middleware introduced in the `simple-jwt-auth` gem to generate and send a JWT bearer token.
https://dsdmoj.atlassian.net/browse/CRIMAP-273
If wanted to test locally, a corresponding PR has been raised in the datastore repo, in order to have an end to end, locally-testable demo.
> Prepare Review to use datastore JWT auth

- app/models/application_history.rb
- app/models/reporting/processed_report.rb
- spec/models/reporting/processed_report_spec.rb
Refactor processed reports to use event data.
[CRIMRE-166](https://dsdmoj.atlassian.net/browse/CRIMRE-166)
Refactor to use review event data instead of datastore data for these counts. A similar refactor can be done on the workload report when we start recording ApplicationReceived events.
[CRIMRE-166]: https://dsdmoj.atlassian.net/browse/CRIMRE-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crimre 166 use event stream for processed report

- .env.test
- Gemfile
- Gemfile.lock
- config/initializers/datastore_client.rb
The `moj-simple-jwt-auth` gem is now included in the `datastore-api-client` gem, so we don't have to add it explicitly to the Gemfile.
**NOTE: this PR once merged will enable JWT authentication against the Datastore. Corresponding PRs will be raised in Review and in the Datastore.
Keeping all in place for a quick revert to http basic auth if needed.**
https://dsdmoj.atlassian.net/browse/CRIMAP-277
> Bump datastore api client gem and enable JWT auth

- .env.development
With openssl >= 3.0.0 you need to have something in those secrets. Nil or empty string will produce an error.
With openssl < 3.0.0 a nil value will blow up but funnily enough not an empty string.
To avoid confusion and edge cases with the openssl version installed in each system, we set a default dummy value, so developers don't need to set their own in their `.local` files.
> Set a more sensible default for ENV variable

- app/models/application_search_result.rb
- app/models/crime_application.rb
- app/views/application/_crime_application.html.erb
- app/views/application_searches/_search_results_table_body.html.erb
- app/views/application_searches/show.html.erb
- app/views/assigned_applications/_application_table.html.erb
- app/views/assigned_applications/index.html.erb
- app/views/crime_applications/_open_crime_applications_table_body.html.erb
- app/views/crime_applications/_open_crime_applications_table_headers.html.erb
- app/views/crime_applications/_overview.html.erb
- config/locales/en.yml
- spec/system/open_applications_dashboard_spec.rb
- spec/system/searching/search_filters_and_results_spec.rb
Removes references / columns to whether cases are or are not on common platform as discussed.
- run the app and make sure everything looks okay
> Remove 'common platform' placeholder code

- app/aggregates/reviewing/commands/complete.rb
- app/controllers/crime_applications_controller.rb
- app/views/crime_applications/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/aggregates/reviewing/complete_spec.rb
- spec/system/reviewing/mark_application_as_complete_spec.rb
- spec/system/reviewing/send_back_to_provider_spec.rb
Mark as complete triggers a call to the datastore to update the application status
User is redirected to Your list if successful with a success flash message shown
User is left on current page if unsuccessful with an unsuccessful flash message shown
https://dsdmoj.atlassian.net/browse/CRIMRE-149
> CRIMRE-149 Mark application as complete

- Gemfile.lock
- app/controllers/crime_applications_controller.rb
- app/lib/types.rb
- app/models/application_search_filter.rb
- app/models/reporting/workload_report.rb
- config/locales/en.yml
- spec/models/application_search_filter_spec.rb
- spec/system/searching/filter_by_status_spec.rb
Show completed applications on the closed tab.
Include completed in the status search filter.
Use review_status instead of status for datastore queries.
[CRIMRE-151](https://dsdmoj.atlassian.net/browse/CRIMRE-151)
[CRIMRE-151]: https://dsdmoj.atlassian.net/browse/CRIMRE-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-151 Show completed on the closed tab.

- app/aggregates/reviewing/commands/receive_application.rb
- app/aggregates/reviewing/review.rb
- app/controllers/api/events_controller.rb
- config/routes.rb
- spec/requests/api/events_spec.rb
Add a test endpoint for 'apply.submission' events from SNS.
[CRIMRE-177](https://dsdmoj.atlassian.net/browse/CRIMRE-177)
Very, very spikey. Experiment to see what, if any, messages we get when we add an endpoint to an SNS.
[CRIMRE-177]: https://dsdmoj.atlassian.net/browse/CRIMRE-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-177 Spike sns callback for submission events

- app/controllers/assigned_applications_controller.rb
- app/views/assigned_applications/index.html.erb
- spec/system/assigning/viewing_your_assigned_applications_spec.rb
- spec/system/closed_applications_dashboard_spec.rb
- spec/system/searching/filter_by_status_spec.rb
Fixes a bug which caused all open applications to be listed on 'Your list' if the user didn't have any assignments.
https://github.com/ministryofjustice/laa-review-criminal-legal-aid/issues/131
> Show an empty list when user does not have assignments

- app/controllers/api/events_controller.rb
- spec/requests/api/events_spec.rb
Handle all potential SNS message formats.
SNS currently uses raw message format which results in the callback body being the crime application json.
This  pr adds support for this, as well as the aws default for standard message format.
It also adds support for the proposed message format which uses raw format but as an object as follows:
```ruby
{event_name: "apply.submission", data: {id: application_id, ....}}
```
> CRIMRE-177-handle-all-potential-message-format

- app/aggregates/reviewing/commands/load_review.rb
- app/aggregates/reviewing/errors.rb
- app/aggregates/reviewing/review.rb
- app/controllers/api/events_controller.rb
- app/models/application_history.rb
- app/models/application_history_item.rb
- app/models/crime_application.rb
- spec/aggregates/reviewing/receive_application_spec.rb
- spec/aggregates/reviewing/send_back_spec.rb
- spec/models/crime_application_spec.rb
- spec/requests/api/events_spec.rb
- spec/shared_contexts/with_review.rb
- spec/system/closed_applications_dashboard_spec.rb
Show application_received events in history.
[CRIMRE-180](https://dsdmoj.atlassian.net/browse/CRIMRE-180)
These were previously fake events. 
In production environments, review will be notified via SNS that an application has been submitted. 
This notification service can be replicated in development (see datastore readme). However, to support contexts where an SNS service is not configured, review will create an application_received event when an application is first accessed by a user on review. 
The timestamp shown on the history for application_received events is the application's submittted_at and not the event's timestamp.
[CRIMRE-180]: https://dsdmoj.atlassian.net/browse/CRIMRE-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show application_received events in history

- app/models/crime_application.rb
- app/views/application_history_items/_reviewing_application_received.html.erb
- app/views/crime_applications/history.html.erb
- spec/fixtures/files/crime_apply_data/applications/148df27d-4710-4c5b-938c-bb132eb040ca.json
- spec/init/api_data.rb
- spec/models/crime_application_spec.rb
- spec/models/reporting/processed_report_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
- spec/system/viewing_an_application/history_when_a_resubmission_spec.rb
Recursively iterate through parent ids to collate all application history items
Built history for all items
Link to previous superseded versions via respective history application received items
https://dsdmoj.atlassian.net/browse/CRIMRE-153
Submit from apply
Assign to self, and return in review
Resubmit from apply
View application and application history
> Crimre 153 resubmission history

- app/controllers/application_controller.rb
- app/models/user.rb
- db/migrate/20230301132756_add_last_auth_at_to_users.rb
- db/schema.rb
- lib/warden/strategies/azure_ad.rb
- spec/models/user_spec.rb
- spec/requests/azure_ad_logout_spec.rb
- spec/shared_contexts/logged_in_user.rb
Only authenticate users if they exist in the review database. 
Active users are authenticated if they are found by auth_oid.
Users pending activation are authenticated if they are found by email address.
Pending activation users are activated on authentication.
Once activated a user cannot be found by email address (in the context of authentication).
[CRIMRE-193](https://dsdmoj.atlassian.net/browse/CRIMRE-193)
Be good to find out what sort of logging/monitoring is expected around authentication. I'd like to move User.authenticate! into a service or an authentication aggregate.
[CRIMRE-193]: https://dsdmoj.atlassian.net/browse/CRIMRE-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-193 only auth extant users

- app/controllers/application_controller.rb
- app/views/layouts/_header_navigation.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/govuk_template.html.erb
- config/locales/en.yml
- spec/system/header_nav_spec.rb
Add header nav for switching between application views and user management views
Manage user nav link needs linking up to actual controller/view
https://dsdmoj.atlassian.net/browse/CRIMRE-195
> Add header nav for application/user management navigation

- app/controllers/admin/manage_users_controller.rb
- app/controllers/application_controller.rb
- app/views/admin/manage_users/index.html.erb
- app/views/layouts/_header_navigation.html.erb
- config/locales/en.yml
- spec/system/header_nav_spec.rb
- spec/system/manage_users/viewing_spec.rb
- Add conditionality to manage_users_controller to only allow users that can manage users to the dashboard - redirect to Your list and flash message
- Add can_manage_others attribute to Manage users table
- Conditionally hide Manage users link in header nav to those allowed to access
https://dsdmoj.atlassian.net/browse/CRIMRE-199
Check the link is not present, and that accessing` /admin/manage_users` directly redirects and flashes message
Then to be able to see the link, and access manage users:
- `rails c`
- `User.first.update(can_manage_others: true)`
> Restrict users to see nav option and access user admin only if allowed

- db/migrate/20230307122915_make_users_email_case_insensitive.rb
- db/schema.rb
- spec/models/user_spec.rb
User email are case insensitive when queried
User email has a case insensitive uniqueness constraint
User auth_subject_id has a uniqueness constraint
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMRE/boards/960?selectedIssue=CRIMRE-200
The auth provider sends emails with uppercase characters. Users tend to provide emails in lowercase.  
Also, users are uniq by email, this uniqueness MUST ignore case.
> CRIMRE-200 make email case insensitive

- app/views/admin/manage_users/new.html.erb
- config/locales/en.yml
- spec/system/manage_users/add_user_spec.rb
Tiny PR to add cancel button to add users page + spec (forgot to add in previous PR)
Cancel link added:
> Add cancel button

- app/controllers/admin/deactivate_users_controller.rb
- app/models/user.rb
- app/views/admin/deactivate_users/new.html.erb
- app/views/admin/manage_users/edit.html.erb
- app/views/admin/manage_users/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/shared_contexts/with_a_logged_in_admin_user.rb
- spec/shared_contexts/with_a_logged_in_user.rb
- spec/system/manage_users/deactivate_a_user_spec.rb
- spec/system/manage_users/edit_user_spec.rb
- spec/system/manage_users/viewing_spec.rb
Admin can deactivate a user.
[CRIMRE-196](https://dsdmoj.atlassian.net/browse/CRIMRE-196)
Deactivated users cannot access the service but remain in the database (so are seen in history etc).
[CRIMRE-196]: https://dsdmoj.atlassian.net/browse/CRIMRE-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-196 admin can deactivate a user.

- app/forms/admin/new_user_form.rb
- config/locales/en/errors.yml
- spec/forms/admin/new_user_form_spec.rb
- spec/spec_helper.rb
- spec/system/manage_users/add_user_spec.rb
Follow up of [PR 155](https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/155). Handles the error state when an admin tries to add a user that already exists on the system.
Also adds a convenience method that pretty prints `page.html` as a readable html document rather than a long string which is hard to parse.
- try to add a user that already exists - you should see the error message as show in the screenshot.
> Crimre 180 new users have to be unique

- .env.development
- .env.test
- config/initializers/devise.rb
- config/kubernetes/staging/config_map.yml
- config/routes.rb
Specify azure_ad return_uri
Having to specify the return_uri adds a configuration burden. 
It seemed not to be necessary when using Devise, however the host url does not seem to be being set consistently.
This change reverts to specifying the return_uri per deployment, and in doing so should hopefully fix authentication on staging.
> Specify redirect_uri for azure_ad

- app/aggregates/reviewing/commands/mark_as_ready.rb
- config/locales/en.yml
- spec/system/reviewing/mark_application_as_complete_spec.rb
- spec/system/reviewing/mark_application_as_ready_spec.rb
- spec/system/reviewing/send_back_to_provider_spec.rb
- spec/system/viewing_an_application/that_is_assigned_to_me_spec.rb
- spec/system/viewing_an_application/that_is_assigned_to_somone_else_spec.rb
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
- Makes a request to update the status of an application to ready for assessment in the datastore when an application has been marked as ready for assessment in the client
- Also changes colour of ready for assessment tag to blue from default blue
[CRIMRE-248](https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMRE/boards/960?modal=detail&selectedIssue=CRIMRE-248)
[CRIMRE-248]: https://dsdmoj.atlassian.net/browse/CRIMRE-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-248 update ready for assessment status in datastore

- app/models/reporting/workload_report.rb
- config/locales/en.yml
- spec/models/reporting/workload_report_spec.rb
- spec/system/assigning/get_next_application_spec.rb
- spec/system/reporting/workload_report_spec.rb
- add latest column headers
- remove closed applications total
- add applications received total
- only show the counts up to the last nine days in the final row
[CRIMRE-214](https://dsdmoj.atlassian.net/browse/CRIMRE-214)
[CRIMRE-214]: https://dsdmoj.atlassian.net/browse/CRIMRE-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-214 workload report content update

- app/views/crime_applications/_client_details.html.erb
- app/views/crime_applications/_interests_of_justice.html.erb
- app/views/crime_applications/_overview.html.erb
- app/views/crime_applications/show.html.erb
- config/locales/en.yml
- spec/fixtures/files/crime_apply_data/applications/148df27d-4710-4c5b-938c-bb132eb040ca.json
- spec/fixtures/files/crime_apply_data/applications/1aa4c689-6fb5-47ff-9567-5eee7f8ac2cc.json
- spec/fixtures/files/crime_apply_data/applications/5aa4c689-6fb5-47ff-9567-5efe7f8ac211.json
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
Add conditional to interest of justice section to list IOJ passport types with passported badge instead of IOJ reason type and justification 
Update show application view to present 'Not provided' for optional fields that were not input on Apply - to make explicit to caseworker that these were not sent. 
Update fixture and test to ensure that this reflects the return values when input not provided (i.e. "" not null) - to prevent evergreen test. 
https://dsdmoj.atlassian.net/browse/CRIMRE-38
We only know the value for under 18 passport, this will need updating for when we have bypassed on offence
> Add ioj passport, update show application view and fixtures

- config/locales/en.yml
- spec/system/assigning/viewing_your_assigned_applications_spec.rb
Update copy for number of applications assigned on the your list page. 
https://dsdmoj.atlassian.net/browse/CRIMRE-272
> Update copy for number assigned

- .env.development
- .env.test
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/users/dev_auth_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/lib/feature_flags.rb
- app/lib/omni_auth/strategies/dev_auth.rb
- app/views/users/dev_auth/new.html.erb
- app/views/users/sessions/new.html.erb
- config/initializers/devise.rb
- config/routes.rb
- config/settings.yml
- db/seeds.rb
- spec/rails_helper.rb
- spec/requests/authentication_spec.rb
- spec/system/authenticating/dev_auth_spec.rb
- creates a custom DevAuth Omniauth strategy
- use DevAuth by default in development/test
- add an admin  user to db seed
[CRIMRE-232](https://dsdmoj.atlassian.net/browse/CRIMRE-232)
Removes the need for AzureAd in development. 
Allows a developer to authenticate with any user in their database.
To use AzureAD in development set  DEV_AUTH_ENABLED=false
Includes a NonAuth'd user so developers can attempt to sign in with a non-authorised but authenticated user.
I've attempted to do this with minimal changes to the authentication code.
[CRIMRE-232]: https://dsdmoj.atlassian.net/browse/CRIMRE-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-232 use custom OmniAuth strategy when local

- app/views/crime_applications/_assignment.html.erb
- config/locales/en.yml
- spec/system/assigning/assign_an_application_to_myself_spec.rb
- spec/system/assigning/reassign_an_application_confirmation_errors_spec.rb
- spec/system/assigning/reassign_an_application_to_myself_spec.rb
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
Update value of Assigned to: label when no one is assigned - from "Unassigned" to "no one"
https://dsdmoj.atlassian.net/browse/CRIMRE-265
> Update value of Assigned to: label when no one is assigned

- app/views/crime_applications/_review_overview.html.erb
Moves the status above the reference number as per the designs
[CRIMRE-291](https://dsdmoj.atlassian.net/browse/CRIMRE-291)
- open application show page
- status should be above the reference number
- also check that the spacing looks right to you against the designs.
[CRIMRE-291]: https://dsdmoj.atlassian.net/browse/CRIMRE-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move status above reference

- spec/lib/omni_auth/strategies/dev_auth_spec.rb
Confirm OmniAuth configuration 
It is possible to change the configuration used by the OpenID Connect strategy in a way that still functions but undermines security.
This change adds a spec to make sure such changes are not made without full consideration.
> Spec OmniAuth strategy configuration

- Gemfile
- Gemfile.lock
- spec/models/crime_application_spec.rb
Update to use latest schema gem.
FIXES: https://ministryofjustice.sentry.io/issues/4105872851/events/802e273436184fe9b9283e04be1e8756/
> REVIEW-CRIMINAL-LEGAL-AID-4 Update Schema Gem

- app/models/reporting/table.rb
- app/models/reporting/workload_report.rb
- app/views/application/_table_header.html.erb
- config/locales/en.yml
- spec/models/reporting/workload_report_spec.rb
- spec/system/assigning/viewing_your_assigned_applications_spec.rb
- spec/system/closed_applications_dashboard_spec.rb
- spec/system/open_applications_dashboard_spec.rb
- spec/system/reporting/workload_report_spec.rb
- spec/system/searching/search_filters_and_results_spec.rb
https://dsdmoj.atlassian.net/browse/CRIMRE-267
- User logs into portal
- User go to the All open applications page
- User should see that the following headers in the table above screenshot have been updated
- Changed ‘Applicant’ to ‘Applicant’s name'
- Changed ‘Ref. no.’ to ‘Reference number’
- Changed ‘Days passed’ to ‘Business days since application was received’
> CRIMRE-267-Updated headers in the application table for all open applications

- app/views/crime_applications/index.html.erb
- config/locales/en.yml
- spec/system/closed_applications_dashboard_spec.rb
- spec/system/open_applications_dashboard_spec.rb
https://dsdmoj.atlassian.net/browse/CRIMRE-268
https://dsdmoj.atlassian.net/browse/CRIMRE-269
- User logs into portal
- User clicks on either 'All open applications' or 'Closed applications'
- User should see underneath either heading on the page 'All open applications' or 'Closed applications' the following text         "There are [number] open applications that need to be reviewed" or "There are [number] closed applications that have been completed or sent back to the provider."
> CRIMRE-269-Updated the wording for open and closed application totals

- app/views/crime_applications/_offences.html.erb
- config/locales/en.yml
Update date range formatting from "10/10/2022 - 11/10/2022" to "10/10/2022 to 11/10/2022"
https://dsdmoj.atlassian.net/browse/CRIMRE-274
Got agreement from Liv that the date wrapping over 2 lines is ok
> Update date range formatting

- config/kubernetes/staging/config_map.yml
We are evaluating internal cross-namespace networking between Apply/Review and Datastore.
For the time being and until we decide so, external ingress will still be available.
https://dsdmoj.atlassian.net/browse/CRIMAP-328
In theory everything should continue working as before, just slightly less latency when loading lists or paginating (thus difficult to evaluate as we don't have that many records yet).
> CRIMAP-328 Switch datastore URL to internal svc

- app/controllers/crime_applications_controller.rb
- config/locales/en.yml
- spec/system/reviewing/mark_application_as_ready_spec.rb
- spec/system/viewing_an_application/that_is_assigned_to_me_spec.rb
- spec/system/viewing_an_application/that_is_assigned_to_somone_else_spec.rb
Marking as ready should reload current page, not redirect to Your list
Change Mark as Ready cta to Mark as ready for MAAT as per designs
https://dsdmoj.atlassian.net/browse/CRIMRE-296
> Correct mark as ready cta and routing

- .github/actions/deploy/action.yml
- .github/workflows/test-build-deploy.yml
Updated some outdated action versions.
DRY github workflow to allow for reusable deploy action with parameterised inputs.
Do not merge until the k8s manifests in PR #235 are merged first.
https://dsdmoj.atlassian.net/browse/CRIMRE-279
> CRIMRE-279 Update github CI/CD workflow

- app/aggregates/reviewing/commands/receive_application.rb
- app/aggregates/reviewing/review.rb
- app/controllers/api/events_controller.rb
- app/models/application_search_result.rb
- app/models/concerns/reviewable.rb
- app/models/crime_application.rb
- spec/aggregates/reviewing/receive_application_spec.rb
- spec/requests/api/events_spec.rb
- spec/shared_contexts/with_stubbed_search.rb
- spec/system/assigning/get_next_application_spec.rb
- spec/system/assigning/viewing_your_assigned_applications_spec.rb
- spec/system/closed_applications_dashboard_spec.rb
- spec/system/viewing_an_application/history_when_a_resubmission_spec.rb
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
Store the parent_id when an application is received via SNS, search_result, or application find.
https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/87
Latest designs require us to be able to link to the latest version of an application. 
This builds on https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/87 to import the parent_id to store the parent_id when an application is received.
> CRIMRE-306 Store the parent id on application recieve

- README.md
- config/kubernetes/staging/ingress.yml
This is a subdomain of our production domain.
Internal cloud platform URLs are still available and functional, but this is now an easier to remember domain.
Azure config might require changes to work with this subdomain.
https://dsdmoj.atlassian.net/browse/CRIMAP-172
> CRIMAP-172 Add staging subdomain to ingress

- app/models/review.rb
- app/read_models/reviews/configuration.rb
- app/read_models/reviews/update_from_aggregate.rb
- config/initializers/event_store.rb
- db/migrate/20230425145156_create_reviews.rb
- db/schema.rb
- spec/models/review_spec.rb
- spec/read_models/reviews/update_from_aggreate_spec.rb
Create Review read model.
https://dsdmoj.atlassian.net/browse/CRIMRE-306
The Review read model is being introduced to facilitate two new querying requirements on Crime Review:
- Produce a list of all applications reviewed by a given caseworker [CRIMRE-302](https://dsdmoj.atlassian.net/browse/CRIMRE-302)
- Establish the latest version of a given application [CRIMRE-293](https://dsdmoj.atlassian.net/browse/CRIMRE-293)
The Review read model will be a standalone read model for the Review aggregate. Whenever a Review READ_MODEL_CHANGING_EVENT occurs, the corresponding handler will load the Review aggregate from the event stream and store the necessary attributes into the read model.
[CRIMRE-302]: https://dsdmoj.atlassian.net/browse/CRIMRE-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
> CRIMRE-306 create review read model

- app/aggregates/reviewing/commands/receive_application.rb
- app/aggregates/reviewing/commands/supersede.rb
- app/aggregates/reviewing/events/superseded.rb
- app/aggregates/reviewing/review.rb
- app/models/application_history.rb
- app/models/crime_application.rb
- app/views/application_history_items/_reviewing_application_received.html.erb
- app/views/application_history_items/_reviewing_superseded.html.erb
- app/views/crime_applications/history.html.erb
- spec/system/viewing_an_application/history_when_a_resubmission_spec.rb
Create a "Superseded" event in the event stream of an application when a new version is submitted.
Provide a link to the superseding application on the superseded application's history.
[CRIMRE-293](https://dsdmoj.atlassian.net/browse/CRIMRE-293)
The code in the CrimeApplication model is intended for temporary use during user research on the staging environment from 3-4 May. This code is not part of the final implementation and should not be used in production.
In production, the events stream will provide up-to-date events. However, as the supserseding events are not available on the staging data user for user testing, we are artificially generating the events for testing purposes only.
[CRIMRE-293]: https://dsdmoj.atlassian.net/browse/CRIMRE-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
> CRIMRE-293 Add resubmission to a superseded applications history

- config/kubernetes/production/config_map.yml
- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/config_map.yml
- config/kubernetes/staging/ingress.yml
The old cloud URLs will keep working (so we don't break bookmarks etc.) but they will redirect to the corresponding new domain/subdomain.
NOTE: Azure might require configuring this new callback. Only merge once that's done.
Follow-up to PRs #244 and #246.
> Redirect cloud urls to new domains

- app/models/user.rb
- app/models/user_authenticate.rb
- config/application.rb
- db/migrate/20230504142944_rename_users_auth_expires_at_invitation_expires_at.rb
- db/schema.rb
- spec/models/user_authenticate_spec.rb
- spec/models/user_spec.rb
- spec/requests/authentication_spec.rb
User account invitations only last 48 hours from creation.
[CRIMRE-210](https://dsdmoj.atlassian.net/browse/CRIMRE-210)
Note this PR only adds a time limit to invitations and prevents authentication if more than 48 hours have expired since the invitation was created.
How a user manager deals with expired invitations will be part of another ticket. As will the text for the invitation email.
[CRIMRE-210]: https://dsdmoj.atlassian.net/browse/CRIMRE-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-210 user invitations expire in 48 hours

- config/initializers/lograge.rb
Follow up to PR #253.
`current_user` is defined by Devise automagically. `current_user_id` is a private method in `ApplicationController` but the health controller is a `BareApplicationController` thus don't inherit this and other methods.
Fix pods going into `CrashLoopBackOff` as the probe fails to assert the readiness of the pod.
> Fix lograge payload current user method

- app/mailers/notify_mailer.rb
- spec/mailers/notify_mailer_spec.rb
- spec/system/reviewing/send_back_to_provider_spec.rb
Adds return reason to email.
[CRIMRE-316](https://dsdmoj.atlassian.net/browse/CRIMRE-316)
Notify Templates also updated to include this.
[CRIMRE-316]: https://dsdmoj.atlassian.net/browse/CRIMRE-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add return_reason to return email

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Adds modsecurity directive to Staging/Production installations, fulfils basic layer 7 security requirements
https://dsdmoj.atlassian.net/browse/CRIMRE-216 (investigation)
https://dsdmoj.atlassian.net/browse/CRIMRE-223 (implementation - this PR)
- Deliberately restricted file upload and data upload to 1MiB - is this far too small?
- Deliberately enabled OWASP rules as well as standard WAF rules - too restrictive?
N/A
Full smoke test of all functionality required.
Is there any Report Download functionality anywhere? 
Is there any File Upload functionality anywhere?
> [CRIMRE-233] Add modsecurity

- app/views/crime_applications/_offences.html.erb
- app/views/crime_applications/show.html.erb
- config/locales/en.yml
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
Added class not determined badge for unlisted (manually input) offences. 
Required some moving of govuk layout to fit 
https://dsdmoj.atlassian.net/browse/CRIMRE-99
> Add class not determined badge for unlisted offences

- app/forms/admin/new_user_form.rb
- app/mailers/notify_mailer.rb
- config/govuk_notify_templates.yml
- spec/forms/admin/new_user_form_spec.rb
- spec/mailers/notify_mailer_spec.rb
- spec/system/manage_users/add_user_spec.rb
Send an email to a user when they are granted access to the Crime Review service.
https://dsdmoj.atlassian.net/browse/CRIMRE-315
See ticket for email placeholder text used.
> CRIMRE-315 send access granted email.

- app/models/concerns/reviewable.rb
- app/models/crime_application.rb
Populate superseding history item from aggregate.
This refactor removes code to allow superseding history item to work with older data. This was required for testing as part of user testing and now no longer necessary.
> Populate superseding history item from aggregate

- app/javascript/local/copy_reference_number.js
There was a browser console error being raised on pages where the links for this function were not present. Added a check in so that the events are only attached if the links are present.
- copy ref num fuctionality should be the same
- their should be no error errors raised on the FE console when these links don't exist on the page.
> Add element check to JS copy function

- Gemfile
- Gemfile.lock
Use the latest version of the laa schema gem which standardises timestamp format and enforces types in the json schema.
[CRIMRE-333](https://dsdmoj.atlassian.net/browse/CRIMRE-333)
[CRIMRE-333]: https://dsdmoj.atlassian.net/browse/CRIMRE-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use latest version of the schema gem

- app/controllers/admin/manage_users_controller.rb
- app/controllers/application_searches_controller.rb
- app/controllers/assigned_applications_controller.rb
- app/controllers/crime_applications_controller.rb
- app/controllers/errors_controller.rb
- app/controllers/reassigns_controller.rb
- app/controllers/reports_controller.rb
- app/controllers/returns_controller.rb
- app/controllers/service_controller.rb
- app/models/concerns/auth_updateable.rb
- app/models/user.rb
- config/routes.rb
- config/settings.yml
- spec/requests/authentication_spec.rb
- spec/requests/authorisation_spec.rb
- spec/system/header_nav_spec.rb
- spec/system/manage_users/viewing_spec.rb
User managers can only access the service on staging.
On all other environments they are redirect to the manage users interface
[CRIMRE-323](https://dsdmoj.atlassian.net/browse/CRIMRE-323)
I've added the authorisation request spec which is should check all routes.
[CRIMRE-323]: https://dsdmoj.atlassian.net/browse/CRIMRE-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Only allow user managers access to service on staging

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Replica of [ PR on Apply ](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/367) to prevent 403 forbidden on modsec xss suspicion
> Skip modsec xss rule

- app/helpers/application_helper.rb
Fixes small bug of back button being on Your List page when it is redirected to on logon (as it is the auth root path, not your list path)
Small refactor based on @willmcb 's previous comments
> Remove back button from root, small refactor

- Gemfile
- Gemfile.lock
Bump schema gem from 0.2.1 to 0.3.0
> Bump schema gem from 0.2.1 to 0.3.0

- Gemfile
- Gemfile.lock
- spec/fixtures/files/crime_apply_data/applications/148df27d-4710-4c5b-938c-bb132eb040ca.json
- spec/fixtures/files/crime_apply_data/applications/1aa4c689-6fb5-47ff-9567-5eee7f8ac2cc.json
- spec/fixtures/files/crime_apply_data/applications/5aa4c689-6fb5-47ff-9567-5efe7f8ac211.json
Update to use 0.4.0 of the schema gem.
Update fixtures to work with the stricter structs.
The structs now have stricter definitions -- which are, in some cases, more strict than the json schema itself. 
This PR updates the fixtures we have on review so that they work with the latest structs/schema.
> Update fixtures for stricter structs

- config/initializers/filter_parameter_logging.rb
PR does a little rationalisation and adds some missed filters to the filter logger. Also separates the "application" domain filters from the the more technical ones (e.g. salt, passw).
I also moved these to symbols to be consistent with apply and enable comments to be added to the filter.
Analysis of what is logged across systems is linked in the comment of the ticket as a google sheet. 
[CRIMRE-227](https://dsdmoj.atlassian.net/browse/CRIMRE-227)
[CRIMRE-227]: https://dsdmoj.atlassian.net/browse/CRIMRE-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Amend logging filters, post audit

- app/assets/stylesheets/local/custom.scss
On Edge browser, the app will side scroll making it more difficult to scroll down the page. The experimental feature `elastic-overscroll` is enabled by default on edge browsers (on windows) and is responsible for this. This can be disabled by the user by navigating to `edge://flags` and manually disabling the feature. However, this cannot be disabled programatically. Therefore, side scrolling is disabled using css and the page is 'locked' to help with usability. This is will impact usability across all browsers but as the user base primarily use edge and are unlikely to use other browsers, this is not a concern.
[CRIMRE-331](https://dsdmoj.atlassian.net/browse/CRIMRE-331)
This recordings below are in chrome but this applies across all browsers …
> Disable sidescrolling to help with usability

- app/controllers/admin/manage_users/deactivated_users_controller.rb
- app/helpers/application_helper.rb
- app/views/admin/manage_users/deactivated_users/_actions.html.erb
- config/locales/en/manage_users.yml
- spec/system/manage_users/reactivate_a_user_spec.rb
Does not allow the current logged in user from reactivating themselves by:
- Hiding the 'Reactivate' link
- Showing an error message if current_user attempts to Reactivate by entering an appropriate URL into their browser
https://dsdmoj.atlassian.net/browse/CRIMRE-361
This behaviour is only applicable when current_user is deactivated by somebody else but their browser session is still open.
Introduced a new helper method `gov_link_to_unless_current_user` because `link_to_if` still outputs the link just without the anchor tag.
Not sure if premature to move the reactivation methods into a dedicated controller - perhaps overkill?
1. Log in to 2 different browsers with 2 different users, both with 'can manage others' permission set to true. 
2. Deactivate one of the users.
3. Then in the …
> [CRIMRE-361] Prevent current_user from reactivating

- app/helpers/application_helper.rb
- app/models/application_search_filter.rb
- app/models/application_search_result.rb
- app/models/business_day.rb
- app/models/reporting/processed_report.rb
- app/models/reporting/workload_report.rb
- app/views/application_searches/_search_results_table_body.html.erb
- config/application.rb
- spec/models/application_search_filter_spec.rb
- spec/system/closed_applications_dashboard_spec.rb
- spec/system/manage_users/viewing_spec.rb
- spec/system/open_applications_dashboard_spec.rb
- spec/system/searching/filter_by_date_range_spec.rb
- spec/system/viewing_an_application/history_spec.rb
Convert all timestamps to London TZ before formatting or converting to dates.
UTC is used for the application and database timezones across the crime review/apply services.
Because the timestamps we get from the datastore etc are in UTC, before formatting them, or converting to dates, they must be converted to the London TZ.
This is especially important for Review where we need to know specific day in the London time zone for MI.
> Ensure all times are TZ London before formatting

- app/models/flash_notice.rb
- app/views/application/_flash_notice.html.erb
- app/views/shared/_flash_banner.html.erb
- config/locales/en/devise.yml
- spec/models/flash_notice_spec.rb
- spec/support/gds_helper.rb
- spec/system/authenticating/a_dormant_user_spec.rb
- spec/system/authenticating/an_invited_user_spec.rb
Allow links to appear in flash messages
[CRIMRE-369](https://dsdmoj.atlassian.net/browse/CRIMRE-369)
This issue arose after the content for some devise flash messages was updated to include a mail link.  One alternative to this change might be to include the email as a text rather than a link.
[CRIMRE-369]: https://dsdmoj.atlassian.net/browse/CRIMRE-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow links in flash notifications

- config/locales/en/devise.yml
- config/locales/en/errors.yml
- spec/requests/authorisation_spec.rb
- spec/system/authenticating/a_signed_out_user_spec.rb
Now Review has a start page, the banner saying "Sign in to view this page" makes no sense given there is a page that is being displayed.
Suggestion from design to update banner to make more sense by saying "Sign in to access the service"
> Update banner wording to make sense with page

- app/views/crime_applications/_interests_of_justice.html.erb
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
If an application that when first submitted has IoJ not needed (no reason input), if it is found to be a split case on the courts systems then it may require returning and having an IoJ reason added. Crime Apply allows for this and overrides the 'IoJ not needed' attribute locally, but it remains in place in the data on resubmission, so a resubmitted application can have both an IoJ not needed flag AND an IoJ reason attribute. 
This PR reorders the conditional statements to check first if there is an IoJ reason and render that regardless of if the not needed flag is present (from the original submission) 
https://dsdmoj.atlassian.net/browse/CRIMRE-355
> Reorder if statements for logic to display ioj passport vs ioj reason

- app/models/flash_notice.rb
- app/read_models/received_on_reports/configuration.rb
- spec/models/reporting/received_on_report_spec.rb
Consider sent back as closed in workload report
[CRIMRE-385](https://dsdmoj.atlassian.net/browse/CRIMRE-385)
A typo, was causing sent back applications not be counted as closed in the workload report.
[CRIMRE-385]: https://dsdmoj.atlassian.net/browse/CRIMRE-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Consider sent back as closed in workload report

- app/views/crime_applications/_interests_of_justice.html.erb
- config/locales/en.yml
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
When ioj not needed flag is set (with no ioj reason) render a summary list under the IoJ section of application details.
Remove use of badges
When Ioj reason set, render as usual in govuk table
https://dsdmoj.atlassian.net/browse/CRIMRE-390
> Render summary list for IoJ when IoJ passported

- app/views/returns/new.html.erb
On the send back to provider page, the choose a reason error link did not link to the first radio button option when clicked. This has been amended.
[CRIMRE-386](https://dsdmoj.atlassian.net/browse/CRIMRE-386)
[CRIMRE-386]: https://dsdmoj.atlassian.net/browse/CRIMRE-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Link 'Choose a reason' error message to radio button

- app/views/crime_applications/_codefendants.html.erb
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
Co-defendant conflict conditional was not checking conflict value, just presence, so rendering of empty conflict badge for no-conflict co-defendants.
Added tests for codefendant options, to guard against this error.
https://dsdmoj.atlassian.net/browse/CRIMRE-391
> Fix conditional to stop rendering of empty conflict badge. Add tests

- .github/CODEOWNERS
- Gemfile
- Gemfile.lock
Bump the schemas gem, which contains the refactor of the appeal attributes, incorporating the new appeal_lodged_date.
NOTE: even if Review wasn't using these appeal attributes before, once Apply start submitting new applications without the old `appeal_with_changes_maat_id` attribute, if Review remains in an old version of the schemas gem, the structs will not be able to map these new applications, as that attribute was marked as "mandatory presence" and no longer is returned by the datastore.
This is the same issue we had recently with the `passportable` attribute.
https://dsdmoj.atlassian.net/browse/CRIMAP-427
Review is not showing to the case worker these appeal attributes, I think there is a separate ticket to add those to the view.
Everything should keep working with no additional …
> CRIMAP-427 Bump schemas gem (appeal_lodged_date)

- app/controllers/admin/manage_users_controller.rb
- app/controllers/application_controller.rb
- app/controllers/service_controller.rb
Redirect user managers to manage users' admin on sign in
Move service specific methods from Application to Service controller
[CRIMRE-374](https://dsdmoj.atlassian.net/browse/CRIMRE-374)
This is part of a series of changes to simplify error handling in the application. 
User managers will be shown a 404 for all service routes rather than redirecting them to admin as currently. This is being done to prevent information leakage to user managers via the redirect urls. This PR supports that change by explicitly redirecting user managers to admin on sign in rather than relying on the #require_service_user! method which will soon 404 with user managers.
[CRIMRE-374]: https://dsdmoj.atlassian.net/browse/CRIMRE-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> Redirect user managers to manage users' admin on sign in

- app/controllers/users/omniauth_callbacks_controller.rb
- config/routes.rb
- spec/requests/authentication_spec.rb
- spec/requests/authorisation_spec.rb
Render rather than redirect for Omniauth/Devise errors.
[CRIMRE-374](https://dsdmoj.atlassian.net/browse/CRIMRE-374)
This is part of a series of changes to simplify error handling in the application.
[CRIMRE-374]: https://dsdmoj.atlassian.net/browse/CRIMRE-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Render forbidden for Omniauth/Devise errors

- app/views/crime_applications/_case_details.html.erb
- config/locales/en.yml
- spec/system/viewing_an_application/that_is_open_and_unassigned_spec.rb
In appeal cases surface appeal attributes:
- lodged date
- financial change details 
- previous maat id
https://dsdmoj.atlassian.net/browse/CRIMRE-389
Put an appeal / appeal with changes case type through Apply, view Case Details section on Review
> CRIMRE-389 Surface appeal lodged date, change details and maat id in appeal cases

- config/initializers/sentry.rb
Configure Sentry as a rails error subscriber
As discovered by @zheileman, and contrary to what is stated in https://edgeguides.rubyonrails.org/error_reporting.html, Sentry requires explicit configuration in order to register as a subscriber. This can be seen in the discussion on GitHub at https://github.com/rails/rails/pull/43625#issuecomment-1072514175.
> Explicit configure of Sentry as error subscriber

- Gemfile
- Gemfile.lock
Bump schemas gem to accommodate the datastore return_details refactor.
Link to  @zheileman 's Apply ticket to which this belongs https://dsdmoj.atlassian.net/browse/CRIMAP-433
> CRIMAP-433 Bump schemas gem (return_details refactor)

- app/mailers/notify_mailer.rb
- config/govuk_notify_templates.yml
- spec/mailers/notify_mailer_spec.rb
Changes the reply to email address for access granted emails.
These have been added to notify for staging / prod - they are referenced like templates via UUID in:
`config/govuk_notify_templates.yml`
Note this only changes reply to for onboarding as the return email will use the default address - see ticket for more detail.
[CRIMRE-376](https://dsdmoj.atlassian.net/browse/CRIMRE-376)
- please double check that the UUIDs are correct to your understanding. i.e. they match the UUID for the return to for each environment.
[CRIMRE-376]: https://dsdmoj.atlassian.net/browse/CRIMRE-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Changes the reply to address for access granted emails

- config/initializers/devise.rb
- config/settings.yml
Prevent the DevAuth strategy from being configured outside the local env
[CRIMRE-402](https://dsdmoj.atlassian.net/browse/CRIMRE-402)
Adds an additional check to prevent the application being initialised with the DevAuth feature enabled in a non Local environment.
[CRIMRE-402]: https://dsdmoj.atlassian.net/browse/CRIMRE-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-402 ensure dev_auth cannot be used outside local env

- app/controllers/admin/manage_users_controller.rb
- app/controllers/application_controller.rb
- app/controllers/service_controller.rb
- app/models/application_search.rb
- app/views/errors/datastore_error.html.erb
- config/locales/en/errors.yml
- spec/init/api_data.rb
- spec/system/assigning/get_next_application_spec.rb
- spec/system/errors_spec.rb
- spec/system/searching/filter_by_status_spec.rb
Caseworkers see an error message explaining that we cannot connect to the datastore. 
The page shown contains the service navigation for a signed in user.
[CRIMRE-401](https://dsdmoj.atlassian.net/browse/CRIMRE-401)
[CRIMRE-401]: https://dsdmoj.atlassian.net/browse/CRIMRE-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-401 handle datastore errors better

- .rubocop.yml
- app/models/application_search_filter.rb
- spec/models/application_search_filter_spec.rb
- spec/shared_contexts/with_stubbed_assignments_and_reviews.rb
Only list those users that have reviews or active assignments in the search filter. Previously all users were listed.
Also fixes CRIMRE-412 as it is no longer possible to select a user that does not have reviews or current assignments.
[CRIMRE-411](https://dsdmoj.atlassian.net/browse/CRIMRE-411)
[CRIMRE-412](https://dsdmoj.atlassian.net/browse/CRIMRE-412)
[CRIMRE-411]: https://dsdmoj.atlassian.net/browse/CRIMRE-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMRE-412]: https://dsdmoj.atlassian.net/browse/CRIMRE-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-411 only show users with reviews or assignments

- app/models/reporting/workload_report.rb
- spec/models/reporting/workload_report_spec.rb
- spec/system/reporting/workload_report_spec.rb
Add a dedicated row for "3 days" in the workload report.
[CRIMRE-415](https://dsdmoj.atlassian.net/browse/CRIMRE-415)
[CRIMRE-415]: https://dsdmoj.atlassian.net/browse/CRIMRE-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-415 extend the workload report by one day

- README.md
- config/environments/production.rb
- config/initializers/devise.rb
- config/settings.yml
- docker-compose.yml
This PR fixes running docker-compose in review. The docker-compose env name has been changed to staging to enable dev_auth to be used (as dev_auth cannot be used in production) and the running of the app in ssl has been disabled
[CRIMRE-370](https://dsdmoj.atlassian.net/browse/CRIMRE-370)
Fyi I found testing in chrome to be a bit of a pain as it kept forcing ssl. I found Firefox to be easier 
[CRIMRE-370]: https://dsdmoj.atlassian.net/browse/CRIMRE-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix docker compose

- app/controllers/errors_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/views/errors/unprocessable_entity.html.erb
- config/locales/en/errors.yml
- spec/requests/authentication_spec.rb
Previously invalid authenticity token requests etc were being shown a page not found message. This change shows a request error message suggesting they go back, refresh, and try again.
Also overrides Devise passthru to redirect to sign in. Otherwise a user gets stuck on an unformatted page if they refresh the after an authenticity token failure on the user auth path.
From the root path, tamper with the authenticity token hidden field on the Start button, and click the button.
To confirm the passthru fix, reload the page and confirm you are redirected to sign_in.
> Add 422 error message

- Gemfile
- Gemfile.lock
- spec/init/webmock.rb
Removes redundant webdriver gem that was causing build issues due to webdriver not supporting chrome v115
> Remove redundant webdriver gem

- .rubocop.yml
- app/aggregates/reviewing/review.rb
- app/models/application_search.rb
- app/models/application_search_filter.rb
- app/models/business_day.rb
- app/models/concerns/reviewable.rb
- app/models/review.rb
- app/views/application/_application_search_filter.html.erb
- config/environments/test.rb
- config/locales/en.yml
- config/settings.yml
- spec/models/application_search_filter_spec.rb
- spec/read_models/reviews/update_from_aggreate_spec.rb
- spec/shared_contexts/with_stubbed_assignments_and_reviews.rb
- spec/shared_contexts/with_stubbed_search.rb
- spec/system/assigning/get_next_application_spec.rb
- spec/system/closed_applications_dashboard_spec.rb
- spec/system/errors_spec.rb
- spec/system/manage_users/revive_a_user_spec.rb
- spec/system/searching/filter_by_age_in_business_days_spec.rb
- spec/system/searching/filter_by_caseworker_spec.rb
- spec/system/searching/filter_by_date_of_birth_spec.rb
- spec/system/searching/filter_by_date_range_spec.rb
- spec/system/searching/filter_by_status_spec.rb
Users can search applications by age in business days.
This feature is currently only enabled in local environments.
[CRIMAP-499](https://dsdmoj.atlassian.net/browse/CRIMAP-499)
The code surrounding the filter is more complex than I'd like. Most of this complexity arises because the data source for the search changes depending on which filters are active. "Caseworker" and "Business days since received" both use local data, while the remaining filters are for the datastore.
[CRIMAP-499]: https://dsdmoj.atlassian.net/browse/CRIMAP-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-499 filter by age in business days.

- app/controllers/performance_tracking_controller.rb
- app/views/layouts/_header.html.erb
- app/views/performance_tracking/index.html.erb
- config/locales/en.yml
- config/locales/en/performance_tracking.yml
- config/routes.rb
- spec/requests/authorisation_spec.rb
- spec/shared_contexts/with_a_logged_in_user.rb
- spec/system/header_nav_spec.rb
- spec/system/performance_tracking/viewing_spec.rb
Adds performance tracking page `/performance_tracking` which is hidden behind the `BasicUserRoles` feature flag and access is restricted to supervisors only.
Upon hitting the url, caseworkers are shown a 404 page and user managers are redirected to the manage users dashboard. The tab is also hidden from both user types. 
[CRIMAP-509](https://dsdmoj.atlassian.net/browse/CRIMAP-509)
[CRIMAP-510](https://dsdmoj.atlassian.net/browse/CRIMAP-510)
Not a fan of the Performance tracking name 😅 I'm assuming this is just a placeholder but other names are welcome 😄
Also now that we are introducing new roles and routes, it is worth potentially rethinking the current `authentication_spec.rb` format as I can see it becoming a big file down the line. Perhaps the testing of which areas of the service each …
> [CRIMAP-509/510] Add supervisor performance tracking page

- app/assets/stylesheets/local/custom.scss
- config/locales/en.yml
- spec/system/searching/filter_by_age_in_business_days_spec.rb
Update the filter label copy and increase the select width to be the same as the label.
[CRIMAP-499](https://dsdmoj.atlassian.net/browse/CRIMAP-499)
[CRIMAP-499]: https://dsdmoj.atlassian.net/browse/CRIMAP-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-499 Update filter label text

- app/controllers/application_controller.rb
- spec/system/performance_tracking/viewing_spec.rb
The service and performance tracking page are accessible to user managers by enabling the `allow_user_managers_service_access` feature flag on staging. However, whether the feature flag was enabled was the only condition being checked in the controllers meaning every user has access to the feature on staging as the feature flag is enabled for all on staging. This was not obvious previously as the service is also accessible to caseworkers and supervisors.
This condition has been changed to check whether a user can manage others as well as checking that the feature flag is enabled and tests have been modified to check both caseworker and user manager access of the performance tracking page on staging
[CRIMAP-535](https://dsdmoj.atlassian.net/browse/CRIMAP-535)
Merging this PR initially to …
> Ensure only user managers can access parts of the service on staging

- .env.development
- Procfile.dev
- config/environments/development.rb
- docker-compose.yml
We run Apply on port 3000 and Datastore on port 3003 by default, either when running the rails application locally or when using docker-compose.
However Review was by default using port 3000 too, clashing with Apply when all 3 apps needed to be run to produce an end-to-end journey.
This change makes the port 3001 the default one for Review. It is still possible to locally override this by exposing `PORT=X` in your `.env.development.local` file if you are used to a different port.
Additionally support connections from _inside_ a docker container (for instance localstack) to the application running in the host machine (_not_ as a container).
Running `rails s` and running `docker-compose up` should run both the app in port 3001 (unless you override it with the ENV variable PORT).
> Set default puma port to 3001 to avoid clashing

- app/services/aws/sns_service.rb
With the purpose of facilitate an end-to-end journey in localhost, using LocalStack for SNS and http callbacks, we skip the ARN allowlist, and the Signature verification.
Also added some meaningful logging which is interesting to have to diagnose any issues. Also if running Review in a docker container, the subscription will not be confirmed automatically, so logging the URL is needed to confirm it manually by visiting the URL.
This works along with PR in datastore:
https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/144
https://dsdmoj.atlassian.net/browse/CRIMAP-530
Happy to discuss if this is not desirable or if we favour a different approach. This is the simplest thing it came to mind without causing too much trouble.
Checkout this branch and start the rails …
> Skip some SNS security controls in development mode

- app/lib/prometheus_metrics/configuration.rb
- app/services/aws/sns_service.rb
- docker-compose.yml
With the objective of being able to run all 3 services (apply, review and datastore) at the same time as docker containers, some tweaks are needed.
Prometheus exporter port was hardcoded, it needs to be different in each container otherwise it will clash. Also by default now is disabled as most of the time we will never need it locally, but can be enabled for quick tests.
Added the datastore dummy credentials and endpoint (it works wether datastore is running also in a container, or on the host machine, assuming it's running in port 3003).
Added local docker to SNS bypass, for when Review is running as docker container.
`docker-compose up` will no longer run prometheus exporter. If datastore is up and running in port 3003, Review container will be able to talk to datastore too. SNS will …
> Tweak docker-compose

- Dockerfile
- Gemfile
- Gemfile.lock
Add gcombat and update dart-sass to allow ```docker-compose up``` with Apple Silicon
gcombat allows glibc programs to be run in Alpine Linux (https://wiki.alpinelinux.org/wiki/Running_glibc_programs)
It was also necessary to update dart-sass to a version that correctly understands the architecture it is working in.
To make sure this does not introduce a regression on Intel Mac, remove any docker files you may already have and run  ```docker-compose up```
> Docker compose works with apple silicon

- Dockerfile
The `postgresql-dev` and `postgresql-client` packages used in the Dockerfile were outdated, now that we are running postgres 15.x (locally, CI and also cloud platform through RDS).
This ensure alpine build the image using latest versions of the postgres libraries.
More info in slack thread
https://mojdt.slack.com/archives/C056U956ESH/p1692175607705879
> Update postgres client to fix vulns

- app/read_models/caseworker_reports/configuration.rb
- app/read_models/caseworker_reports/link_to_temporal_streams.rb
- config/initializers/event_store.rb
- spec/read_models/caseworker_reports/configuration_spec.rb
- spec/read_models/caseworker_reports/link_to_temporal_streams_spec.rb
Create event streams for monthly, daily and weekly caseworker reports.
[CRIMAP-543](https://dsdmoj.atlassian.net/browse/CRIMAP-543)
Create discrete linked streams for each month day and week so that caseworker reports can be viewed according to the day week and month.
[CRIMAP-543]: https://dsdmoj.atlassian.net/browse/CRIMAP-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-534 Link to caseworker events to temporal streams.

- .github/workflows/test-build-deploy.yml
Image tag sting had a comma in it which was causing the tag command to fail
[CRIMAP-577](https://dsdmoj.atlassian.net/browse/CRIMAP-577)
[CRIMAP-577]: https://dsdmoj.atlassian.net/browse/CRIMAP-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix docker tag issue where too many args were being passed

- app/models/crime_application.rb
- app/views/casework/crime_applications/_overview.html.erb
- spec/models/crime_application_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Show the red undetermined badge, when an applications means type is undetermined.
[CRIMAP-617](https://dsdmoj.atlassian.net/browse/CRIMAP-617)
Review no longer assumes that all applications are means passported.
passported:
undetermined:
[CRIMAP-617]: https://dsdmoj.atlassian.net/browse/CRIMAP-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-617 show means type undetermined when not passported

- app/models/reporting/temporal_report.rb
- app/read_models/caseworker_reports.rb
- app/read_models/caseworker_reports/configuration.rb
- app/read_models/caseworker_reports/link_to_temporal_streams.rb
- app/read_models/received_on_reports/close_application.rb
- app/read_models/received_on_reports/configuration.rb
- app/read_models/received_on_reports/handler.rb
- app/read_models/received_on_reports/link_to_received_on_stream.rb
- app/read_models/received_on_reports/receive_application.rb
- spec/read_models/received_on_reports/configuration_spec.rb
Link workload reporting events to received on business day streams.
[CRIMAP-589](https://dsdmoj.atlassian.net/browse/CRIMAP-589)
This is in preparation for building the workload report directly from events, which will allow workload reports to be generated for any time in the past.
[CRIMAP-589]: https://dsdmoj.atlassian.net/browse/CRIMAP-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-589 link workload reporting events to business day streams

- Gemfile
- Gemfile.lock
- app/models/crime_application.rb
- app/views/casework/crime_applications/_overview.html.erb
- config/locales/en/casework.yml
- spec/models/crime_application_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Surface passporting benefit type when it is provided.
If the applicant is passported but it is a historic application that did not have benefit type requested, list as 'Not requested'
If under 18, (or error has let through a non-means passported applicant) whole row is not shown. 
https://dsdmoj.atlassian.net/browse/CRIMAP-597
> CRIMAP-597 Show passporting benefit type on review page

- app/models/crime_application.rb
- app/views/casework/crime_applications/_interests_of_justice.html.erb
- app/views/casework/crime_applications/_overview.html.erb
- spec/models/crime_application_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Review should only show one IoJ passport
If there are both IoJ passports present ( 'on_offence', and 'on_age_under18') age passport is the only one that should be shown.
> Only show one ioj passport, with under 18 taking precedence

- Gemfile
- Gemfile.lock
- app/views/casework/crime_applications/_case_details.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Shows the first court hearing location name ('Initial court')
https://dsdmoj.atlassian.net/browse/CRIMAP-601
Not sure whether the `is_first_court_hearing` value needs to be checked as well to determine output?
Create and application and in the court hearing section enter appropriate values.
> [CRIMAP-601] Show first court hearing location

- config/kubernetes/staging/ingress.yml
Adds an exception to modsec to allow SNS events sent to /api/events
N/A
The following log error in kibana showed modsecurity rejecting AWS SNS Event notifications to /api/events because `text/plain` headers are disallowed by default by the OWASP Core ruleset.
Kibana log:
```
{
"transaction": {
"client_ip": "52.94.39.44",
"time_stamp": "Fri Oct  6 08:56:32 2023",
"server_id": "7e6bcce3ecf046b75f697a6d36c2d328899efc7c",
"client_port": 28793,
"host_ip": "172.20.63.31",
"host_port": 443,
"unique_id": "cfa545c3306c2ee94755b1339a5d472a",
"request": { "method": "POST", "http_version": 1.1, "uri": "/api/events" },
"response": {
"body": "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n", …
```
> [CHORE] Add modsec exception for SNS events STAGING ONLY

- config/kubernetes/staging/ingress.yml
Attempts to allow legitimate AWS SNS messages through using a regex. The actual header sent by AWS is: `Content-Type: text/plain; charset=UTF-8`
https://dsdmoj.atlassian.net/browse/CRIMAP-655
Tried to remove the regex so that ANY POST request would have the rule `920420` removed however that didn't work as intended with limited testing directly against staging. Using this PR to confirm properly the ingress is working for AWS SNS events.
> [CRIMAP-655] Use regex for sns modsecurity (STAGING ONLY)

- config/kubernetes/production/ingress.yml
Allows AWS SNS messages with `content-type: text/plain; charset=UTF-8` style header through the firewall.
https://dsdmoj.atlassian.net/browse/CRIMAP-655
This rule is already active in Staging.
The following curl request should return 422:
```
curl -X GET -H "Content-Type: text/plain; charset=UTF-8" https://review-criminal-legal-aid.service.justice.gov.uk -v
```
However the following curl request fails - the regex has given us a lot of grief so we will evaluate effectiveness over time:
```
curl -X POST -H "Content-Type: text/plain;" https://staging.review-criminal-legal-aid.service.justice.gov.uk/api/events -v
```
Use curl as per above
> [CRIMAP-655] Enable AWS SNS messages through modsecurity (PRODUCTION ONLY)

- app/models/reporting/business_day_age_range_row.rb
- app/models/reporting/workload_report.rb
- app/read_models/received_on_reports/link_to_received_on_stream.rb
- app/read_models/received_on_reports/projection.rb
- app/views/reporting/base/_workload_report.html.erb
- config/brakeman.ignore
- config/locales/en/casework.yml
- spec/models/reporting/business_day_age_range_row_spec.rb
- spec/models/reporting/workload_report_spec.rb
- spec/read_models/received_on_reports/projection_spec.rb
CRIMRE-589 refactor workload report to event source its data.
[CRIMAP-589](https://dsdmoj.atlassian.net/browse/CRIMAP-589)
The workload report has only been available as a snapshot of current state. CRIMRE-589  adds functionality to view this report as it was at any given time. This PR is a prepares for that by event sourcing the report rather than relying on the data cached in the ReceivedOnReport table.
Confirm that the mini report on the open applications page is correct.
[CRIMAP-589]: https://dsdmoj.atlassian.net/browse/CRIMAP-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-589 event source the workload mini report

- config/kubernetes/staging/ingress.yml
Prevent sql injection false positives on the rails session cookie
[CRIMAP-651](https://dsdmoj.atlassian.net/browse/CRIMAP-651)
False positives on the session cookie have been causing 403 errors. Here we use tags rather than id to prevent the offending rules being applied to the rails session cookie.  After testing on staging, this change will need to be applied to the production ingress.
[CRIMAP-651]: https://dsdmoj.atlassian.net/browse/CRIMAP-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-651 Skip attack-sqli check on session cookie

- Gemfile
- Gemfile.lock
- app/controllers/casework/documents_controller.rb
- app/services/datastore/documents/download.rb
- app/views/casework/crime_applications/_supporting_evidence.html.erb
- config/locales/en/casework.yml
- config/routes.rb
- spec/requests/authorisation_spec.rb
- spec/services/datastore/documents/download_spec.rb
- spec/shared_contexts/when_downloading_a_document.rb
- spec/system/casework/viewing_an_application/that_is_assigned_to_me_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
This is the second part of two PR's to implement downloading supporting evidence on review. This PR enables users to download evidence. There are two restrictions to downloading evidence: 1) You must be assigned to the application 2) You must be downloading a file that is uploaded to the current application (this is to prevent malicious actors from changing the application id of a link to an application they are assigned to, to download files in other applications). 
Videos are linked below to demonstrate the functionality 
[CRIMAP-526](https://dsdmoj.atlassian.net/browse/CRIMAP-526)
Note there is slightly different download behaviour per browser and we found that with a firefox browser, pdf files are downloaded and also opened in another tab. This didn't occur for png files and we …
> [CRIMAP-526] download supporting evidence

- app/controllers/reporting/snapshots_controller.rb
- app/controllers/reporting/user_reports_controller.rb
- app/helpers/app_text_helper.rb
- app/lib/types.rb
- app/models/reporting/business_day_age_range_row.rb
- app/models/reporting/snapshot.rb
- app/models/reporting/workload_report.rb
- app/read_models/received_on_reports/projection.rb
- app/views/reporting/snapshots/show.html.erb
- app/views/reporting/user_reports/index.html.erb
- config/brakeman.ignore
- config/locales/en.yml
- config/locales/en/reporting.yml
- config/routes.rb
- spec/models/reporting/business_day_age_range_row_spec.rb
- spec/models/reporting/snapshot_spec.rb
- spec/read_models/received_on_reports/projection_spec.rb
- spec/requests/authorisation_spec.rb
- spec/system/reporting/reports_page_spec.rb
- spec/system/reporting/snapshot_reports_spec.rb
Add prototype processed report snapshot
[CRIMAP-589](https://dsdmoj.atlassian.net/browse/CRIMAP-589)
Whilst the report can be viewed at any historical time, the UI has been kept simple to allow users to navigate to "Now" or the end of (23:59) any previous day. (The url can be altered to view the report at a different time.)
[CRIMAP-589]: https://dsdmoj.atlassian.net/browse/CRIMAP-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-589 prototype processed snapshot report

- Gemfile
- Gemfile.lock
Update Schema gem to 1.0.5 to allow optional Document.scan_status
https://dsdmoj.atlassian.net/browse/CRIMAP-675
Introduces new Document virus scan attributes ready for https://dsdmoj.atlassian.net/browse/CRIMAP-659
> [CRIMAP-675] Update schema gem to v1.0.5

- app/models/concerns/user_role.rb
- app/views/manage_users/history/_actions.html.erb
- config/settings.yml
- spec/models/concerns/user_role_spec.rb
- spec/system/manage_users/change_user_role_spec.rb
Remove basic user roles feature flag
[CRIMAP-679](https://dsdmoj.atlassian.net/browse/CRIMAP-679)
This feature is now available in all environments.
[CRIMAP-679]: https://dsdmoj.atlassian.net/browse/CRIMAP-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-679 remove basic user role feature flag

- app/controllers/errors_controller.rb
- app/views/layouts/errors.html.erb
- spec/system/authenticating/dev_auth_spec.rb
Do not show flash messages on error pages.
[CRIMAP-702](https://dsdmoj.atlassian.net/browse/CRIMAP-702)
To prevent information leakage flash messages should not be shown on error pages. This PR adds a dedicated errors layout and specs to make sure that flash messages are not included on error page errors.
Using the dev auth locally, select the "Not.Authorised@example.com"
Confirm that a flash notice is not shown on the resulting error page.
[CRIMAP-702]: https://dsdmoj.atlassian.net/browse/CRIMAP-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-702 do not show flash messages on error pages

- app/controllers/users/omniauth_callbacks_controller.rb
- config/application.rb
- spec/requests/authentication_spec.rb
- spec/system/authenticating/a_deactivated_user_spec.rb
- spec/system/authenticating/dev_auth_spec.rb
Refactor devise controller to directly use the application failure app.
[CRIMAP-702](https://dsdmoj.atlassian.net/browse/CRIMAP-702)
Whilst working on CRIMAP-702, I noticed that the devise errors had not been updated to use the application's failure app. This PR does that. It also adds a system spec for a deactivated user which was previously only tested in the model spec.
[CRIMAP-702]: https://dsdmoj.atlassian.net/browse/CRIMAP-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use rails failure app for devise errors.

- app/controllers/casework/documents_controller.rb
- app/services/datastore/documents/download.rb
- config/environments/test.rb
- config/locales/en/casework.yml
- spec/services/datastore/documents/download_spec.rb
- spec/shared_contexts/when_downloading_a_document.rb
- spec/system/casework/viewing_an_application/that_is_assigned_to_me_spec.rb
Follows PR in apply to add logging around evidence upload failures. The logs capture user id, ip address, severity (error), file type and s3 object key information. 
Also adds some error handling to display a message to the user if a download attempt failed. This follows an existing pattern for failures around evidence deletion currently implemented in apply. A screenshot is attached below. 
[CRIMAP-687](https://dsdmoj.atlassian.net/browse/CRIMAP-687)
Note: There is logging already in place in the [datastore](https://github.com/ministryofjustice/laa-criminal-applications-datastore/blob/main/app/services/operations/documents/traits/s3_operation.rb#L37) handling errors with calls to obtain the presign download url. By adding logging on review, we can collect additional information we are …
> [CRIMAP-687] evidence download failure logging 

- app/presenters/case_details_presenter.rb
- app/views/casework/crime_applications/_case_details.html.erb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Always displays `first_court_hearing_name`, assumes `first_court_hearing_name` is always populated with a value by Datastore. 
https://dsdmoj.atlassian.net/browse/CRIMAP-728
- Dependent on latest Datastore with [PR 79](https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/179)
1. Create a new application, in the court hearing section enter the hearing court name and select "Yes" for "Did this court also hear the first hearing". Submit application.
2. Log in to Review as caseworker and check the Case Details section
3. Try creating applications with "no hearing yet" and "no" as the answer to "Did this court also hear the first hearing". Try changing the court hearing details after they've been entered before submitting to ensure correct data is always output.
> [CRIMAP-728] Revert back to always outputting first_court_hearing_name

- app/controllers/casework/documents_controller.rb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Following confirmation from product, the restriction limiting users from downloading evidence on review if they are not assigned to an application has been removed. This is with the aim of revisiting what measures we could put in place to make evidence download more secure without impacting user needs in the future. More information in the ticket linked.
[CRIMAP-736](https://dsdmoj.atlassian.net/browse/CRIMAP-736)
https://github.com/ministryofjustice/laa-review-criminal-legal-aid/assets/51047911/039edc88-44fc-426b-af5d-32bb6b23a02d
Submit an application in apply with supporting evidence. Go to the submitted application in review and download that evidence. You should be able to download the evidence regardless of whether you are assigned to the application or not.
[CRIMAP-736]: …
> [CRIMAP-736] Remove restriction allowing only assigned users to download evidence

- Gemfile
- Gemfile.lock
Fixes sentry error: https://ministryofjustice.sentry.io/issues/4635857522/?alert_rule_id=14029744&alert_timestamp=1700049014274&alert_type=email&environment=staging&notification_uuid=4d3c22be-7e9b-462a-9766-52360ce25270&project=4504927032967168&referrer=alert_email
The work stream attribute was set to the case details level in the schema but as was being set to the crime application parent in the datastore. The schema was corrected to move the work stream attribute to the crime application struct
> Update schema to v1.0.7

- app/components/data_table/header_cell_component.rb
- app/views/reporting/base/_caseworker_report.html.erb
Fix missing translation error for cell without content.
This error only manifested in production env because translation errors render as strings in production env.
> CRIMAPP-78 handle empty cell content

- app/models/crime_application.rb
- app/views/casework/crime_applications/_overview.html.erb
- config/locales/en/casework.yml
- spec/models/crime_application_spec.rb
Conditional to show selected input for benefit type was on whether or not the applicant had a positive DWP result, rather than whether they had been (or historically would have been) shown this question. 
Potential outcomes as follows:
1. Selected a passporting benefit - shows benefit name
2. Selected 'None' - shows 'None'
3. Not shown question at time of application -  shows 'Not asked when this application was submitted'
4. Not shown question as applicant under 18 - line not shown on Review
https://dsdmoj.atlassian.net/browse/CRIMAPP-195
Relevance of when to show an answer is whether or not the provider would have been presented with the question (or would have if it was in the MVP from the start)
> CRIMAPP-195 Show benefit type if over 18

- Gemfile
- Gemfile.lock
Updates to latest schema to allow usage of `means_details` going forward
https://dsdmoj.atlassian.net/browse/CRIMAPP-105
N/A
>  [CRIMAP-129] Use latest schema 1.0.10

- app/aggregates/allocating.rb
- app/controllers/casework/base_controller.rb
- app/controllers/casework/crime_applications_controller.rb
- app/controllers/concerns/application_searchable.rb
- app/helpers/application_helper.rb
- app/models/reporting/workload_report.rb
- app/services/utils/current_work_stream_calculator.rb
- app/views/casework/assigned_applications/index.html.erb
- app/views/casework/base/_primary_navigation.html.erb
- app/views/casework/crime_applications/_open_closed_applications.html.erb
- app/views/casework/crime_applications/index.html.erb
- app/views/reporting/temporal_reports/show.html.erb
- config/application.rb
- config/routes.rb
- spec/helpers/application_helper_spec.rb
- spec/requests/authorisation_spec.rb
- spec/services/utils/current_work_stream_calculator_spec.rb
- spec/shared_contexts/with_stubbed_search.rb
- spec/system/casework/assigning/viewing_your_assigned_applications_spec.rb
- spec/system/casework/closed_applications_dashboard_spec.rb
- spec/system/casework/open_applications_dashboard_spec.rb
- spec/system/casework/primary_nav_spec.rb
Adds tabs to the open/closed for each work stream and show the number of applications received / still open or closed for each work stream
As part of this work, two new routes are added `applications/open/:work_stream` and `applications/closed/:work_stream`. The current routes `applications/open` and `applications/closed` are still available whilst this feature is in development. 
The work stream that a user selects is saved in the users session so that they can navigate to the last work stream they were looking at across the open and closed applications pages.
[CRIMAPP-229](https://dsdmoj.atlassian.net/browse/CRIMAPP-229)
[CRIMAPP-230](https://dsdmoj.atlassian.net/browse/CRIMAPP-230)
Note this does not change the data in the `Check when applications were received` mini report on the …
> Add work stream tabs to the open/closed applications pages

- Gemfile
- Gemfile.lock
Bump schema version to 1.0.11 to fix issue reading structs with empty income_details.
https://ministryofjustice.sentry.io/issues/4635857522/?environment=staging&query=start%3D2023-11-20T11%3A52%3A32%26end%3D2023-11-27T11%3A52%3A32%26groupStatsPeriod%3Dauto&referrer=alerts-related-issues-issue-stream#:~:text=REVIEW%2DCRIMINAL%2DLEGAL%2DAID%2D14
Navigate to an application's details and confirm the page loads as expected.
> Bump schema gem

- config/settings.yml
Sets work stream ff to false after it was accidentally enabled
https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/461
> [PATCH] Set work streams ff to false on prod

- config/settings.yml
Re-enables work stream feature flag that was [previously disabled](https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/481) on staging for regression testing.
> Re enable work stream ff on staging

- app/models/reporting/caseworker_report.rb
- spec/models/reporting/caseworker_report_spec.rb
Handle sorting by integer when nil
https://ministryofjustice.sentry.io/issues/4729005239/?environment=staging&query=&referrer=issue-stream&statsPeriod=7d&stream_index=1
nil values are assigned -1 for sorting which means they are differentiated from 0%
Attempt to sort the Caseworker report on Review when one of the percentages has a nil value.
> Handle sorting by integer when nil

- config/settings.yml
Work steams ff was previously disabled for regression testing on staging. This PR re-enables it
> Renable work stream ff on staging for qa

- app/controllers/application_controller.rb
- app/models/concerns/user_competence.rb
- app/models/concerns/user_role.rb
- app/models/user.rb
- app/views/layouts/_header.html.erb
- spec/models/concerns/user_competence_spec.rb
- spec/models/concerns/user_role_spec.rb
- spec/requests/authentication_spec.rb
- spec/system/header_nav_spec.rb
This pull request enables DataAnalysts to access the caseworker section of the service.
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375/backlog?selectedIssue=CRIMAPP-87
Previously, DataAnalysts didn't have access to the casework section. However, in practice, they require access to the search function and application details and history. Due to restrictions, DataAnalysts were included as Supervisors. Changes in competencies now permit users to access the caseworker section, but without specific caseworker competencies, they can't review applications.
This PR grants DataAnalysts access to the caseworker area, allowing them to view applications and conduct searches but preventing them from reviewing applications.
We do not have Data Analysts enrolled on production …
> [CRIMAPP-87] Allow Data Analyst casework read access

- app/controllers/casework/assigned_applications_controller.rb
- app/views/casework/application_searches/_search_results_table_body.html.erb
- app/views/casework/application_searches/search.html.erb
- spec/system/casework/no_competencies_spec.rb
- spec/system/casework/searching/search_filters_and_results_spec.rb
Discovered a bug in qa where when caseworkers with no competencies click to retrieve the next application, there is an error shown. This is because the search and sort filters were not being set when the page is being rendered with a flash message so the assigned applications table couldn't be populated. In future, assigned applications may be unassigned from caseworkers when their competencies are removed but this hasn't been agreed yet 
Also removes the application type column from following qa, as it was decided that this should be displayed once change in financial circumstances applications are coming through. Currently, every application is 'initial' so the column is not helpful 
[CRIMAPP-279](https://dsdmoj.atlassian.net/browse/CRIMAPP-279) …
> [CRIMAPP-279] Ensure assigned applications are displayed for users with no competencies

- app/views/casework/crime_applications/_income.html.erb
- app/views/casework/crime_applications/show.html.erb
- config/locales/en/casework.yml
- config/settings.yml
- spec/system/casework/viewing_an_application/application_details/income_details_spec.rb
Adds means journey feature flag 
Displays income details on application details page if present
If an application has not gone through the income details section, nothing is displayed
[CRIMAPP-283](https://dsdmoj.atlassian.net/browse/CRIMAPP-283)
Submit an application in apply with income details 
Go to review and view the application verify you can see the income details with the correct answers
Also verify an application with no income details does not display the section
[CRIMAPP-283]: https://dsdmoj.atlassian.net/browse/CRIMAPP-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-283] Add income section to app details

- app/views/casework/crime_applications/_other_income_details.html.erb
- app/views/casework/crime_applications/show.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/other_income_details_spec.rb
Adds other income details section to application details
[CRIMAPP-287](https://dsdmoj.atlassian.net/browse/CRIMAPP-287)
There was no design specified in the case that Other was selected but I have replicated what is displayed in apply for a completed application
Submit an application on apply with the other income details question answered 
Then check it is displayed in review 
Will need to check the view when the other option is selected
Also check applications that have not answered that question do not display the other income details section
[CRIMAPP-287]: https://dsdmoj.atlassian.net/browse/CRIMAPP-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-287] Add other income details section

- Gemfile
- Gemfile.lock
- app/models/crime_application.rb
- app/presenters/dependants_presenter.rb
- app/views/casework/crime_applications/_dependants.html.erb
- app/views/casework/crime_applications/_income.html.erb
- app/views/casework/crime_applications/_other_income_details.html.erb
- app/views/casework/crime_applications/show.html.erb
- config/locales/en/casework.yml
- config/settings.yml
- spec/presenters/dependants_presenter_spec.rb
- spec/system/casework/viewing_an_application/application_details/dependants_spec.rb
- spec/system/casework/viewing_an_application/application_details/income_details_spec.rb
Adds dependants section to application details 
Also fixes issue with income details section where rows where being displayed for questions that were not shown during the application
Note needs to be merged after accompanying [apply PR ](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/589)to amend the serialisation and rehydration due to schema changes
Displays dependants section if dependants submitted as part of application 
Displays no dependants if no dependants selected 
Displays nothing if dependants screen was not seen during application
Requires an application with dependants, an application where no dependants has been selected and an application which hasn't gone through the dependants screen on apply 
Navigate to review and check each of the following …
> [CRIMAPP-286] Add dependants section to app details

- app/views/casework/crime_applications/_case_details.html.erb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Do not show MAAT id if appeal with change in financial circumstances.
[CRIMAPP-323](https://dsdmoj.atlassian.net/browse/CRIMAPP-323)
[CRIMAPP-323]: https://dsdmoj.atlassian.net/browse/CRIMAPP-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-323 Do not show MAAT id when appeal with cifc

- Gemfile.lock
Revert importmap upgrade
This was causing assets not to build correctly on live services. Temporary reversion to prevent this issue on live services.
> Revert importmap upgrade

- Gemfile
- Gemfile.lock
- app/models/application_search_result.rb
- app/models/crime_application.rb
- app/views/casework/crime_applications/_client_details.html.erb
- app/views/casework/crime_applications/_initial.html.erb
- app/views/casework/crime_applications/_overview.html.erb
- app/views/casework/crime_applications/_pse.html.erb
- app/views/casework/crime_applications/_supporting_evidence.html.erb
- app/views/casework/crime_applications/show.html.erb
- config/locales/en/casework.yml
- config/settings.yml
- spec/models/crime_application_spec.rb
- spec/system/casework/viewing_an_application/post_submission_evidence_application_spec.rb
Sets up the display for a PSE application. Displays client details, provider details and post submission evidence details, along with the application type in the overview section
[CRIMAPP-350](https://dsdmoj.atlassian.net/browse/CRIMAPP-350)
The crime_application folder in views could do with some organisation/refactoring as there are a lot of files and I wonder if it is easy to navigate for newcomers. I think this could involve a new controller so won't do as part of this PR but i'll add a ticket to the backlog to prioritise as some point. 
Also no feature flag added (yet) as this is all dependant on PSE being live on apply
Note: the work to submit a PSE application on apply has not been completed so this requires checking out of the spike branch in apply to submit a PSE application to …
> [CRIMAPP-350] Display PSE relevant details for PSE application

- Gemfile
- Gemfile.lock
- app/views/casework/crime_applications/_overview.html.erb
- config/locales/en/casework.yml
Add *case_concluded attributes in "Application details" sections of the page
https://dsdmoj.atlassian.net/browse/CRIMAPP-310
> CRIMAPP-310 Add "has_case_concluded" attributes

- app/views/casework/crime_applications/show.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/post_submission_evidence_application_spec.rb
Hides the `send back to provider` and `mark as ready for maat` review buttons for pse applications. Only displays the `mark as complete` action
[CRIMAPP-375](https://dsdmoj.atlassian.net/browse/CRIMAPP-375)
**Note: Make sure you have built datastore and crime apply from main**
**Steps for testing:**
- Submit a standard application in apply and review the application in review (as can only submit pse for applications that are complete)
- Then go back to apply and find the application in the submitted tab. Click on the application and click upload post submission evidence
- Submit your pse application and then go to review and find and assign the pse application to yourself 
- Check the button displayed says `mark as complete` and you can click that button and the application is marked as …
> [CRIMAPP-375] Display mark as complete for pse applications

- app/presenters/case_details_presenter.rb
- app/views/casework/crime_applications/_overview.html.erb
- config/locales/en/casework.yml
Display "Has the case concluded" date conditionally (Please refer to the screenshots)
https://dsdmoj.atlassian.net/browse/CRIMAPP-310
**Actual text is different from screenshot**
- Date when the case concluded -> When the case concluded
**1) For old Applications when "Has the case concluded" question was never asked**
**2) For new applications when "Has the case concluded" question was asked with 2 possible answers**
> RIMAPP-310- Udate application details view

- Gemfile
- Gemfile.lock
- app/presenters/case_details_presenter.rb
- app/views/casework/crime_applications/_overview.html.erb
- config/locales/en/casework.yml
Display "Has the court remanded your client in custody" date conditionally (Please refer to the screenshots)
https://dsdmoj.atlassian.net/browse/CRIMAPP-314
Actual text is different from screenshot
- Has a court remanded your client in custody? -> Has a court remanded client in custody?
- Date when they were remanded -> When they were remanded
**1) For old Applications when "Has the court remanded your client in custody"  question was never asked**
**For New Applications  when "Has the court remanded your client in custody"  question was asked**
> CRIMAPP-314 Add "has the court remanded your client in custody" attributes

- Gemfile
- Gemfile.lock
- app/views/casework/crime_applications/_employment.html.erb
- app/views/casework/crime_applications/_initial.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/employment_spec.rb
Adds employment information to the application details section if present
[CRIMAPP-330](https://dsdmoj.atlassian.net/browse/CRIMAPP-330)
**With all employment details**
**With employment details when job not lost in custody**
**With all employment details when employment not ended in the last three months**
Requires an application with all employment details entered, an application where No has been selected for `Did they lose their job as a result of being in custody?` and an application where No has been selected for `Have they ended employment in the last 3 months?`
Navigate to review and check the application details section matches the screenshots above for the relevant application 
Also check that existing applications on review do not display the employment section and any new …
> [CRIMAPP-330] Display employment section in application details

- app/controllers/casework/assigned_applications_controller.rb
- app/lib/types.rb
- app/models/application_search_filter.rb
- app/models/concerns/user_competence.rb
- app/models/get_next.rb
- config/locales/en/casework.yml
- spec/models/concerns/user_competence_spec.rb
- spec/system/casework/assigning/get_next_application_spec.rb
Supervisors can now assign a PSE competency to a caseworker
A caseworker with a PSE competency can pick up a PSE application via the get next button
A caseworker without a PSE competency can’t pick up a PSE application via the get next button
[CRIMAPP-421](https://dsdmoj.atlassian.net/browse/CRIMAPP-421)
This is a change to the way work queues and competency assignment currently works in comparison to eForms.  
Work needs to be done consider how to explain how this works to supervisors and caseworkers on review and ensure they are trained to understand the differences
**Changes to the competency form** 
**Retrieving a PSE application as a caseworker with the PSE competency** 
**Retrieving a PSE application as a caseworker without the PSE competency** 
**Note: Requires a pse application to …
> [CRIMAPP-421] Add PSE as a competency

- app/views/casework/crime_applications/_additional_information.en.html.erb
- app/views/casework/crime_applications/show.html.erb
- spec/system/casework/viewing_an_application/application_details/additional_information_spec.rb
Show additional information from the provider in application details.
[CRIMAPP-428](https://dsdmoj.atlassian.net/browse/CRIMAPP-428)
View an application with additional information, confirm that they are show as per design. 
View an application without additional information, confirm that the inset text is not shown.
[CRIMAPP-428]: https://dsdmoj.atlassian.net/browse/CRIMAPP-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-428 Show additional information.

- Gemfile
- Gemfile.lock
- app/presenters/case_details_presenter.rb
- app/views/casework/crime_applications/_overview.html.erb
- config/locales/en/casework.yml
Display "Do you intend to claim pre-order work?" `preorder_work_date` and `preorder_work_details`  conditionally (Please refer to the screenshots)
https://dsdmoj.atlassian.net/browse/CRIMAPP-366
**1) For old Applications when "Do you intend to claim pre-order work?" question was never asked**
**2) For new applications when "Do you intend to claim pre-order work?" question was asked with 2 possible answers**
information is available on http://REVIEW-APP/applications/:id
> RIMAPP-366 Add-pre-order-work-page attributes

- app/aggregates/reviewing/commands/receive_application.rb
- app/models/concerns/reviewable.rb
- spec/aggregates/reviewing/complete_spec.rb
- spec/aggregates/reviewing/mark_as_ready_spec.rb
- spec/aggregates/reviewing/receive_application_spec.rb
- spec/aggregates/reviewing/send_back_spec.rb
- spec/read_models/received_on_reports/configuration_spec.rb
- spec/read_models/received_on_reports/projection_spec.rb
Fixes local regression where superseded applications are missing superseded styling elements (e.g. the link to go to the latest version of the application, greyed out test etc..). This was due to recent changes to prevent initial applications from adopting the superseded styling when a pse application is submitted. 
[CRIMAPP-515](https://dsdmoj.atlassian.net/browse/CRIMAPP-515)
1. Submit an application in Apply
2. In Review, assign that application to list and return to provider with any reason
3. Resubmit from Apply
4. In Review go to Closed Applications tab and open the 1st version that was submitted. 
Confirm the following styling:
- Greyed out reference number and name
- Copy reference number link should not be visible
- Warning text: This application has been resubmitted. Go to the …
> [CRIMAPP-515] Display superseded styling for superseded applications

- package.json
Fix bug seen on staging where the mini reports on the open/closed applications pages were not displaying 
Also checked reports are working as expected
Seems to be due to the post install script that was changing the pin in the import map for govuk frontend from pin `"govuk-frontend", to: "https://ga.jspm.io/npm:govuk-frontend@5.2.0/dist/govuk/all.mjs"`  to pin `"govuk-frontend" # @5.2.0`
Pull down this branch 
Run yarn install
Check the mini reports on the open/closed applications pages are visible and displaying the correct data
Also check the reports are displaying as expected (need to be signed in as a supervisor or data analyst to view)
> Fix mini report bug

- Gemfile
- Gemfile.lock
- app/views/casework/crime_applications/_capital_details.html.erb
- app/views/casework/crime_applications/sections/_other_capital_details.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/income_details_spec.rb
- spec/system/casework/viewing_an_application/application_details/other_capital_details_spec.rb
Displays answer to step "Does your client have any income, savings or assets under a restraint or freezing order?" in the capital section if it was not asked in the income assessment section on apply
If this question was not asked, the other capital section is not shown
[CRIMAPP-505](https://dsdmoj.atlassian.net/browse/CRIMAPP-505)
Requires [apply PR](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/712) with apply side changes for local testing
Submit an application in apply with the step `Does your client have any income, savings or assets under a restraint or freezing order?` answered. Instructions for this is in the apply pr 
Then confirm a `other capital` section is shown in review with the correct data 
Then submit an application without answering the step …
> [CRIMAPP-505] Display frozen income savings assets in capital

- app/models/application_search_sorting.rb
- spec/system/casework/assigning/viewing_your_assigned_applications_spec.rb
- spec/system/casework/closed_applications_dashboard_spec.rb
- spec/system/casework/open_applications_dashboard_spec.rb
- spec/system/casework/searching/sorting_search_results_spec.rb
Add sorting by application type to open applications, closed applications, search and your list pages.
[CRIMAPP-348](https://dsdmoj.atlassian.net/browse/CRIMAPP-348)
requires https://github.com/ministryofjustice/laa-criminal-applications-datastore/compare/CRIMAPP-348-sort-by-application-type?expand=1
[CRIMAPP-348]: https://dsdmoj.atlassian.net/browse/CRIMAPP-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-348 sort by application type

- app/aggregates/reviewing/review.rb
- app/controllers/reporting/snapshots_controller.rb
- app/models/reporting/workload_report.rb
- app/models/reporting/workload_report_row.rb
- app/read_models/received_on_reports/projection.rb
- app/read_models/reviews/update_from_aggregate.rb
- app/views/reporting/base/_workload_report.en.html.erb
- db/migrate/20240315132443_add_appplication_type_to_review_read_model.rb
- db/schema.rb
- spec/models/reporting/workload_report_spec.rb
- spec/read_models/received_on_reports/projection_spec.rb
- spec/read_models/reviews/update_from_aggreate_spec.rb
- spec/system/casework/open_applications_dashboard_spec.rb
- spec/system/reporting/snapshot_reports_spec.rb
- spec/system/reporting/workload_report_spec.rb
Add separate rows for `initial` and `pse` in the workload report.
Show each workstream as a separate table in the workload report.
Store application_type on Review read model.
[CRIMAPP-626](https://dsdmoj.atlassian.net/browse/CRIMAPP-626)
This is required for release of PSE
[CRIMAPP-626]: https://dsdmoj.atlassian.net/browse/CRIMAPP-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-626 Add PSE to workload report

- .rubocop.yml
- app/controllers/concerns/work_streamable.rb
- app/controllers/manage_competencies/caseworker_competencies_controller.rb
- app/lib/types.rb
- app/models/concerns/user_competence.rb
- app/models/get_next.rb
- app/presenters/caseworker_presenter.rb
- app/views/manage_competencies/caseworker_competencies/edit.html.erb
- config/locales/en.yml
- config/locales/en/manage_competencies.yml
- spec/controllers/concerns/work_streamable_spec.rb
- spec/models/concerns/user_competence_spec.rb
- spec/shared_contexts/with_a_logged_in_user.rb
- spec/system/casework/assigning/get_next_application_spec.rb
- spec/system/manage_competencies/change_user_competencies_spec.rb
- spec/system/manage_competencies/viewing_spec.rb
Stop setting 'initial' as the default competency for all caseworkers.
Make supervisors competencies configurable.
Visually distinguish competencies by type on the edit form.
[CRIMAPP-646](https://dsdmoj.atlassian.net/browse/CRIMAPP-646)
In order to allow some caseworkers to focus exclusively on PSE, supervisors need the ability remove the ‘initial’ competency which is currently assigned to all caseworkers by default.
see ticket
[CRIMAPP-646]: https://dsdmoj.atlassian.net/browse/CRIMAPP-646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-646 change competency defaults

- app/controllers/manage_competencies/caseworker_competencies_controller.rb
- spec/system/manage_competencies/viewing_spec.rb
Allow user managers' competencies to be configured on staging.
> User manager competencies can be configured on staging

- Gemfile
- Gemfile.lock
- app/models/crime_application.rb
- app/presenters/income_payments_presenter.rb
- app/views/casework/crime_applications/_address.html.erb
- app/views/casework/crime_applications/_income_details.html.erb
- app/views/casework/crime_applications/_payment_with_frequency.html.erb
- app/views/casework/crime_applications/sections/_income_payments.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/address_details_spec.rb
- spec/system/casework/viewing_an_application/application_details/income_payments_spec.rb
- spec/system/casework/viewing_an_application/application_details/trust_fund_spec.rb
Displays income payments a client gets
Also updates presentation order of address fields 
[CRIMAPP-284](https://dsdmoj.atlassian.net/browse/CRIMAPP-284)
Submit an application with income payment details. Then confirm details appear similar to the first screenshot above
Also submit an application where `My client does not get any of these payments` has been selected for income payment details and confirm it appears as the second screenshot 
[CRIMAPP-284]: https://dsdmoj.atlassian.net/browse/CRIMAPP-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-284] Display income payments client gets

- app/views/casework/crime_applications/_capital_details.html.erb
Assets is being displayed after the investment section instead of before the savings section
> Fix placement of assets section

- app/views/casework/crime_applications/sections/_income_benefits.html.erb
- app/views/casework/crime_applications/sections/_income_payments.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/income_benefits_spec.rb
- spec/system/casework/viewing_an_application/application_details/income_payments_spec.rb
Display other income benefits/payments details in review
[CRIMAPP-728](https://dsdmoj.atlassian.net/browse/CRIMAPP-728)
[CRIMAPP-729](https://dsdmoj.atlassian.net/browse/CRIMAPP-729)
Submit an application in apply with other income benefits and payments details
Confirm the rows are being displayed in review
Also confirm the rows are not displayed if no other income benefits and payments were selected and when there are no income payments/benefits 
[CRIMAPP-728]: https://dsdmoj.atlassian.net/browse/CRIMAPP-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-729]: https://dsdmoj.atlassian.net/browse/CRIMAPP-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-728, 729] Add other income benefit/payment details

- Gemfile
- Gemfile.lock
- app/models/crime_application.rb
- app/views/casework/crime_applications/_initial.html.erb
- app/views/casework/crime_applications/_overview.html.erb
- config/locales/en/casework.yml
- spec/models/crime_application_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Displays last jsa appointment if benefit type is jsa and also if it is present (as for historical applications it was not previously collected)
Also moves supporting evidence section to after the means assessment sections (bug ticket 739)
[CRIMAPP-441](https://dsdmoj.atlassian.net/browse/CRIMAPP-441)
[CRIMAPP-739](https://dsdmoj.atlassian.net/browse/CRIMAPP-739)
** App with JSA with last jsa appointment date**
**App with JSA with no last jsa appointment date (historical application)**
**App with a different passporting benefit (no last jsa appointment date)**
**Supporting evidence displayed underneath means**
**Requires checking out of these [apply](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/776) and …
> [CRIMAPP-441] Display last jsa appointment date

- app/models/crime_application.rb
- app/views/casework/crime_applications/_appeal_income_details.html.erb
- app/views/casework/crime_applications/_appeal_no_changes.html.erb
- app/views/casework/crime_applications/_client_details.html.erb
- app/views/casework/crime_applications/_overview.html.erb
- app/views/casework/crime_applications/show.html.erb
- config/locales/en/casework.yml
- spec/models/crime_application_spec.rb
Conditionally show income sections for appeal no changes
Populate a sensible value for Application Mean Tested field
https://dsdmoj.atlassian.net/browse/CRIMAPP-754
> Conditionally show income sections for appeal no changes

- Gemfile
- Gemfile.lock
- app/models/crime_application.rb
- app/presenters/properties_presenter.rb
- app/views/casework/crime_applications/_capital_details.html.erb
- app/views/casework/crime_applications/_income_details.html.erb
- app/views/casework/crime_applications/_initial.html.erb
- app/views/casework/crime_applications/_outgoings_details.html.erb
- app/views/casework/crime_applications/sections/_income_benefits.html.erb
- app/views/casework/crime_applications/sections/_income_payments.html.erb
- app/views/casework/crime_applications/sections/_investments.html.erb
- app/views/casework/crime_applications/sections/_national_savings_certificates.html.erb
- app/views/casework/crime_applications/sections/_outgoing_payments.html.erb
- app/views/casework/crime_applications/sections/_properties.html.erb
- app/views/casework/crime_applications/sections/_savings.html.erb
- config/locales/en/casework.yml
- spec/models/crime_application_spec.rb
- spec/system/casework/viewing_an_application/application_details/income_benefits_spec.rb
- spec/system/casework/viewing_an_application/application_details/income_payments_spec.rb
- spec/system/casework/viewing_an_application/application_details/investments_spec.rb
- spec/system/casework/viewing_an_application/application_details/national_savings_certificates_spec.rb
- spec/system/casework/viewing_an_application/application_details/outgoing_payments_spec.rb
- spec/system/casework/viewing_an_application/application_details/properties_spec.rb
- spec/system/casework/viewing_an_application/application_details/savings_spec.rb
Display assets, savings, investments, national saving certificates when none selected 
Also updates income payments, income benefits and outgoings payments to use newly added attributes
[CRIMAPP-735](https://dsdmoj.atlassian.net/browse/CRIMAPP-735)
[CRIMAPP-735]: https://dsdmoj.atlassian.net/browse/CRIMAPP-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-735] display absent asset, savings, investments, nsc records

- Gemfile
- Gemfile.lock
- app/views/casework/crime_applications/_client_details.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/address_details_spec.rb
- spec/system/casework/viewing_an_application/application_details/national_savings_certificates_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Displays residence type on review if present
Does not display home address row if residence type is none (as question is not asked in apply)
[CRIMAPP-776](https://dsdmoj.atlassian.net/browse/CRIMAPP-776)
**When question was asked**
**For historical apps where question was not asked**
[CRIMAPP-776]: https://dsdmoj.atlassian.net/browse/CRIMAPP-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-776] Display residence type in review

- app/views/casework/crime_applications/sections/_trust_fund.html.erb
Trust fund value was not displaying the pennies, this has been corrected
We could do with amending the fixure data to include pence in the value so we can test this and get a failing spec if there was a regression
> [CRIMAPP-759] Display trust fund value to 2dp

- app/views/casework/crime_applications/history.html.erb
- app/views/casework/crime_applications/show.html.erb
Correct styling of full width columns.
[CRIMAPP-814](https://dsdmoj.atlassian.net/browse/CRIMAPP-814)
[CRIMAPP-814]: https://dsdmoj.atlassian.net/browse/CRIMAPP-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix regression in column layout

- Gemfile
- Gemfile.lock
- app/presenters/income_benefits_presenter.rb
- app/presenters/income_payments_presenter.rb
- spec/presenters/income_benefits_presenter_spec.rb
- spec/presenters/income_payments_presenter_spec.rb
Updates schema version
Modifies income payments and income benefits presenters to only display payments with an ownership type of applicant ahead of partner work (and to fix specs failing due to fixture updates) 
[CRIMAPP-840](https://dsdmoj.atlassian.net/browse/CRIMAPP-840)
[CRIMAPP-840]: https://dsdmoj.atlassian.net/browse/CRIMAPP-840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-840] Update schema to v1.1.3

- Gemfile
- Gemfile.lock
- app/models/crime_application.rb
- app/views/casework/crime_applications/_initial.html.erb
- app/views/casework/crime_applications/_passporting_benefit_check.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/passporting_benefit_check_spec.rb
Adds passporting benefit check section to display dwp outcome 
[CRIMAPP-914](https://dsdmoj.atlassian.net/browse/CRIMAPP-914)
Note: Requires [apply](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/867) and [datastore](https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/264) changes
In apply, create and submit applications for each of the scenarios outlined in the [ticket](https://dsdmoj.atlassian.net/browse/CRIMAPP-912)/[figma](https://www.figma.com/design/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=10335-85981&t=XHpTZgeMrrckBs4q-0)
Then navigate to review and confirm the view of the passporting benefit check section matches that on apply/ in the designs 
[CRIMAPP-914]: https://dsdmoj.atlassian.net/browse/CRIMAPP-914?atlOrigin=eyJpIjoiNWR …
> [CRIMAPP-914] Display unemployed client dwp outcome

- Gemfile
- Gemfile.lock
- app/views/casework/crime_applications/sections/_savings.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/savings_spec.rb
Show the 'Partner’s wages or benefits paid into this account?' answer in the saving card if given.
[CRIMAPP-945](https://dsdmoj.atlassian.net/browse/CRIMAPP-945)
[CRIMAPP-945]: https://dsdmoj.atlassian.net/browse/CRIMAPP-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-945-add-partner-wages-qestion

- Gemfile
- Gemfile.lock
- app/presenters/income_payments_presenter.rb
- app/views/casework/crime_applications/_income_details.html.erb
- app/views/casework/crime_applications/sections/_employments.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/employments_spec.rb
Show employment and deductions in application details page
https://dsdmoj.atlassian.net/browse/CRIMAPP-878
https://dsdmoj.atlassian.net/browse/CRIMAPP-875
> [!IMPORTANT]  
> Currently we are rehydrating only Employments loop with deductions. Standalone pages (`Employment income`, `Self assessment tax bill `and `other work benefits`) are still pending for rehydration which will be addresses in separate PR
> CRIMAPP-875,878-employed-income-rehydration-and-adding-to-data-store and  Employed Income sections to Crime Review

- app/views/casework/crime_applications/_appeal_no_changes.html.erb
- app/views/casework/crime_applications/_initial.html.erb
- app/views/casework/crime_applications/_partner_details.html.erb
Fixes error with displaying the partner section when there is no partner due to the way the nino is being passed into the partial which errors when partner is nil
Also removes the partner details from the appeal no changes partial as partner questions are not asked when the case type is appeal no changes
> Fix bugs displaying partner section

- Gemfile
- Gemfile.lock
- app/models/crime_application.rb
- app/presenters/income_payments_presenter.rb
- app/views/casework/crime_applications/_income_details.html.erb
- app/views/casework/crime_applications/sections/_employments.html.erb
- app/views/casework/crime_applications/sections/_partner_other_work_benefits.html.erb
- app/views/casework/crime_applications/sections/_partner_self_assessment_tax_bill.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/employments_spec.rb
Add partner income details
- partner employments
- partner work benefits
- partner self assessment tax bill
https://dsdmoj.atlassian.net/browse/CRIMAPP-1029
f changes (if applicable)
> CRIMAPP-1029: Add Employed Income parter to Crime Review

- app/helpers/application_helper.rb
- app/views/casework/crime_applications/_capital_details.html.erb
- app/views/casework/crime_applications/sections/_premium_bonds.html.erb
- app/views/casework/crime_applications/sections/_premium_bonds_partner.html.erb
- config/locales/en/casework.yml
- spec/shared_contexts/with_stubbed_application.rb
- spec/system/casework/viewing_an_application/application_details/premium_bonds_partner_spec.rb
- spec/system/casework/viewing_an_application/application_details/premium_bonds_spec.rb
Combines partner an client premium bonds into a single card where appropriate.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1106
> CRIMAPP-1106 combine partner and client premium bonds

- app/views/casework/crime_applications/_declarations.html.erb
- app/views/casework/crime_applications/_initial.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/declarations_spec.rb
Show declaration section, conditionally showing partner rows
https://dsdmoj.atlassian.net/browse/CRIMAPP-1088
Any application that is submitted is default signed by provider declaring that they have the client's declaration, so that is default and hardcoded as Yes
SCENARIO 1:
Create an application on Apply main
Add a partner
Fill in declaration at the end with 'no' and some reason 
Submit
Check in Review the row show correctly
SCENARIO 2:
Create an application on Apply main
Add a partner
Fill in declaration at the end with 'yes'
Submit
Check in Review the rows show correctly
SCENARIO 3:
Create an application on Apply main
DO NOT add a partner
Shouldn't see partner declaration on Apply submission
Submit
Check in Review only the one row shows and partner rows are not there
> Show declaration section, conditionally showing partner rows

- app/views/casework/crime_applications/sections/_passporting_benefit_check_partner.html.erb
- spec/system/casework/viewing_an_application/application_details/passporting_benefit_check_partner_spec.rb
Only show partner benefit details if partnerincluded in means assessment
CRIMAPP-1115
> only show partner benefit check with no conflict

- Dockerfile
Use up-to-date AWS CA bundle for RDS for secure connectivity between application server and RDS
Replaces deprecated `MAINTAINER` with `LABEL` instruction
N/A
> [EXPERIMENTAL] Update CA bundle, remove MAINTAINER

- app/models/crime_application.rb
- app/views/casework/crime_applications/_income_details.html.erb
- app/views/casework/crime_applications/sections/_businesses.html.erb
- config/locales/en/casework.yml
- config/settings.yml
- spec/system/casework/viewing_an_application/application_details/businesses_spec.rb
Display client and partner businesses if present 
[CRIMAPP-1068](https://dsdmoj.atlassian.net/browse/CRIMAPP-1068)
Note: self employed is not yet available on Crime Apply so if testing locally, you will need to pull down and test via [this branch](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1008)
Note: there are a couple of screens yet to be implemented in the self employed flow so this implements only what is available on the branch listed above.
[CRIMAPP-1068]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1068] Display self employed businesses

- Gemfile
- Gemfile.lock
Upgrade openid connect dependencies
As per https://github.com/omniauth/omniauth_openid_connect/pull/182
> Upgrade openid connect dependencies

- app/views/casework/crime_applications/_income_details.html.erb
- app/views/casework/crime_applications/sections/_employment.html.erb
- app/views/casework/crime_applications/sections/_employments.html.erb
- spec/system/casework/viewing_an_application/application_details/employments_spec.rb
* Remove 'partner income' heading
* Fix unemployed 'when did your client end employment' question showing unless they are unemployed
* Fix ordering of income and jobs sections to match Apply
[CRIMAPP-1162](https://dsdmoj.atlassian.net/browse/CRIMAPP-1162)
[CRIMAPP-1159](https://dsdmoj.atlassian.net/browse/CRIMAPP-1159)
[CRIMAPP-1157](https://dsdmoj.atlassian.net/browse/CRIMAPP-1157)
[CRIMAPP-1162]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1159]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1157]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
> CRIMAPP-1162-1159 Fix display issues on Application page

- app/views/casework/crime_applications/_case_details.html.erb
- app/views/casework/crime_applications/_initial.html.erb
Conditional to show case details section was on whether there was a case type. There is no case type, but are other case details present on non-means applicaitons. 
The only application type with no case details is  PSE, so conditional now base on that.
Case type row hidden for non-means
https://dsdmoj.atlassian.net/browse/CRIMAPP-1194
> Always show case details attributes unless PSE

- Gemfile
- Gemfile.lock
- app/models/crime_application.rb
- spec/models/crime_application_spec.rb
Refactors `#non_means_tested` to calculate apps non means status with the `is_means_tested` attribute rather than the means passport value. This is to prevent inaccuracies in the event that an application is resubmitted and the means passport value has not been updated
Also updates schema version to v1.1.30
[CRIMAPP-1195](https://dsdmoj.atlassian.net/browse/CRIMAPP-1195)
Follow steps in ticket
[CRIMAPP-1195]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1195] Calculate non means status with `is_means_tested` attribute

- app/models/crime_application.rb
- app/presenters/income_details_presenter.rb
- app/views/casework/crime_applications/_income_details.html.erb
- app/views/casework/crime_applications/sections/_employment.html.erb
- app/views/casework/crime_applications/sections/_income.html.erb
- app/views/casework/crime_applications/sections/_partner_employment.html.erb
- config/locales/en/casework.yml
Fix employment status text for Client and Partner
https://dsdmoj.atlassian.net/browse/CRIMAPP-1228
> CRIMAPP-1228:  Fix employment status display for client and partner

- app/views/casework/crime_applications/_income_details.html.erb
- app/views/casework/crime_applications/sections/_income.html.erb
Hide income threshold section for self-employed journey
Move self-assessment tax bill and other work benefits sections to below self-employed sections
[CRIMAPP-1211](https://dsdmoj.atlassian.net/browse/CRIMAPP-1211)
[CRIMAPP-1210](https://dsdmoj.atlassian.net/browse/CRIMAPP-1210)
[CRIMAPP-1211]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1210]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1211-1210 Fix order of employment sections

- app/views/casework/crime_applications/sections/_income.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/income_details_spec.rb
Fix 'income_above_threshold' text in 'Application details' section based on the following:
When partner is included show "Joint income more than £12,475 a year before tax?"
When partner is not included show "Income more than £12,475 a year before tax?"
https://dsdmoj.atlassian.net/browse/CRIMAPP-1225
> CRIMAPP-1225: Fix income label

- app/views/casework/crime_applications/_partner_details.html.erb
- spec/system/casework/viewing_an_application/application_details/partner_details_spec.rb
Fix 'Partner details' > 'Conflict of interest?' values
https://dsdmoj.atlassian.net/browse/CRIMAPP-1233
> CRIMAPP-1233: Fix partner with conflict of interest value

- Gemfile
- Gemfile.lock
Bump schema version to v1.2.1
https://dsdmoj.atlassian.net/browse/CRIMAPP-963
> CRIMAPP-963: Update schema version to v1.2.1

- app/views/casework/crime_applications/_overview.html.erb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Updates the logic displaying the means test status of an application on review
Now the question to ask providers whether an application is subject to the means test has been added to apply, new applications will have a value (`yes`/`no`) and this value will display. For historical applications where there is no value for this question, the row will not be displayed. 
This changes previous behaviour where a passported badge would display if the dwp check was successful and an undetermined badge would display if the dwp check was undetermined. Due to the changes in how the benefit check result is displayed, this is now handled in the passporting benefit check section. 
This change has been agreed with design who will also look into the overview section and how it can be updated at some …
> [CRIMAPP-1254] Update means test row

- app/presenters/case_details_presenter.rb
- spec/system/casework/viewing_an_application/application_details/case_details_spec.rb
Allow applications without hearing date to be reviewed.
[LAA-REVIEW-CRIMINAL-LEGAL-AID-14](https://ministryofjustice.sentry.io/issues/5657883847/)
PR resolves a blocking production issue.
> LAA-REVIEW-CRIMINAL-LEGAL-AID-14 allow nil hearing date

- Gemfile.lock
- config/kubernetes/staging/deployment.tpl
- spec/controllers/concerns/work_streamable_spec.rb
- use ping for Liveness probe
- remove initial delay on liveness probe
- extend delay on readyness probe
The liveness probe was previously using the same endpoint as the readiness probe, which included a database connection check. We suspect that when the liveness probe takes too long due to database latency, it triggers unnecessary container restarts.
This update removes the database check from the liveness probe and also removes liveness initial delay, which should prevent restarts caused by temporary database connection issues.
> CRIMAPP-345 fix pod crash loop

- app/controllers/healthcheck_controller.rb
- config/initializers/lograge.rb
- config/kubernetes/staging/deployment.tpl
- spec/requests/healthcheck_spec.rb
Use simple query for health check
[CRIMAPP-345](https://dsdmoj.atlassian.net/browse/CRIMAPP-345)
`ActiveRecord::Base.connection.active?` was not returning `true` for the health check, which was resulting in the readiness probe failing. This changes the check to use a simple query, to ensure the connection is active.
[CRIMAPP-345]: https://dsdmoj.atlassian.net/browse/CRIMAPP-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Health end point activates db connection

- config/kubernetes/production/deployment.tpl
Add startupProbe to production deployment
[CRIMAPP-345](https://dsdmoj.atlassian.net/browse/CRIMAPP-345)
This configuration has been confirmed to work on staging
[CRIMAPP-345]: https://dsdmoj.atlassian.net/browse/CRIMAPP-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-345 add startup probe to production deploy

- config/kubernetes/staging/prometheus.yml
Increase the sampling period for 4xx and 5xx prometheus alerts.
Updates the alerts to triggers if the total rate exceeds 5 errors per minute, but averaged over a 5-minute period to hopefully reduce number of unnecessary alerts.
> Increase sample period for 5xx and 4xx alerts

- app/aggregates/reviewing/available_reviewer_actions.rb
- app/aggregates/reviewing/review.rb
- app/components/review_action_component.rb
- app/helpers/components_helper.rb
- app/lib/types.rb
- app/models/concerns/reviewable.rb
- app/views/casework/crime_applications/show.html.erb
- config/locales/en/casework.yml
- spec/aggregates/reviewing/available_reviewer_actions_spec.rb
- spec/system/accessibility_spec.rb
- spec/system/casework/reviewing/a_cifc_application_spec.rb
- spec/system/casework/reviewing/a_non_means_application_spec.rb
- spec/system/casework/reviewing/a_pse_application_spec.rb
Actions available to the reviewer can be configured
[CRIMAPP-1320](https://dsdmoj.atlassian.net/browse/CRIMAPP-1320)
Refactor to allow actions available to a reviewer to be configured based on the state of the review, the type of application being reviewed, and the type of assessment required.
In addition to the refactor this PR also removes the redundant ready_for_assessment action for Non-means applications.
This refactor is covered by the system specs.
[CRIMAPP-1320]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1320 available reviewer actions can be configured

- app/aggregates/deciding/decision.rb
- app/aggregates/reviewing.rb
- app/aggregates/reviewing/commands/complete.rb
- app/controllers/casework/completes_controller.rb
- config/locales/en/casework.yml
- config/settings.yml
- spec/aggregates/deciding/decision_spec.rb
- spec/aggregates/reviewing/complete_spec.rb
A fix to address an error where on completing an application the user is redirected to the new confirmation page, which expects at least one funding decision to exist so it can be shown. The user is now redirected to the assigned application list (as it was done before) if there are no funding decisions.
This also fixes an issue where entire decision object were being sent to the Datastore, rather than just the necessary attributes.
The `adding_decisions` feature flag is temporarily **disabled** in **staging** so that the Datastore can be tested in its current state in production-like conditions, where `adding_decisions` is disabled.
[LAA-REVIEW-CRIMINAL-LEGAL-AID-1K](https://ministryofjustice.sentry.io/issues/5968122648/?alert_rule_id=15149521&alert_type=issue&notification_uuid=1270e1be-9 …
> Fix: complete page expects decisions

- config/settings.yml
Enable `adding_decisions` in staging so it can be QA'd.
[CRIMAPP-1355](https://dsdmoj.atlassian.net/browse/CRIMAPP-1355)
[CRIMAPP-1355]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enable adding_decisions in staging

- app/lib/types.rb
- spec/models/application_search_filter_spec.rb
- spec/system/casework/searching/filter_by_age_in_business_days_spec.rb
- spec/system/casework/searching/filter_by_caseworker_spec.rb
- spec/system/casework/searching/filter_by_date_of_birth_spec.rb
- spec/system/casework/searching/filter_by_date_range_spec.rb
- spec/system/casework/searching/filter_by_status_spec.rb
Changes search default from open to all applications 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1385
> [CRIMAPP-1385] Update search default to all applications

- app/controllers/casework/assigned_applications_controller.rb
- app/lib/types.rb
- app/models/get_next.rb
- spec/models/application_search_filter_spec.rb
- spec/system/casework/assigning/get_next_application_spec.rb
- spec/system/casework/searching/filter_by_age_in_business_days_spec.rb
- spec/system/casework/searching/filter_by_caseworker_spec.rb
- spec/system/casework/searching/filter_by_date_of_birth_spec.rb
- spec/system/casework/searching/filter_by_date_range_spec.rb
- spec/system/casework/searching/filter_by_status_spec.rb
Changes search default from open to all applications. This was attempted in PR #722 but there were areas of the app that returned all applications when they shouldn't have been. So this PR also explicitly sets the review status search filter to `open` for assigned applications and get next functions 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1385
> Update search page default review status to all applications

- config/environments/test.rb
- spec/init/api_data.rb
- spec/requests/api/events_spec.rb
- spec/system/casework/viewing_an_application/application_details/supporting_evidence_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
- spec/system/errors_spec.rb
Raise unhandled errors in system specs
The `show_exceptions` setting was incorrectly configured to `:all` in the test environment, causing unhandled exceptions (e.g., WebMock errors) in system specs to be hidden.
Changing the configuration to `:rescuable` ensures that handled error pages are shown, while unhandled errors are properly raised.
> Fix unhandled errors in system specs

- config/kubernetes/staging/ingress.yml
Updated the ModSec rules in staging to prevent common false positives on select endpoints.
Test the endpoints with form input that normally triggers the rules.
> Update ModSec rules in staging

- app/views/casework/crime_applications/_supporting_evidence.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/supporting_evidence_spec.rb
Updates supporting evidence summary card to display card when no files have been uploaded
[dsdmoj.atlassian.net/browse/CRIMAPP-1335](https://dsdmoj.atlassian.net/browse/CRIMAPP-1335)
> [CRIMAPP-1335] Update supporting evidence card design

- app/aggregates/authorising/commands/activate.rb
- app/lib/types.rb
- spec/requests/authentication_spec.rb
Create custom type for auth_subject_id, which was incorrectly set as UUID.
[LAA-REVIEW-CRIMINAL-LEGAL-AID-1Y](https://ministryofjustice.sentry.io/issues/6014323946/)
[CRIMAPP-1440](https://dsdmoj.atlassian.net/browse/CRIMAPP-1440)
[CRIMAPP-1440]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LAA-REVIEW-CRIMINAL-LEGAL-AID-1Y

- app/aggregates/reviewing/commands/receive_application.rb
- spec/models/sns_event/receive_application_event_spec.rb
- spec/requests/api/events_spec.rb
SNS message ID is not a UUID
[LAA-REVIEW-CRIMINAL-LEGAL-AID-1V](https://ministryofjustice.sentry.io/issues/6001868959/)
> Sns message id is not of type UUID

- app/views/casework/crime_applications/_client_details.html.erb
- spec/system/casework/viewing_an_application/appeal_no_changes_application_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
Hides the nino answer row for appeal no changes and under 18 applications as the nino question is not asked
Client contact detail information is also hidden for appeal no changes applications as these questions are not asked during the application
https://dsdmoj.atlassian.net/browse/CRIMAPP-1389
> [CRIMAPP-1389] Hide answer rows when question not asked

- app/aggregates/deciding.rb
- app/aggregates/deciding/commands/unlink.rb
- app/aggregates/deciding/decision.rb
- app/aggregates/reviewing.rb
- app/aggregates/reviewing/commands/remove_decision.rb
- app/aggregates/reviewing/review.rb
- app/components/decision_component.rb
- app/controllers/casework/maat_decisions_controller.rb
- app/controllers/casework/returns_controller.rb
- app/models/concerns/reviewable.rb
- app/views/casework/crime_applications/_funding_decision.html.erb
- config/locales/en/casework.yml
- config/routes.rb
- db/schema.rb
- spec/aggregates/reviewing/review_spec.rb
- spec/system/casework/deciding/adding_another_maat_decision_spec.rb
- spec/system/casework/deciding/removing_a_maat_decision_spec.rb
- spec/system/casework/reviewing/mark_application_as_complete_spec.rb
- spec/system/casework/reviewing/mark_application_as_ready_spec.rb
- spec/system/casework/reviewing/send_back_to_provider_spec.rb
Decisions linked by MAAT ID can be removed.
[CRIMAPP-1361](https://dsdmoj.atlassian.net/browse/CRIMAPP-1361)
- Only MAAT decisions can be removed
- They cannot be removed after the decision has been submitted
- When there are more than one decision, the user is redirected to the decisions/index page.
- When the last decision is removed, the user is redirected to the application details page.
- A previously linked decision, that has been removed, can be linked again. 
- When a removed decision is linked, comments from when previously linked are removed.
[CRIMAPP-1361]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1361 remove a linked decision

- Gemfile
- Gemfile.lock
Bump `laa-criminal-legal-aid-schemas` to v1.4.1.
[CRIMAPP-1398](https://dsdmoj.atlassian.net/browse/CRIMAPP-1398)
[CRIMAPP-1398]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1398] Bump schemas to v1.4.1

- app/views/casework/crime_applications/sections/_employment.html.erb
- app/views/casework/crime_applications/sections/_partner_employment.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/employment_spec.rb
- spec/system/casework/viewing_an_application/application_details/partner_employment_spec.rb
Displays answer for armed forces question when client or partner are in the armed forces question
If the answer is no or the question was not asked, then the question is not displayed
https://dsdmoj.atlassian.net/browse/CRIMAPP-1468
**When answer is yes**
**When answer is no**
Submit an application in apply where the client/partner armed forces question is **yes** (client/partner must be employed). Confirm that the answer is displayed.
Submit an application in apply where the client/partner armed forces question is **no** (client/partner must be employed). Confirm that the answer is **not** displayed.
> [CRIMAPP-1468] Display armed forces question in review

- app/models/reporting/workload_report.rb
- app/models/reporting/workload_report_row.rb
- app/views/reporting/base/_workload_report.en.html.erb
- spec/models/reporting/workload_report_spec.rb
- spec/system/reporting/workload_report_spec.rb
Show only the zero to 4 business days on the detailed workload report.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1472
The data for days 5-9 is not useful, but it requires the same computational resources as the critical data from days 0-4. While optimisation is planned for this report, implementing this change should significantly reduce the processing time for these reports in the meantime.
The data for days 5-9 will still be able in the current workload reports.
> Workload report only shows 0..4 business days

- .trivyignore
Updated the Trivy ignore file with vulnerabilities that are to do with the Cloud Platform and not our code. These will be ignored until 14th May, 2025.
[CRIMAPP-1476](https://dsdmoj.atlassian.net/browse/CRIMAPP-1476)
[CRIMAPP-1476]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1476] Ignore Trivy vulns outside our control

- .github/workflows/snyk-container.yml
- .github/workflows/snyk-infrastructure.yml
- .github/workflows/test-build-deploy.yml
Updated the following GitHub Actions dependencies:
1. `actions/cache@v3` -> `actions/cache@v4`
2. `actions/upload-artifact@v3` - > `actions/upload-artifact@v4`
3. `aws-actions/amazon-ecr-login@v1` - > `aws-actions/amazon-ecr-login@v2`
4. `actions/checkout@v3` -> `actions/checkout@v4`
5. `aws-actions/configure-aws-credentials@v3` - > `aws-actions/configure-aws-credentials@v4`
[CRIMAPP-1353](https://dsdmoj.atlassian.net/browse/CRIMAPP-1353)
[CRIMAPP-1353]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update GitHub Actions

- app/views/users/sessions/new.html.erb
Removed the content line about eForms from the homepage.
[CRIMAPP-1495](https://dsdmoj.atlassian.net/browse/CRIMAPP-1495)
[CRIMAPP-1495]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1495] Remove eForms link

- app/models/reporting/snapshot.rb
- config/locales/en.yml
- spec/models/reporting/snapshot_spec.rb
- spec/system/casework/viewing_an_application/history_spec.rb
- spec/system/casework/viewing_an_application/post_submission_evidence_application_spec.rb
- spec/system/casework/viewing_an_application/that_is_open_and_unassigned_spec.rb
- spec/system/reporting/snapshot_reports_spec.rb
- spec/system/reporting/workload_report_spec.rb
Updates time display to 12hr from 24hr clock where applicable
Impacts the following screens: 
- Application details (date stamp)
- Application history 
- User competencies history
- Workload report
https://dsdmoj.atlassian.net/browse/CRIMAPP-1412
> [CRIMAPP-1412] Update time display across app

- config/locales/en.yml
- spec/system/manage_competencies/history_spec.rb
Update datetime view to display date before the time
This impacts the competencies and user manager screens 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1412
> [CRIMAPP-1412] Update datetime view

- app/services/datastore/documents/download.rb
- spec/services/datastore/documents/download_spec.rb
- spec/shared_contexts/when_downloading_a_document.rb
Update `response_content_disposition` for uploaded files to handle file names that contain characters outside the ISO-8859-1 character set.
[CRIMAPP-1510](https://dsdmoj.atlassian.net/browse/CRIMAPP-1510)
Upload a file whose name contains UTF-8 characters on Apply and attempt to download them on Review.
Some examples that would normally fail:
- `Document 1 – Main Account 1-15 November.pdf`
- `Payslip - Sept ‘24.pdf`
[CRIMAPP-1510]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1510] Sanitise upload file names

- app/assets/stylesheets/local/custom.scss
Make search form accessible at 400% zoom
[CRIMAPP-1529](https://dsdmoj.atlassian.net/browse/CRIMAPP-1529)
[CRIMAPP-1529]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1529 search input can handle 400% zoom

- app/assets/stylesheets/local/custom.scss
- app/views/casework/application_searches/search.html.erb
Search results table scrolls to allow viewing at 250% zoom
[CRIMAPP-1531](https://dsdmoj.atlassian.net/browse/CRIMAPP-1531)
[CRIMAPP-1531]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1531 search results table can scroll

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Disable ModSec rule 933160 to prevent false positives on the `{application_id}/return` endpoint.
[Slack conversation](https://mojdt.slack.com/archives/C06GX24DV26/p1736354100125169)
> Update ModSec rules

- Gemfile.lock
- app/assets/stylesheets/local/custom.scss
- app/views/casework/base/_primary_navigation.html.erb
- app/views/layouts/govuk_template.html.erb
- spec/system/errors_spec.rb
- spec/system/manage_users/deactivate_a_user_spec.rb
- spec/system/manage_users/reactivate_a_user_spec.rb
Replace MoJ primary navigation with Govuk service navigation.
[CRIMAPP-1568](https://dsdmoj.atlassian.net/browse/CRIMAPP-1568)
Replacing the MoJ primary navigation with the GOVUK Service navigation improves accessibility at higher magnification. While we discussed adopting the latest GOVUK  header navigation recommendations, we agreed that a deeper review of the navigation was necessary. For now, we will retain the current navigation approach but replace the view component to address accessibility issues when zoomed.
[CRIMAPP-1568]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1568] Replace MoJ primary navigation with Govuk

- app/views/casework/application_searches/search.html.erb
- spec/system/casework/searching/search_filters_and_results_spec.rb
Rename search result caseworker column from "Closed by" to "Caseworker"
[CRIMAPP-1536](https://dsdmoj.atlassian.net/browse/CRIMAPP-1536)
Search shows both open and closed applications and needs to show the name of the assigned caseworker.
[CRIMAPP-1536]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1536 rename search result caseworker column header

- app/views/casework/crime_applications/_capital_details.html.erb
- app/views/casework/crime_applications/sections/_properties.html.erb
Fixes the assets heading which was displaying even when the assets question was not asked
**When assets question asked**
> Assets heading only displays if question asked

- app/components/decision_component.html.erb
- app/components/decision_overall_result_component.rb
- app/helpers/components_helper.rb
- app/services/maat/means_translator.rb
- config/locales/en/casework.yml
- spec/components/decision_component_spec.rb
- spec/components/decision_overall_result_component_spec.rb
Overall results indicates when contribution possible.
[CRIMAPP-1569](https://dsdmoj.atlassian.net/browse/CRIMAPP-1569)
This change is for User Research at this stage. Adds two additional overall results "Granted - with contribution" and "Granted - failed means test" in addition to "Granted" and "Failed".
[CRIMAPP-1569]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1569 overall result indicates when contribution possible

- app/assets/stylesheets/local/custom.scss
- app/views/casework/crime_applications/_review_overview.html.erb
Duplicate ids on the application details screen were flagged as having potential to cause accessibility issues for screen readers, as the reader might ignore the second instance of the same id. They were changed to css classes. 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1545
> [CRIMAPP-1545] Use classes to implement superseded stying

- config/routes.rb
- spec/requests/authorisation_spec.rb
- spec/system/authenticating/a_signed_out_user_spec.rb
- spec/system/casework/deciding/adding_a_maat_decision_by_reference_spec.rb
- spec/system/errors_spec.rb
- spec/system/manage_competencies/viewing_spec.rb
- spec/system/manage_users/add_user_spec.rb
- spec/system/manage_users/change_user_role_spec.rb
- spec/system/manage_users/revive_a_user_spec.rb
- spec/system/manage_users/viewing_spec.rb
Updates the routes to use dashes instead of underscores.
Temporarily retains underscored paths to ensure that back links and form URLs don't break for users using the service at the time of deployment.
[CRIMAPP-1503](https://dsdmoj.atlassian.net/browse/CRIMAPP-1503)
[CRIMAPP-1503]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1503] Update URLs to use dashes

- app/aggregates/deciding/decision.rb
- app/components/decision_component.html.erb
- app/components/decision_component.rb
- app/models/decisions/draft.rb
- app/services/maat/decision_translator.rb
- config/locales/en/casework.yml
- spec/aggregates/reviewing/complete_spec.rb
- spec/components/decision_overall_result_component_spec.rb
- spec/services/maat/decision_translator_spec.rb
- spec/system/casework/deciding/adding_a_maat_decision_by_maat_id_spec.rb
- send the court_type and overall_result to datastore
- show the 'Means type' (court_type) on the decision summary card
-  ignore funding decision of MAAT decisions without a means result
[CRIMAPP-1577](https://dsdmoj.atlassian.net/browse/CRIMAPP-1577)
The MAAT API can return partially completed results. During reassessment, the MAAT API maintains the previous funding decision until the means assessment is completed. Therefore, funding decisions that exist without a corresponding means result should be ignored.
[CRIMAPP-1577]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1577 Store MAAT overall result and CaseType

- config/locales/en/casework.yml
- spec/components/decision_overall_result_component_spec.rb
Rename "Granted - with a contribution" "Granted - with contribution"
Rename "Passed - with a contribution" "Passed - with contribution"
[CRIMAPP-1581](https://dsdmoj.atlassian.net/browse/CRIMAPP-1581)
[CRIMAPP-1581]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Rename "with a contribution" "with contribution"

- app/aggregates/reviewing/available_reviewer_actions.rb
- app/lib/types.rb
- spec/aggregates/reviewing/available_reviewer_actions_spec.rb
- spec/system/casework/deciding/adding_a_cifc_decision_spec.rb
- spec/system/casework/reviewing/a_cifc_application_spec.rb
Skip "Mark as ready for MAAT" if CIFC
[CRIMAPP-1583](https://dsdmoj.atlassian.net/browse/CRIMAPP-1583)
The review process for CIFC applications differs from "initial" means-assessed applications. Instead of creating a new MAAT record, the CIFC application links to the original application's MAAT decision. Caseworkers manually adjust the original decision's means information based on the CIFC application's details, making the "Mark as ready for MAAT" action unnecessary.
This issue was identified during the outcome playback work. However, this change to remove "Mark as ready for MAAT" for CIFC will also effect current CIFC applications (i.e. before the outcome playback feature is enabled).
[CRIMAPP-1579]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> CRIMAPP-1583 skip mark_as_ready if CIFC

- app/views/layouts/casework.html.erb
- app/views/layouts/govuk_template.html.erb
- config/initializers/govuk_components.rb
- config/locales/en/helpers.yml
Adds feedback survey link to phase banner 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1575
> Add review feedback survey link

- app/aggregates/deciding/commands/set_funding_decision.rb
- app/aggregates/deciding/decision.rb
- app/components/decision_overall_result_component.rb
- app/services/maat/decision_translator.rb
- app/services/maat/overall_result_translator.rb
- spec/aggregates/reviewing/complete_spec.rb
- spec/components/decision_component_spec.rb
- spec/components/decision_overall_result_component_spec.rb
- spec/services/maat/overall_result_translator_spec.rb
- spec/support/decision_form_helpers.rb
- spec/system/casework/deciding/adding_a_maat_decision_by_maat_id_spec.rb
- spec/system/casework/deciding/submitting_a_non_means_decision_spec.rb
Revert to using eForm's overall result text
[CRIMAPP-1597](https://dsdmoj.atlassian.net/browse/CRIMAPP-1597)
[CRIMAPP-1597]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1597 revert to using eForm's overall result text

- Gemfile
- Gemfile.lock
- app/aggregates/deciding/commands/set_funding_decision.rb
- app/aggregates/deciding/decision.rb
- app/aggregates/deciding/overall_result_calculator.rb
- app/components/decision_overall_result_component.rb
- app/models/decisions/draft.rb
- config/locales/en/casework.yml
- spec/aggregates/deciding/overall_result_calculator_spec.rb
- spec/aggregates/reviewing/complete_spec.rb
- spec/components/decision_component_spec.rb
- spec/components/decision_overall_result_component_spec.rb
- spec/system/casework/deciding/adding_a_maat_decision_by_maat_id_spec.rb
- spec/system/casework/deciding/submitting_a_non_means_decision_spec.rb
Store the overall result as a type. 
[CRIMAPP-1597](https://dsdmoj.atlassian.net/browse/CRIMAPP-1597)
The initial plan was to store MAAT strings directly in the datastore overall_result, as MAAT is the source of truth for decisions and its logic is complex. However, testing has shown that these strings do not fully meet providers' needs and may cause confusion.
Instead, we will store a constant representing the overall result, which clients can translate into text as needed. This result will combine the funding_decision with any relevant qualifications that help providers understand the next steps.
The overall result is now displayed to the user in the format funding_decision - qualification, e.g., "Granted - with contribution" or "Refused - failed IoJ". In the datastore, these values are …
> CRIMAPP-1597 store overall_result type rather than string

- app/aggregates/deciding.rb
- app/aggregates/deciding/commands/unlink.rb
- app/aggregates/reviewing/commands/send_back.rb
- app/controllers/casework/maat_decisions_controller.rb
- app/controllers/casework/returns_controller.rb
- app/views/casework/returns/new.html.erb
- config/initializers/event_store.rb
- config/locales/en/casework.yml
- spec/rails_helper.rb
- spec/system/casework/deciding/adding_another_maat_decision_spec.rb
- spec/system/casework/reviewing/send_back_to_provider_spec.rb
Unlink draft decisions on return to provider
Content updates to the return to provider confirm page
[CRIMAPP-1589](https://dsdmoj.atlassian.net/browse/CRIMAPP-1589)
Otherwise resubmissions will not be able to link decisions linked to the original application.
[CRIMAPP-1589]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1589] unlink draft decisions on return to provider

- app/views/casework/decisions/comments/edit.html.erb
- app/views/casework/decisions/interests_of_justices/edit.html.erb
- app/views/casework/decisions/overall_results/edit.html.erb
- app/views/casework/maat_decisions/new.html.erb
- config/locales/en/casework.yml
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/reporting.yml
- spec/support/decision_form_helpers.rb
- spec/system/casework/assigning/viewing_your_assigned_applications_spec.rb
- spec/system/casework/closed_applications_dashboard_spec.rb
- spec/system/casework/deciding/adding_a_non_means_decision_spec.rb
- spec/system/casework/open_applications_dashboard_spec.rb
- spec/system/casework/reviewing/mark_application_as_ready_spec.rb
- spec/system/casework/reviewing/send_back_to_provider_spec.rb
- spec/system/casework/searching/search_filters_and_results_spec.rb
- spec/system/casework/searching/sorting_search_results_spec.rb
Makes content updates ahead of outcome playback release. Updates: 
- Link this application to a MAAT ID needs to be H2 heading (to not conflict with the applicant’s name that’s already an H1 heading)
- Success message after linking to MAAT currently says: ‘You marked the application as ready for assessment’ - change to: >> ‘Application ready for assessment in MAAT.’
- Change tab heading Type of application >> Application type
- In manual funding decision flow, correct headings to: 
- [client’s name] = h1
- Interest of justice test / Means test / Overall result = h2 
- Reason for result [h3]
- Caseworker name [h3]
- Date of test  [h3]
- In manual funding decision flow, correct error messages to:
- Interest of justice test / Means test / Overall result = Select a result for the [Interest of …
> [CRIMAPP-1606] Content updates

- app/views/casework/crime_applications/sections/_properties.html.erb
This ensures that the client's assets are shown based on the properties they've declared. This addresses an issue where some applications will have both `has_no_properties: "yes"` and declared properties due to a bug on Apply.
[CRIMAPP-1641](https://dsdmoj.atlassian.net/browse/CRIMAPP-1641)
[CRIMAPP-1641]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1641] Show assets based on properties array

- config/routes.rb
Follow up of https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/795 to remove the temporarily retained underscored paths that were added to ensure continuity whilst urls were updated
[dsdmoj.atlassian.net/browse/CRIMAPP-1503](https://dsdmoj.atlassian.net/browse/CRIMAPP-1503)
> [CRIMAPP-1503] Remove temporary underscored routes

- app/assets/stylesheets/local/custom.scss
- app/javascript/local/copy_text.js
- app/views/casework/crime_applications/_review_overview.html.erb
If the browser has Javascript disabled. The "Copy reference number" link is hidden.  When the link is selected, the screen reader announces this.
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?selectedIssue=CRIMAPP-1543
To disable Javascript on chrome, go to chrome://settings/content/javascript and select "dont allow sites to use Javascript".
Activate MacOS Voiceover using CMD + Fn + F5
You can tab into the "copy reference number" link then press CTRL + OPT + SPACE (MacOs)
> [CRIMAPP-1543] Hide link if no JS & link copy announcement

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Remove OWASP 942360 from return reasons
[CRIMAPP-1677](https://dsdmoj.atlassian.net/browse/CRIMAPP-1677)
[CRIMAPP-1677]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1677] remove OWASP 942360 from return reasons

- app/assets/stylesheets/local/govuk.scss
- app/assets/stylesheets/local/phase_banner.scss
Fix phase banner colour regression.
Fix configuration of global styles for GOVUK Frontend
[
](url)
> Fix phase banner colour and global style config

- app/javascript/application.js
- app/views/casework/crime_applications/_case_details.html.erb
- app/views/casework/crime_applications/_overview.html.erb
Fixes bug with copy urn link in the case details section which was not working 
This is because there were duplicate IDs for the copy urn links on the page 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1690
> [CRIMAPP-1690] Fix copy urn link

- app/models/reporting/weekly_report.rb
- app/views/reporting/temporal_reports/_return_reasons_report.en.html.erb
- spec/system/reporting/weekly_reports_spec.rb
Updates the weekly report date formatting to display the year of both dates when the week spans a new year
https://dsdmoj.atlassian.net/browse/CRIMAPP-1701
> [CRIMAPP-1701] Amend weekly report date formatting

- config/kubernetes/staging/ingress.yml
Updated the ModSec ingress controller on staging for testing purposes ahead of the wider roll out on 15th April.
[CRIMAPP-1721](https://dsdmoj.atlassian.net/browse/CRIMAPP-1721)
[CRIMAPP-1721]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1721] Upgrade ModSec controller on staging

- app/components/offence_class_component.rb
This change moves the 'Not determined' offence class tag to a new line. This fixes the issue where the tag gets selected when caseworkers double-click the text to copy the offence name.
[CRIMAPP-1725](https://dsdmoj.atlassian.net/browse/CRIMAPP-1725)
[CRIMAPP-1725]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1725] Change undetermined offence class tag spacing

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Disable ModSec rule 932380 to prevent false positives on the `{application_id}/return` endpoint.
This rule was triggered by text that has CRLF line breaks (\r\n), followed by the words 'if' and 'for', making ModSec think it was a Windows Command Injection.
[CRIMAPP-1727](https://dsdmoj.atlassian.net/browse/CRIMAPP-1727)
Attempt to return an application and have the return reason contain text with CRLF line breaks followed by 'if' and 'for'. The rule should not be triggered and you should be able to return the application.
[CRIMAPP-1727]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1727] Disable ModSec rule 932380

- app/components/offence_class_component.rb
- app/views/casework/crime_applications/_offences.html.erb
- config/locales/en/casework.yml
- spec/system/casework/viewing_an_application/application_details/offences_spec.rb
This updates the offence summary card text and splits the 'Offence type and class' row into two to match the designs in Figma. This also solves the issue where the offence class would get selected when caseworkers double-clicked to offence name, intending to only copy the name and not the class.
[CRIMAPP-1725](https://dsdmoj.atlassian.net/browse/CRIMAPP-1725)
[Figma design](https://www.figma.com/design/TELZW9jdNqFcrI4yZoH7BV/Crime-Review?node-id=7877-4401&t=5gA6k9toOvWaOJVL-1)
[CRIMAPP-1725]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1725] Update offence summary card

- config/application.rb
This addresses the issue discovered by the latest AppSec test where the HTML tags allowed by `Rails::HTML5::SafeListSanitizer` may be used in our text boxes to alter the HTML of user input when it is rendered, for example in our summary cards.
[CRIMAPP-1675](https://dsdmoj.atlassian.net/browse/CRIMAPP-1675)
Many of the affected fields already call `simple_format`, which sanitizes input by default. Other fields that are affected on Apply, such as client and partner names and addresses, seem to output HTML tags as text. The config change ensures that no HTML tags are allowed.
[CRIMAPP-1675]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1675] Fully sanitize HTML

- app/views/casework/crime_applications/sections/_income_benefits.html.erb
- app/views/casework/crime_applications/sections/_income_benefits_partner.html.erb
- app/views/casework/crime_applications/sections/_income_payments.html.erb
- app/views/casework/crime_applications/sections/_income_payments_partner.html.erb
- spec/system/casework/viewing_an_application/application_details/income_benefits_spec.rb
- spec/system/casework/viewing_an_application/application_details/income_payments_spec.rb
This fixes a formatting issue in the summary cards for income payments and benefits where line breaks are removed in user input and HTML tags are left in.
[CRIMAPP-1675](https://dsdmoj.atlassian.net/browse/CRIMAPP-1675)
[CRIMAPP-1675]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1675] Summary card answer formatting fix

- .env.development
- Gemfile
- Gemfile.lock
- app/notifiers/sent_back_notifier.rb
- config/application.rb
- config/initializers/sidekiq.rb
- config/kubernetes/staging/deployment-worker.yml
- config/routes.rb
- config/sidekiq.yml
- docker-compose.yml
- spec/requests/authorisation_spec.rb
- spec/shared_contexts/with_a_stubbed_mailer.rb
- spec/system/casework/reviewing/send_back_to_provider_spec.rb
This change adds Sidekiq to process background jobs. This initial configuration is to be tested in staging in preparation for work to implement automatically generated monthly reports. As a first test, this change should make it so that `application_returned_email` jobs are delegated to the `mailers` queue by Sidekiq.
This relies on an ElastiCache (Redis) instance deployed on CloudPlatform.
I've added Prometheus metrics that we could use to track and set up alerts. We could also set up a Grafana dashboard, as NSCC have done [here](https://grafana.live.cloud-platform.service.justice.gov.uk/d/laa-submit-crime-forms-sidekiq-metrics/laa-non-standard-crime-claims-sidekiq-metrics?from=now-24h&to=now&timezone=browser&var-namespace=laa-assess-crime-forms-prod&var-job=SendEmailToProvider&refresh=1m …
> [CRIMAPP-1679] Add Sidekiq

- config/kubernetes/staging/deployment-worker.tpl
A small change to fix the `deployment-worker` readiness probe, which was checking for a file in the wrong directory.
> [CRIMAPP-1679] Fix worker readiness probe

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
- Remove attack-rce rules from session cookie
- Remove attack-injection-php from session cookie
- Groups session cookie rules for clarity
[CRIMAPP-1748](https://dsdmoj.atlassian.net/browse/CRIMAPP-1748)
The rails session cookie is signed to prevent tampering and is stored in the client so ignoring to avoid significant user pain. Fix confirmed on staging.
[CRIMAPP-1748]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1748] Remove attack-rce rules from session cookie

- app/lib/prometheus_metrics/configuration.rb
- config/initializers/sidekiq.rb
- config/kubernetes/staging/deployment-worker.tpl
- config/kubernetes/staging/deployment.tpl
- config/kubernetes/staging/service.yml
This change enables Prometheus to collect metrics from Sidekiq, alongside this change on Cloud Platform: https://github.com/ministryofjustice/cloud-platform-environments/pull/32646
> [CRIMAPP-1679] Fix and enable Prometheus for Sidekiq

- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/kubernetes/staging/config_map.yml
- config/kubernetes/staging/deployment-worker.tpl
- config/kubernetes/staging/deployment.tpl
- config/storage.yml
- db/migrate/20250506083556_create_active_storage_tables.active_storage.rb
- db/schema.rb
This change sets up ActiveStorage with an S3 bucket to be used to store generated reports. S3 bucket created here: https://github.com/ministryofjustice/cloud-platform-environments/pull/32693
This is for staging only. A separate PR will be created to do this for production.
> [CRIMAPP-1679] Use ActiveStorage S3 to store generated reports (staging)

- Gemfile
- Gemfile.lock
This adds the missing `aws-sdk-s3` gem that was forgotten in the last PR, causing staging to crash.
> [CRIMAPP-1679] Add aws-sdk-s3 gem

- app/controllers/reporting/generated_reports_controller.rb
- app/controllers/reporting/user_reports_controller.rb
- app/jobs/generate_downloadable_temporal_report_job.rb
- app/models/generated_report.rb
- app/models/reporting/caseworker_report.rb
- app/models/reporting/temporal_report.rb
- app/views/reporting/user_reports/index.html.erb
- config/locales/en/reporting.yml
- config/routes.rb
- config/sidekiq.yml
- db/migrate/20250506144826_create_generated_reports.rb
- db/schema.rb
- spec/jobs/generate_downloadable_temporal_report_job_spec.rb
- spec/models/reporting/caseworker_report_spec.rb
- spec/rails_helper.rb
- spec/requests/authorisation_spec.rb
- spec/system/reporting/generated_reports_spec.rb
This change creates the job `GenerateDownloadableTemporalReportJob`, which creates and stores a CSV report for the given report type and interval. For now, the job creates a report for the previous month, week, or day, relative to when the job is executed. Additionally, the job is scheduled to run every 15 minutes for quick testing on staging.
The table `generated_reports` stores the reports generated by the job.
The generated reports are shown as download links in a basic layout on `/reporting` for authorised users only.
> [CRIMAPP-1679] Create GeneratedReports table and job

- config/kubernetes/staging/deployment-worker.tpl
- config/kubernetes/staging/deployment.tpl
This adds the service account name to staging deployments to (hopefully) allow access to S3 using IRSA. Accompanying CloudPlatform PR: https://github.com/ministryofjustice/cloud-platform-environments/pull/32815
> [CRIMAPP-1679] Add service account name to staging

- app/lib/prometheus_metrics/configuration.rb
- app/notifiers/access_granted_notifier.rb
- app/notifiers/role_changed_notifier.rb
- app/notifiers/sent_back_notifier.rb
- config/application.rb
- config/initializers/sidekiq.rb
- config/kubernetes/production/deployment-worker.tpl
- config/kubernetes/production/service.yml
- config/routes.rb
- config/sidekiq.yml
- spec/shared_contexts/with_a_stubbed_mailer.rb
- spec/system/manage_users/add_user_spec.rb
- spec/system/manage_users/change_user_role_spec.rb
This change:
- Makes all mail delivery async
- Removes redundant production checks, enabling Sidekiq in production
- Applies the necessary infrastructure changes to create worker pods in production
- Adds a monthly caseworker report to the scheduler
Accompanying CloudPlatform PR: https://github.com/ministryofjustice/cloud-platform-environments/pull/32848
> [CRIMAPP-1679] Enable Sidekiq and update infrastructure in prod

- app/models/concerns/user_role.rb
- config/routes.rb
- spec/models/concerns/user_role_spec.rb
This change limits access to the Sidekiq Web UI to admin/user managers in staging and locally. There will be no way to access it in hosted production.
> [CRIMAPP-1679] Limit access to Sidekiq Web

- Gemfile
- Gemfile.lock
- app/controllers/casework/base_controller.rb
- app/controllers/casework/crime_applications_controller.rb
- app/controllers/errors_controller.rb
- app/views/errors/datastore_error.html.erb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/unprocessable_entity.html.erb
- config/application.rb
- config/environments/test.rb
- config/locales/en/errors.yml
- spec/system/casework/reviewing/mark_application_as_ready_spec.rb
- spec/system/casework/reviewing/send_back_to_provider_spec.rb
- spec/system/errors_spec.rb
Show better error messages for Datastore API errors
[CRIMAPP-1769](https://dsdmoj.atlassian.net/browse/CRIMAPP-1769)
[CRIMAPP-1769]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1769] improve datastore error messages

- app/models/reporting/caseworker_report.rb
- app/models/review.rb
- app/read_models/caseworker_reports/basic_projection.rb
- app/read_models/caseworker_reports/event_dataset.rb
- app/read_models/caseworker_reports/row.rb
- app/read_models/caseworker_reports/work_queue_projection.rb
- spec/models/reporting/caseworker_report_spec.rb
- spec/read_models/caseworker_reports/basic_projection_spec.rb
- spec/read_models/caseworker_reports/work_queue_projection_spec.rb
This change creates a new projection for the Caseworker Report, which breaks down assignment and review events by work queue. This projection is only used to generate the CSV; the existing report in the UI (renamed to `basic_projection`) remains untouched.
This projection will list a row for each work stream (+ PSE) per user, leaving the table open for further transformation as needed. We will need to confirm with the data analyst if this format is useful.
[CRIMAPP-1694](https://dsdmoj.atlassian.net/browse/CRIMAPP-1694)
Very basic example of the generated CSV
Go to `/sidekiq` as a user manager/admin, click on Recurring Jobs and manually enqueue the 'monthly_caseworker_report' job, which will generate the CSV and make it downloadable from the Caseworker Report page. There might already be …
> [CRIMAPP-1694] Breakdown caseworker report CSV by work queue

- config/kubernetes/staging/ingress.yml
- configures an IP allowlist in staging
- removes ModSec exemptions previously based on session cookie.
- applies ModSec those exemptions directly to /return and /comment
- returns status 423 for ModSec errors when request IP is in range
[CRIMAPP-1791](https://dsdmoj.atlassian.net/browse/CRIMAPP-1791)
[CRIMAPP-1791]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1791] Configures an IP allowlist in staging

- config/kubernetes/staging/ingress.yml
Move from nginx to ModSec for IP filtering. 
This enables a custom error status to be used for ModSec errors on requests on the IP allow list.
Prior to change:
- Allowed IP + ModSec violation -> 423
- Disallowed IP + ModSec violation -> 423
- Disallowed IP + no ModSec violation -> 403 (from NGINX allowlist)
After change:
- Allowed IP + ModSec violation -> 423
- Disallowed IP + ModSec violation -> 403
- Disallowed IP + no ModSec violation -> 403 (from ModSec rule 1001)
[CRIMAPP-1742](https://dsdmoj.atlassian.net/browse/CRIMAPP-1742)
[CRIMAPP-1742]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1742] add IP allow list ModSec rule

- .github/workflows/snyk-container.yml
This change updates the Snyk Container workflow by adding a couple of `security-severity` fixes that should resolve the errors in the current workflow.
This also adds the ability to run the workflow manually for testing purposes.
As part of this, I have updated the `SNYK_TOKEN` secret to be my PAT while I'm testing this. If we're happy with using Snyk as our main container image scanner, we should create a service account and use a Snyk token linked to it.
[CRIMAPP-1795](https://dsdmoj.atlassian.net/browse/CRIMAPP-1795)
Run the Snyk Container workflow and check the output.
[CRIMAPP-1795]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1795] Update Snyk Container workflow

- config/kubernetes/production/ingress.yml
- introduce public ingress for /health, /ping, api/events etc
- apply an ModSec ip allowlist to application ingress
- use custom error (423) for ModSec errors on requests on IP allow list
[CRIMAPP-1742](https://dsdmoj.atlassian.net/browse/CRIMAPP-1742)
Copies over ingress changes tested on staging
[CRIMAPP-1742]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1742] production ingress allow list and ModSec

- config/kubernetes/production/ingress.yml
Remove api/events from public ingress
Only allow GET requests to public endpoints
[CRIMAPP-1815](https://dsdmoj.atlassian.net/browse/CRIMAPP-1815)
[CRIMAPP-1815]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1815] remove api/events from public ingress

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
- Remove public ingress
- Creates a dedicated ingress for `ping` and `datastore/ping` which applies the pingdom ip allowlist and restricts to GET requests. https://my.pingdom.com/probes/ipv4
- Remaining endpoints are configured by the application ingress which is restricted to the latest laa allow list https://github.com/ministryofjustice/laa-ip-allowlist/blob/main/cidrs.txt
[CRIMAPP-1814](https://dsdmoj.atlassian.net/browse/CRIMAPP-1814)
[CRIMAPP-1814]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1815] remove all public endpoints

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Update public ingress to include only pingdom
[CRIMAPP-1814](https://dsdmoj.atlassian.net/browse/CRIMAPP-1814)
Application of the pingdom ingress was being blocked because of a collision with previous public ingress. This fixes that by updating the public ingress with the pingdom rules.
[CRIMAPP-1814]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1815] update public ingress to be pingdom only

- config/kubernetes/production/config_map.yml
This change adds the missing `AWS_S3_REGION` env variable to production. This was preventing Active Storage from connecting to S3 and crashing the application.
> Add missing AWS Region to prod configmap

- config/kubernetes/production/deployment-worker.tpl
This change reduces the worker (Sidekiq) pod number from 4 to 2 in production.
> Reduce worker replicas to 2

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Update ModsecRule applied to the rails session cookie to prevent observed false positive.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1826
- fix confirmed on staging
- also confirmed that other modsec rules are still applied
> [CRIMAPP-1826] remove attack-injection-php rules from session cookie

- app/views/application/_copy_link.html.erb
Copy links not changing to purple visited state when clicked as per designs due to href on link being set to '#' 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1740
> [CRIMAPP-1740] Copy link qa fix

- app/services/aws/message_poller.rb
- config/kubernetes/staging/deployment-message-poller.tpl
This change adds a readiness probe to `message_poller` so Kubernetes knows when the pod is ready and existing replicas can be destroyed.
[CRIMAPP-1821](https://dsdmoj.atlassian.net/browse/CRIMAPP-1821)
[CRIMAPP-1821]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1821] Add readiness probe to message poller

- app/jobs/aws_message_processing_job.rb
- app/services/aws/message_processor.rb
- Disable argument logging for `AwsMessageProcessingJob`. The arguments passed to this job contain potentially sensitive SNS message metadata.
- `Aws::MessageProcessor` logging is now debug-only to prevent message data from being logged in production.
[CRIMAPP-1821](https://dsdmoj.atlassian.net/browse/CRIMAPP-1821)
[CRIMAPP-1821]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1821] Limit message poller logging

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Auth token randomness was causing false +ves. Token itself is server-generated and containing sqli not exploitable because of framework controls.
> Remove attach-sqli rule 942100 from authenticity token
